"""instrument foundation

Revision ID: b144f727c418
Revises: 
Create Date: 2026-04-16 09:08:07.065498
"""
from datetime import UTC, datetime

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b144f727c418'
down_revision = None
branch_labels = None
depends_on = None


REFERENCE_CREATED_AT = datetime(2026, 4, 16, tzinfo=UTC)

FIELD_CATEGORIES_SNAPSHOT = [
    {"category_code": "general", "display_order": 1, "label": "General"},
    {"category_code": "basics", "display_order": 2, "label": "Basics"},
    {"category_code": "fees_terms", "display_order": 3, "label": "Fees & Terms"},
    {
        "category_code": "performance_risk",
        "display_order": 4,
        "label": "Performance & Risk",
    },
    {"category_code": "exposure", "display_order": 5, "label": "Exposure"},
    {
        "category_code": "ratings_analysis",
        "display_order": 6,
        "label": "Ratings & Analysis",
    },
    {"category_code": "monitoring", "display_order": 7, "label": "Monitoring"},
    {
        "category_code": "custom_attributes",
        "display_order": 8,
        "label": "Custom Attributes",
    },
]

INSTRUMENT_ATTRIBUTE_DEFINITIONS_SNAPSHOT = [
    {
        "attribute_key": "coverage_status",
        "data_type": "single_select",
        "default_visible": True,
        "description": "Research status such as invested, focus, or watch.",
        "is_filterable": True,
        "is_groupable": True,
        "is_view_column": True,
        "label": "Coverage Status",
        "options": ["Invested", "Focus", "Watch", "Archived"],
    },
    {
        "attribute_key": "focus_bucket",
        "data_type": "single_select",
        "default_visible": False,
        "description": "Internal attention bucket for near-term review priority.",
        "is_filterable": True,
        "is_groupable": True,
        "is_view_column": True,
        "label": "Focus Bucket",
        "options": ["Tier 1", "Tier 2", "Tier 3"],
    },
    {
        "attribute_key": "is_invested",
        "data_type": "boolean",
        "default_visible": False,
        "description": "Whether the instrument is currently in the invested book.",
        "is_filterable": True,
        "is_groupable": True,
        "is_view_column": True,
        "label": "Currently Invested",
        "options": [],
    },
]

FIELD_REGISTRY_SNAPSHOT = [
    {
        "instrument_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "category_code": "general",
        "data_type": "string",
        "default_visible": True,
        "default_width": 320,
        "description": "Canonical instrument display name from the watchlist row read model.",
        "field_key": "instrument_name",
        "filter_mode": "text",
        "formatter_code": "text",
        "group_mode": "discrete",
        "label": "Name",
        "product_scope_json": [],
        "sort_mode": "alpha",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.instrument_name",
    },
    {
        "instrument_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "category_code": "general",
        "data_type": "string",
        "default_visible": False,
        "default_width": 140,
        "description": "Top-level instrument type resolved from shared identity.",
        "field_key": "instrument_type",
        "filter_mode": "multi_select",
        "formatter_code": "text",
        "group_mode": "discrete",
        "label": "Instrument Type",
        "product_scope_json": [],
        "sort_mode": "alpha",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.instrument_type",
    },
    {
        "instrument_scope_json": [],
        "availability_rule_json": {"requires": ["primary_identifier"]},
        "category_code": "general",
        "data_type": "string",
        "default_visible": True,
        "default_width": 140,
        "description": "Primary public identifier for the row.",
        "field_key": "ticker_or_isin",
        "filter_mode": "text",
        "formatter_code": "identifier",
        "group_mode": "none",
        "label": "Ticker / ISIN",
        "product_scope_json": [],
        "sort_mode": "alpha",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.ticker_or_isin",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "category_code": "basics",
        "data_type": "string",
        "default_visible": False,
        "default_width": 220,
        "description": "Current manager / advisor firm.",
        "field_key": "management_firm_name",
        "filter_mode": "multi_select",
        "formatter_code": "text",
        "group_mode": "discrete",
        "label": "Management Firm",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "alpha",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.management_firm_name",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "category_code": "basics",
        "data_type": "string",
        "default_visible": True,
        "default_width": 240,
        "description": "Peer group/category used for ranking and comparison.",
        "field_key": "category_name",
        "filter_mode": "multi_select",
        "formatter_code": "text",
        "group_mode": "discrete",
        "label": "Category",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "alpha",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.category_name",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["instrument_detail"]},
        "category_code": "basics",
        "data_type": "string",
        "default_visible": False,
        "default_width": 160,
        "description": "Top-level instrument class for group by and filtering.",
        "field_key": "instrument_class",
        "filter_mode": "multi_select",
        "formatter_code": "text",
        "group_mode": "discrete",
        "label": "Instrument Class",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "alpha",
        "source_domain": "instrument_detail",
        "source_metric_code": "instrument_detail.metadata_json.instrument_class",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "category_code": "basics",
        "data_type": "number",
        "default_visible": True,
        "default_width": 140,
        "description": "Current assets under management from the watchlist row read model.",
        "field_key": "aum",
        "filter_mode": "range",
        "formatter_code": "currency_compact",
        "group_mode": "bucket",
        "label": "AUM",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.aum",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["instrument_chart_read_model"]},
        "category_code": "performance_risk",
        "data_type": "sparkline",
        "default_visible": False,
        "default_width": 140,
        "description": "1-month NAV spark chart from the current chart read model.",
        "field_key": "price_chart_1m",
        "filter_mode": "none",
        "formatter_code": "sparkline",
        "group_mode": "none",
        "label": "Price Chart",
        "product_scope_json": [],
        "sort_mode": "none",
        "source_domain": "read_model",
        "source_metric_code": "instrument_chart_read_model.series",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["instrument_score_snapshot"]},
        "category_code": "ratings_analysis",
        "data_type": "integer",
        "default_visible": True,
        "default_width": 140,
        "description": "Internal score-based rating derived from the current methodology.",
        "field_key": "overall_rating",
        "filter_mode": "multi_select",
        "formatter_code": "stars",
        "group_mode": "discrete",
        "label": "Overall Rating",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "score",
        "source_metric_code": "instrument_score_snapshot.overall_rating",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["instrument_score_snapshot"]},
        "category_code": "ratings_analysis",
        "data_type": "string",
        "default_visible": True,
        "default_width": 160,
        "description": "Current house view from the score snapshot.",
        "field_key": "analyst_stance",
        "filter_mode": "multi_select",
        "formatter_code": "badge",
        "group_mode": "discrete",
        "label": "Analyst Stance",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "alpha",
        "source_domain": "score",
        "source_metric_code": "instrument_score_snapshot.analyst_stance",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "category_code": "performance_risk",
        "data_type": "number",
        "default_visible": True,
        "default_width": 150,
        "description": "Derived from canonical NAV facts.",
        "field_key": "return_ytd",
        "filter_mode": "range",
        "formatter_code": "percent",
        "group_mode": "none",
        "label": "Total Return (YTD)",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_ytd",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "category_code": "performance_risk",
        "data_type": "number",
        "default_visible": True,
        "default_width": 150,
        "description": "1-week total return.",
        "field_key": "return_1w",
        "filter_mode": "range",
        "formatter_code": "percent",
        "group_mode": "none",
        "label": "Total Return (1W)",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1w",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "category_code": "performance_risk",
        "data_type": "number",
        "default_visible": True,
        "default_width": 150,
        "description": "1-year annualized total return.",
        "field_key": "return_1y",
        "filter_mode": "range",
        "formatter_code": "percent",
        "group_mode": "none",
        "label": "Total Return (1Y)",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1y",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "category_code": "performance_risk",
        "data_type": "number",
        "default_visible": True,
        "default_width": 150,
        "description": "3-year annualized total return.",
        "field_key": "return_3y",
        "filter_mode": "range",
        "formatter_code": "percent",
        "group_mode": "none",
        "label": "Total Return (3Y)",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_3y_annualized",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "category_code": "performance_risk",
        "data_type": "number",
        "default_visible": True,
        "default_width": 150,
        "description": "5-year annualized total return.",
        "field_key": "return_5y",
        "filter_mode": "range",
        "formatter_code": "percent",
        "group_mode": "none",
        "label": "Total Return (5Y)",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_5y_annualized",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "category_code": "performance_risk",
        "data_type": "number",
        "default_visible": False,
        "default_width": 150,
        "description": "Maximum drawdown from the active performance snapshot.",
        "field_key": "max_drawdown",
        "filter_mode": "range",
        "formatter_code": "percent",
        "group_mode": "none",
        "label": "Max Drawdown",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.max_drawdown",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "category_code": "performance_risk",
        "data_type": "number",
        "default_visible": False,
        "default_width": 140,
        "description": "Risk snapshot volatility for the selected window.",
        "field_key": "volatility",
        "filter_mode": "range",
        "formatter_code": "percent",
        "group_mode": "none",
        "label": "Volatility",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.volatility",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "category_code": "performance_risk",
        "data_type": "number",
        "default_visible": False,
        "default_width": 140,
        "description": "Current risk-adjusted return metric.",
        "field_key": "sharpe_ratio",
        "filter_mode": "range",
        "formatter_code": "decimal",
        "group_mode": "none",
        "label": "Sharpe Ratio",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.sharpe_ratio",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "category_code": "exposure",
        "data_type": "number",
        "default_visible": True,
        "default_width": 140,
        "description": "Weighted effective duration derived from exposure analytics.",
        "field_key": "duration",
        "filter_mode": "range",
        "formatter_code": "decimal",
        "group_mode": "bucket",
        "label": "Duration",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_duration",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "category_code": "exposure",
        "data_type": "string",
        "default_visible": True,
        "default_width": 150,
        "description": "Exposure-weighted average credit quality.",
        "field_key": "avg_credit_rating",
        "filter_mode": "multi_select",
        "formatter_code": "text",
        "group_mode": "discrete",
        "label": "Avg Credit Rating",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "alpha",
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.avg_credit_rating",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "category_code": "exposure",
        "data_type": "number",
        "default_visible": False,
        "default_width": 150,
        "description": "Exposure-weighted yield to worst derived from holdings analytics.",
        "field_key": "yield_to_worst",
        "filter_mode": "range",
        "formatter_code": "percent",
        "group_mode": "bucket",
        "label": "Yield To Worst",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "numeric",
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_yield_to_worst",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "category_code": "monitoring",
        "data_type": "date",
        "default_visible": False,
        "default_width": 150,
        "description": "Most recent canonical NAV fact adopted for the instrument.",
        "field_key": "last_nav_date",
        "filter_mode": "date_range",
        "formatter_code": "date",
        "group_mode": "bucket",
        "label": "Last NAV Date",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "date",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.last_nav_date",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "category_code": "monitoring",
        "data_type": "datetime",
        "default_visible": False,
        "default_width": 180,
        "description": "Latest holdings statement adoption time.",
        "field_key": "exposure_updated_at",
        "filter_mode": "date_range",
        "formatter_code": "datetime",
        "group_mode": "bucket",
        "label": "Holdings Updated At",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "date",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.exposure_updated_at",
    },
    {
        "instrument_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "category_code": "monitoring",
        "data_type": "string",
        "default_visible": True,
        "default_width": 140,
        "description": "System freshness status derived from the current read model.",
        "field_key": "data_freshness_status",
        "filter_mode": "multi_select",
        "formatter_code": "status",
        "group_mode": "discrete",
        "label": "Freshness",
        "product_scope_json": [],
        "sort_mode": "alpha",
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.data_freshness_status",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["instrument_attribute_value"]},
        "category_code": "custom_attributes",
        "data_type": "single_select",
        "default_visible": True,
        "default_width": 160,
        "description": "Research status such as invested, focus, or watch.",
        "field_key": "attr.coverage_status",
        "filter_mode": "multi_select",
        "formatter_code": "text",
        "group_mode": "discrete",
        "label": "Coverage Status",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "alpha",
        "source_domain": "custom_attribute",
        "source_metric_code": "instrument_attribute_value.coverage_status",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["instrument_attribute_value"]},
        "category_code": "custom_attributes",
        "data_type": "single_select",
        "default_visible": False,
        "default_width": 160,
        "description": "Internal attention bucket for near-term review priority.",
        "field_key": "attr.focus_bucket",
        "filter_mode": "multi_select",
        "formatter_code": "text",
        "group_mode": "discrete",
        "label": "Focus Bucket",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "alpha",
        "source_domain": "custom_attribute",
        "source_metric_code": "instrument_attribute_value.focus_bucket",
    },
    {
        "instrument_scope_json": ["fund"],
        "availability_rule_json": {"requires": ["instrument_attribute_value"]},
        "category_code": "custom_attributes",
        "data_type": "boolean",
        "default_visible": False,
        "default_width": 160,
        "description": "Whether the instrument is currently in the invested book.",
        "field_key": "attr.is_invested",
        "filter_mode": "multi_select",
        "formatter_code": "boolean",
        "group_mode": "discrete",
        "label": "Currently Invested",
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "sort_mode": "alpha",
        "source_domain": "custom_attribute",
        "source_metric_code": "instrument_attribute_value.is_invested",
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_detail',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('detail_view_type', sa.String(), nullable=False),
    sa.Column('instrument_name', sa.String(), nullable=False),
    sa.Column('primary_identifier_type', sa.String(), nullable=True),
    sa.Column('primary_identifier_value', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_detail'))
    )
    op.create_table('field_category',
    sa.Column('category_code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('parent_category_code', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_code'], ['field_category.category_code'], name=op.f('fk_field_category_parent_category_code_field_category')),
    sa.PrimaryKeyConstraint('category_code', name=op.f('pk_field_category'))
    )
    op.create_table('instrument_attribute_definition',
    sa.Column('attribute_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('is_groupable', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_view_column', sa.Boolean(), nullable=False),
    sa.Column('default_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('attribute_key', name=op.f('pk_instrument_attribute_definition'))
    )
    op.create_table('watchlist',
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('watchlist_id', name=op.f('pk_watchlist'))
    )
    op.create_table('instrument_chart_read_model',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('data_freshness_status', sa.String(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_chart_read_model_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_chart_read_model'))
    )
    op.create_table('instrument_exposure_holdings_read_model',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('data_freshness_status', sa.String(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_exposure_holdings_read_model_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_exposure_holdings_read_model'))
    )
    op.create_table('instrument_exposure_read_model',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('data_freshness_status', sa.String(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_exposure_read_model_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_exposure_read_model'))
    )
    op.create_table('instrument_manual_profile',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('people_payload_json', sa.JSON(), nullable=False),
    sa.Column('strategy_payload_json', sa.JSON(), nullable=False),
    sa.Column('price_payload_json', sa.JSON(), nullable=False),
    sa.Column('documents_payload_json', sa.JSON(), nullable=False),
    sa.Column('research_payload_json', sa.JSON(), nullable=False),
    sa.Column('nav_settings_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_manual_profile_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_manual_profile'))
    )
    op.create_table('instrument_performance_read_model',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('data_freshness_status', sa.String(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_performance_read_model_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_performance_read_model'))
    )
    op.create_table('instrument_rating_read_model',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('data_freshness_status', sa.String(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_rating_read_model_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_rating_read_model'))
    )
    op.create_table('instrument_risk_read_model',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('data_freshness_status', sa.String(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_risk_read_model_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_risk_read_model'))
    )
    op.create_table('instrument_score_snapshot',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('methodology_version', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('analyst_stance', sa.String(), nullable=True),
    sa.Column('people_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('process_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('exposure_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('price_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('operations_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fit_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_score_snapshot_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_instrument_score_snapshot'))
    )
    op.create_index('idx_score_snapshot_current', 'instrument_score_snapshot', ['instrument_id', 'is_current'], unique=False)
    op.create_table('instrument_summary_read_model',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('data_freshness_status', sa.String(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_summary_read_model_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument_summary_read_model'))
    )
    op.create_table('exposure_analytics_snapshot',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('methodology_version', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('asset_allocation_json', sa.JSON(), nullable=False),
    sa.Column('sector_allocation_json', sa.JSON(), nullable=False),
    sa.Column('country_allocation_json', sa.JSON(), nullable=False),
    sa.Column('currency_allocation_json', sa.JSON(), nullable=False),
    sa.Column('credit_rating_allocation_json', sa.JSON(), nullable=False),
    sa.Column('duration_bucket_json', sa.JSON(), nullable=False),
    sa.Column('maturity_bucket_json', sa.JSON(), nullable=False),
    sa.Column('yield_bucket_json', sa.JSON(), nullable=False),
    sa.Column('top10_concentration', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('holding_count', sa.Integer(), nullable=True),
    sa.Column('bond_count', sa.Integer(), nullable=True),
    sa.Column('equity_count', sa.Integer(), nullable=True),
    sa.Column('other_count', sa.Integer(), nullable=True),
    sa.Column('cash_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('leverage_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('weighted_duration', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('weighted_maturity', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('weighted_yield_to_worst', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('avg_credit_rating', sa.String(), nullable=True),
    sa.Column('reported_turnover', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('style_box_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_exposure_analytics_snapshot_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_exposure_analytics_snapshot'))
    )
    op.create_index('idx_exposure_snapshot_current', 'exposure_analytics_snapshot', ['instrument_id', 'is_current'], unique=False)
    op.create_table('field_registry',
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_code', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('formatter_code', sa.String(), nullable=False),
    sa.Column('sort_mode', sa.String(), nullable=False),
    sa.Column('filter_mode', sa.String(), nullable=False),
    sa.Column('group_mode', sa.String(), nullable=False),
    sa.Column('instrument_scope_json', sa.JSON(), nullable=False),
    sa.Column('product_scope_json', sa.JSON(), nullable=False),
    sa.Column('availability_rule_json', sa.JSON(), nullable=False),
    sa.Column('source_domain', sa.String(), nullable=False),
    sa.Column('source_metric_code', sa.String(), nullable=False),
    sa.Column('default_width', sa.Integer(), nullable=True),
    sa.Column('default_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['field_category.category_code'], name=op.f('fk_field_registry_category_code_field_category')),
    sa.PrimaryKeyConstraint('field_key', name=op.f('pk_field_registry'))
    )
    op.create_table('holding_snapshot',
    sa.Column('holding_snapshot_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('methodology_version', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_holding_snapshot_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holding_snapshot_id', name=op.f('pk_holding_snapshot'))
    )
    op.create_index('idx_holding_snapshot_current', 'holding_snapshot', ['instrument_id', 'is_current'], unique=False)
    op.create_table('instrument_attribute_value',
    sa.Column('instrument_attribute_value_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('attribute_key', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_instrument_attribute_value_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_key'], ['instrument_attribute_definition.attribute_key'], name=op.f('fk_instrument_attribute_value_attribute_key_instrument_attribute_definition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_attribute_value_id', name=op.f('pk_instrument_attribute_value'))
    )
    op.create_index('idx_instrument_attribute_value_instrument_attribute', 'instrument_attribute_value', ['instrument_id', 'attribute_key', 'adopted_at'], unique=False)
    op.create_table('nav_fact',
    sa.Column('nav_fact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('nav_type', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('observation_id', sa.String(), nullable=True),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_nav_fact_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nav_fact_id', name=op.f('pk_nav_fact')),
    sa.UniqueConstraint('instrument_id', 'as_of_date', 'nav_type', 'currency', name='uq_nav_fact_instrument_date_type_currency')
    )
    op.create_index('idx_nav_fact_instrument_date', 'nav_fact', ['instrument_id', 'as_of_date'], unique=False)
    op.create_table('performance_snapshot',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('methodology_version', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('return_ytd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_1w', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_1m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_3m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_6m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_1y', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_3y_annualized', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_5y_annualized', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_10y_annualized', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('calmar', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('annualized_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_performance_snapshot_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_performance_snapshot'))
    )
    op.create_index('idx_performance_snapshot_current', 'performance_snapshot', ['instrument_id', 'is_current'], unique=False)
    op.create_table('recalc_job',
    sa.Column('recalc_job_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('trigger_ref_type', sa.String(), nullable=True),
    sa.Column('trigger_ref_id', sa.String(), nullable=True),
    sa.Column('job_status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_recalc_job_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recalc_job_id', name=op.f('pk_recalc_job')),
    sa.UniqueConstraint('dedupe_key', name='uq_recalc_job_dedupe_key')
    )
    op.create_index('idx_recalc_job_status_priority', 'recalc_job', ['job_status', 'priority', 'enqueued_at'], unique=False)
    op.create_table('risk_snapshot',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('methodology_version', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('downside_volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('alpha', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('r_squared', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('up_capture', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('down_capture', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('tracking_error', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('information_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument_detail.instrument_id'], name=op.f('fk_risk_snapshot_instrument_id_instrument_detail'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_risk_snapshot'))
    )
    op.create_index('idx_risk_snapshot_current', 'risk_snapshot', ['instrument_id', 'is_current'], unique=False)
    op.create_table('watchlist_item',
    sa.Column('watchlist_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('rank_hint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.watchlist_id'], name=op.f('fk_watchlist_item_watchlist_id_watchlist'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_item_id', name=op.f('pk_watchlist_item')),
    sa.UniqueConstraint('watchlist_id', 'instrument_id', name='uq_watchlist_item_watchlist_asset')
    )
    op.create_index('idx_watchlist_item_watchlist_id', 'watchlist_item', ['watchlist_id'], unique=False)
    op.create_table('watchlist_row_read_model',
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('instrument_name', sa.String(), nullable=False),
    sa.Column('share_class', sa.String(), nullable=True),
    sa.Column('ticker_or_isin', sa.String(), nullable=True),
    sa.Column('management_firm_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('analyst_stance', sa.String(), nullable=True),
    sa.Column('aum', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('return_ytd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_1w', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_1y', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_3y', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_5y', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('duration', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('yield_to_worst', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('avg_credit_rating', sa.String(), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('exposure_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_nav_date', sa.Date(), nullable=True),
    sa.Column('data_freshness_status', sa.String(), nullable=False),
    sa.Column('last_fact_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('staleness_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.watchlist_id'], name=op.f('fk_watchlist_row_read_model_watchlist_id_watchlist'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'instrument_id', name=op.f('pk_watchlist_row_read_model'))
    )
    op.create_table('watchlist_view',
    sa.Column('watchlist_view_id', sa.String(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('default_sort_json', sa.JSON(), nullable=False),
    sa.Column('default_filters_json', sa.JSON(), nullable=False),
    sa.Column('default_advanced_filter_json', sa.JSON(), nullable=False),
    sa.Column('default_group_by', sa.String(), nullable=True),
    sa.Column('density', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.watchlist_id'], name=op.f('fk_watchlist_view_watchlist_id_watchlist'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_view_id', name=op.f('pk_watchlist_view'))
    )
    op.create_table('holding_position',
    sa.Column('holding_position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('holding_snapshot_id', sa.String(), nullable=False),
    sa.Column('holding_name', sa.String(), nullable=False),
    sa.Column('holding_type', sa.String(), nullable=False),
    sa.Column('security_identifier', sa.String(), nullable=True),
    sa.Column('issuer_name', sa.String(), nullable=True),
    sa.Column('issuer_type', sa.String(), nullable=True),
    sa.Column('portfolio_weight', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('share_change_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('coupon_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('credit_rating', sa.String(), nullable=True),
    sa.Column('effective_duration', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('modified_duration', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('yield_to_worst', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['holding_snapshot_id'], ['holding_snapshot.holding_snapshot_id'], name=op.f('fk_holding_position_holding_snapshot_id_holding_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holding_position_id', name=op.f('pk_holding_position'))
    )
    op.create_table('watchlist_view_column',
    sa.Column('watchlist_view_column_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_view_id', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('pin_side', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_view_id'], ['watchlist_view.watchlist_view_id'], name=op.f('fk_watchlist_view_column_watchlist_view_id_watchlist_view'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_view_column_id', name=op.f('pk_watchlist_view_column')),
    sa.UniqueConstraint('watchlist_view_id', 'field_key', name='uq_watchlist_view_column_view_field')
    )
    field_category_table = sa.table(
        "field_category",
        sa.column("category_code", sa.String()),
        sa.column("label", sa.String()),
        sa.column("parent_category_code", sa.String()),
        sa.column("display_order", sa.Integer()),
    )
    instrument_attribute_definition_table = sa.table(
        "instrument_attribute_definition",
        sa.column("attribute_key", sa.String()),
        sa.column("label", sa.String()),
        sa.column("description", sa.String()),
        sa.column("data_type", sa.String()),
        sa.column("options_json", sa.JSON()),
        sa.column("is_groupable", sa.Boolean()),
        sa.column("is_filterable", sa.Boolean()),
        sa.column("is_view_column", sa.Boolean()),
        sa.column("default_visible", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    field_registry_table = sa.table(
        "field_registry",
        sa.column("field_key", sa.String()),
        sa.column("label", sa.String()),
        sa.column("description", sa.String()),
        sa.column("category_code", sa.String()),
        sa.column("data_type", sa.String()),
        sa.column("formatter_code", sa.String()),
        sa.column("sort_mode", sa.String()),
        sa.column("filter_mode", sa.String()),
        sa.column("group_mode", sa.String()),
        sa.column("instrument_scope_json", sa.JSON()),
        sa.column("product_scope_json", sa.JSON()),
        sa.column("availability_rule_json", sa.JSON()),
        sa.column("source_domain", sa.String()),
        sa.column("source_metric_code", sa.String()),
        sa.column("default_width", sa.Integer()),
        sa.column("default_visible", sa.Boolean()),
    )
    op.bulk_insert(field_category_table, FIELD_CATEGORIES_SNAPSHOT)
    op.bulk_insert(
        instrument_attribute_definition_table,
        [
            {
                "attribute_key": str(item["attribute_key"]),
                "label": str(item["label"]),
                "description": (
                    str(item["description"])
                    if item.get("description") is not None
                    else None
                ),
                "data_type": str(item["data_type"]),
                "options_json": list(item.get("options", [])),
                "is_groupable": bool(item.get("is_groupable", True)),
                "is_filterable": bool(item.get("is_filterable", True)),
                "is_view_column": bool(item.get("is_view_column", True)),
                "default_visible": bool(item.get("default_visible", False)),
                "created_at": REFERENCE_CREATED_AT,
            }
            for item in INSTRUMENT_ATTRIBUTE_DEFINITIONS_SNAPSHOT
        ],
    )
    op.bulk_insert(
        field_registry_table,
        [
            {
                "field_key": str(item["field_key"]),
                "label": str(item["label"]),
                "description": (
                    str(item["description"])
                    if item.get("description") is not None
                    else None
                ),
                "category_code": str(item["category_code"]),
                "data_type": str(item["data_type"]),
                "formatter_code": str(item["formatter_code"]),
                "sort_mode": str(item["sort_mode"]),
                "filter_mode": str(item["filter_mode"]),
                "group_mode": str(item["group_mode"]),
                "instrument_scope_json": list(item.get("instrument_scope_json", [])),
                "product_scope_json": list(item.get("product_scope_json", [])),
                "availability_rule_json": dict(item.get("availability_rule_json", {})),
                "source_domain": str(item["source_domain"]),
                "source_metric_code": str(item["source_metric_code"]),
                "default_width": item.get("default_width"),
                "default_visible": bool(item.get("default_visible", True)),
            }
            for item in FIELD_REGISTRY_SNAPSHOT
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_view_column')
    op.drop_table('holding_position')
    op.drop_table('watchlist_view')
    op.drop_table('watchlist_row_read_model')
    op.drop_index('idx_watchlist_item_watchlist_id', table_name='watchlist_item')
    op.drop_table('watchlist_item')
    op.drop_index('idx_risk_snapshot_current', table_name='risk_snapshot')
    op.drop_table('risk_snapshot')
    op.drop_index('idx_recalc_job_status_priority', table_name='recalc_job')
    op.drop_table('recalc_job')
    op.drop_index('idx_performance_snapshot_current', table_name='performance_snapshot')
    op.drop_table('performance_snapshot')
    op.drop_index('idx_nav_fact_instrument_date', table_name='nav_fact')
    op.drop_table('nav_fact')
    op.drop_index('idx_instrument_attribute_value_instrument_attribute', table_name='instrument_attribute_value')
    op.drop_table('instrument_attribute_value')
    op.drop_index('idx_holding_snapshot_current', table_name='holding_snapshot')
    op.drop_table('holding_snapshot')
    op.drop_table('field_registry')
    op.drop_index('idx_exposure_snapshot_current', table_name='exposure_analytics_snapshot')
    op.drop_table('exposure_analytics_snapshot')
    op.drop_table('instrument_summary_read_model')
    op.drop_index('idx_score_snapshot_current', table_name='instrument_score_snapshot')
    op.drop_table('instrument_score_snapshot')
    op.drop_table('instrument_risk_read_model')
    op.drop_table('instrument_rating_read_model')
    op.drop_table('instrument_performance_read_model')
    op.drop_table('instrument_manual_profile')
    op.drop_table('instrument_exposure_read_model')
    op.drop_table('instrument_exposure_holdings_read_model')
    op.drop_table('instrument_chart_read_model')
    op.drop_table('watchlist')
    op.drop_table('instrument_attribute_definition')
    op.drop_table('field_category')
    op.drop_table('instrument_detail')
    # ### end Alembic commands ###
