from __future__ import annotations

from typing import Any

TEST_PORTFOLIO_STORE: dict[str, list[dict[str, Any]]] = {
    "portfolios": [
        {
            "portfolio_id": "yungu",
            "portfolio_name": "yungu",
            "base_currency": "USD",
            "valuation_timezone": "Asia/Shanghai",
            "valuation_cutoff_policy": "latest_complete_eod",
            "as_of_date": "2026-04-15",
            "nav": 216470.0,
            "day_change_value": -1470.0,
            "day_change_pct": -0.0067,
            "securities_count": 3,
            "sort_order": 0,
        }
    ],
    "accounts": [
        {
            "account_id": "cash-usd-main",
            "portfolio_id": "yungu",
            "account_name": "Main USD Cash",
            "account_type": "deposit_account",
            "currency": "USD",
            "institution": "Citi Private Bank",
            "default_settlement_cash_account_id": None,
            "cost_basis_method": None,
            "allowed_instrument_types": None,
            "opened_at": "2026-01-02",
            "status": "active",
        },
        {
            "account_id": "cash-usd-reserve",
            "portfolio_id": "yungu",
            "account_name": "Reserve USD Cash",
            "account_type": "deposit_account",
            "currency": "USD",
            "institution": "Northern Trust",
            "default_settlement_cash_account_id": None,
            "cost_basis_method": None,
            "allowed_instrument_types": None,
            "opened_at": "2026-01-15",
            "status": "active",
        },
        {
            "account_id": "broker-us-core",
            "portfolio_id": "yungu",
            "account_name": "IBKR Core Brokerage",
            "account_type": "securities_account",
            "currency": "USD",
            "institution": "Interactive Brokers",
            "default_settlement_cash_account_id": "cash-usd-main",
            "cost_basis_method": "fifo",
            "allowed_instrument_types": ["equity", "fund"],
            "opened_at": "2026-01-02",
            "status": "active",
        },
        {
            "account_id": "broker-us-income",
            "portfolio_id": "yungu",
            "account_name": "IBKR Income Sleeve",
            "account_type": "securities_account",
            "currency": "USD",
            "institution": "Interactive Brokers",
            "default_settlement_cash_account_id": "cash-usd-reserve",
            "cost_basis_method": "fifo",
            "allowed_instrument_types": ["bond", "fund"],
            "opened_at": "2026-01-15",
            "status": "active",
        },
        {
            "account_id": "cash-hkd-main",
            "portfolio_id": "yungu",
            "account_name": "Main HKD Cash",
            "account_type": "deposit_account",
            "currency": "HKD",
            "institution": "HSBC Private Bank",
            "default_settlement_cash_account_id": None,
            "cost_basis_method": None,
            "allowed_instrument_types": None,
            "opened_at": "2026-02-20",
            "status": "active",
        },
        {
            "account_id": "cash-cny-main",
            "portfolio_id": "yungu",
            "account_name": "Main CNY Cash",
            "account_type": "deposit_account",
            "currency": "CNY",
            "institution": "Bank of China",
            "default_settlement_cash_account_id": None,
            "cost_basis_method": None,
            "allowed_instrument_types": None,
            "opened_at": "2026-03-30",
            "status": "active",
        },
        {
            "account_id": "broker-hk-core",
            "portfolio_id": "yungu",
            "account_name": "IBKR Hong Kong",
            "account_type": "securities_account",
            "currency": "HKD",
            "institution": "Interactive Brokers Hong Kong",
            "default_settlement_cash_account_id": "cash-hkd-main",
            "cost_basis_method": "fifo",
            "allowed_instrument_types": ["equity", "fund"],
            "opened_at": "2026-02-20",
            "status": "active",
        },
    ],
    "transactions": [
        {
            "transaction_id": "txn-0001",
            "portfolio_id": "yungu",
            "transaction_type": "opening_balance",
            "trade_date": "2026-01-02",
            "settlement_date": "2026-01-02",
            "account_id": "cash-usd-main",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 125000.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Imported opening cash balance.",
            "created_at": "2026-01-02T08:00:00Z",
        },
        {
            "transaction_id": "txn-0002",
            "portfolio_id": "yungu",
            "transaction_type": "deposit",
            "trade_date": "2026-02-03",
            "settlement_date": "2026-02-03",
            "account_id": "cash-usd-main",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 50000.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Capital contribution.",
            "created_at": "2026-02-03T10:15:00Z",
        },
        {
            "transaction_id": "txn-0003",
            "portfolio_id": "yungu",
            "transaction_type": "buy",
            "trade_date": "2026-02-10",
            "settlement_date": "2026-02-12",
            "account_id": "broker-us-core",
            "settlement_cash_account_id": "cash-usd-main",
            "instrument_id": "equity-us-abbv",
            "instrument_ref": {
                "instrument_id": "equity-us-abbv",
                "instrument_name": "AbbVie Inc",
                "instrument_type": "equity",
                "currency": "USD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "ABBV",
                        "is_primary": True,
                    },
                    {
                        "identifier_type": "isin",
                        "identifier_value": "US00287Y1091",
                        "is_primary": False,
                    },
                ],
            },
            "quantity": 1000.0,
            "price": 206.47,
            "gross_amount": 206470.0,
            "fees": 18.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Core defensive healthcare add.",
            "created_at": "2026-02-10T09:30:00Z",
        },
        {
            "transaction_id": "txn-0004",
            "portfolio_id": "yungu",
            "transaction_type": "buy",
            "trade_date": "2026-03-05",
            "settlement_date": "2026-03-07",
            "account_id": "broker-us-core",
            "settlement_cash_account_id": "cash-usd-main",
            "instrument_id": "fund-us-agg",
            "instrument_ref": {
                "instrument_id": "fund-us-agg",
                "instrument_name": "iShares Core U.S. Aggregate Bond ETF",
                "instrument_type": "fund",
                "currency": "USD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "AGG",
                        "is_primary": True,
                    }
                ],
            },
            "quantity": 300.0,
            "price": 96.82,
            "gross_amount": 29046.0,
            "fees": 6.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Duration ballast sleeve.",
            "created_at": "2026-03-05T11:20:00Z",
        },
        {
            "transaction_id": "txn-0005",
            "portfolio_id": "yungu",
            "transaction_type": "dividend",
            "trade_date": "2026-03-15",
            "settlement_date": "2026-03-15",
            "account_id": "broker-us-core",
            "settlement_cash_account_id": "cash-usd-main",
            "instrument_id": "equity-us-abbv",
            "instrument_ref": {
                "instrument_id": "equity-us-abbv",
                "instrument_name": "AbbVie Inc",
                "instrument_type": "equity",
                "currency": "USD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "ABBV",
                        "is_primary": True,
                    },
                    {
                        "identifier_type": "isin",
                        "identifier_value": "US00287Y1091",
                        "is_primary": False,
                    },
                ],
            },
            "quantity": None,
            "price": None,
            "gross_amount": 1640.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Quarterly dividend received.",
            "created_at": "2026-03-15T18:00:00Z",
        },
        {
            "transaction_id": "txn-0006",
            "portfolio_id": "yungu",
            "transaction_type": "dividend_reinvestment",
            "trade_date": "2026-03-28",
            "settlement_date": "2026-03-28",
            "account_id": "broker-us-core",
            "settlement_cash_account_id": None,
            "instrument_id": "fund-us-agg",
            "instrument_ref": {
                "instrument_id": "fund-us-agg",
                "instrument_name": "iShares Core U.S. Aggregate Bond ETF",
                "instrument_type": "fund",
                "currency": "USD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "AGG",
                        "is_primary": True,
                    }
                ],
            },
            "quantity": 4.236,
            "price": 96.79,
            "gross_amount": 410.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Fund distribution reinvested.",
            "created_at": "2026-03-28T17:45:00Z",
        },
        {
            "transaction_id": "txn-0007",
            "portfolio_id": "yungu",
            "transaction_type": "sell",
            "trade_date": "2026-04-08",
            "settlement_date": "2026-04-10",
            "account_id": "broker-us-core",
            "settlement_cash_account_id": "cash-usd-main",
            "instrument_id": "equity-us-abbv",
            "instrument_ref": {
                "instrument_id": "equity-us-abbv",
                "instrument_name": "AbbVie Inc",
                "instrument_type": "equity",
                "currency": "USD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "ABBV",
                        "is_primary": True,
                    },
                    {
                        "identifier_type": "isin",
                        "identifier_value": "US00287Y1091",
                        "is_primary": False,
                    },
                ],
            },
            "quantity": 120.0,
            "price": 207.18,
            "gross_amount": 24861.6,
            "fees": 9.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Trim after rally.",
            "created_at": "2026-04-08T14:05:00Z",
        },
        {
            "transaction_id": "txn-0008",
            "portfolio_id": "yungu",
            "transaction_type": "fee",
            "trade_date": "2026-04-09",
            "settlement_date": "2026-04-09",
            "account_id": "cash-usd-main",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 125.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Monthly custody fee.",
            "created_at": "2026-04-09T09:10:00Z",
        },
        {
            "transaction_id": "txn-0009",
            "portfolio_id": "yungu",
            "transaction_type": "withdrawal",
            "trade_date": "2026-04-11",
            "settlement_date": "2026-04-11",
            "account_id": "cash-usd-main",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 12000.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Distribution to LP.",
            "created_at": "2026-04-11T16:40:00Z",
        },
        {
            "transaction_id": "txn-0010",
            "portfolio_id": "yungu",
            "transaction_type": "transfer_out",
            "trade_date": "2026-04-12",
            "settlement_date": "2026-04-12",
            "account_id": "cash-usd-main",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 15000.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": "internal_portfolio",
            "transfer_object_type": "cash",
            "transfer_group_id": "trf-20260412-cash-01",
            "counterparty_account_id": "cash-usd-reserve",
            "note": "Move operating cash to reserve account.",
            "created_at": "2026-04-12T09:05:00Z",
        },
        {
            "transaction_id": "txn-0011",
            "portfolio_id": "yungu",
            "transaction_type": "transfer_in",
            "trade_date": "2026-04-12",
            "settlement_date": "2026-04-12",
            "account_id": "cash-usd-reserve",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 15000.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": "internal_portfolio",
            "transfer_object_type": "cash",
            "transfer_group_id": "trf-20260412-cash-01",
            "counterparty_account_id": "cash-usd-main",
            "note": "Move operating cash to reserve account.",
            "created_at": "2026-04-12T09:05:10Z",
        },
        {
            "transaction_id": "txn-0012",
            "portfolio_id": "yungu",
            "transaction_type": "transfer_out",
            "trade_date": "2026-04-13",
            "settlement_date": "2026-04-13",
            "account_id": "broker-us-core",
            "settlement_cash_account_id": None,
            "instrument_id": "fund-us-agg",
            "instrument_ref": {
                "instrument_id": "fund-us-agg",
                "instrument_name": "iShares Core U.S. Aggregate Bond ETF",
                "instrument_type": "fund",
                "currency": "USD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "AGG",
                        "is_primary": True,
                    }
                ],
            },
            "quantity": 50.0,
            "price": None,
            "gross_amount": 4842.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": "internal_portfolio",
            "transfer_object_type": "position",
            "transfer_group_id": "trf-20260413-pos-01",
            "counterparty_account_id": "broker-us-income",
            "note": "Move duration sleeve to income brokerage.",
            "created_at": "2026-04-13T10:25:00Z",
        },
        {
            "transaction_id": "txn-0013",
            "portfolio_id": "yungu",
            "transaction_type": "transfer_in",
            "trade_date": "2026-04-13",
            "settlement_date": "2026-04-13",
            "account_id": "broker-us-income",
            "settlement_cash_account_id": None,
            "instrument_id": "fund-us-agg",
            "instrument_ref": {
                "instrument_id": "fund-us-agg",
                "instrument_name": "iShares Core U.S. Aggregate Bond ETF",
                "instrument_type": "fund",
                "currency": "USD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "AGG",
                        "is_primary": True,
                    }
                ],
            },
            "quantity": 50.0,
            "price": None,
            "gross_amount": 4842.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": "internal_portfolio",
            "transfer_object_type": "position",
            "transfer_group_id": "trf-20260413-pos-01",
            "counterparty_account_id": "broker-us-core",
            "note": "Move duration sleeve to income brokerage.",
            "created_at": "2026-04-13T10:25:10Z",
        },
        {
            "transaction_id": "txn-0014",
            "portfolio_id": "yungu",
            "transaction_type": "sell",
            "trade_date": "2026-04-14",
            "settlement_date": "2026-04-14",
            "account_id": "broker-us-income",
            "settlement_cash_account_id": "cash-usd-reserve",
            "instrument_id": "fund-us-agg",
            "instrument_ref": {
                "instrument_id": "fund-us-agg",
                "instrument_name": "iShares Core U.S. Aggregate Bond ETF",
                "instrument_type": "fund",
                "currency": "USD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "AGG",
                        "is_primary": True,
                    }
                ],
            },
            "quantity": 20.0,
            "price": 96.97,
            "gross_amount": 1939.4,
            "fees": 4.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Trim transferred bond sleeve under FIFO.",
            "created_at": "2026-04-14T09:40:00Z",
        },
        {
            "transaction_id": "txn-0015",
            "portfolio_id": "yungu",
            "transaction_type": "interest",
            "trade_date": "2026-04-15",
            "settlement_date": "2026-04-15",
            "account_id": "cash-usd-reserve",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 82.4,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Monthly sweep interest credited.",
            "created_at": "2026-04-15T08:10:00Z",
        },
        {
            "transaction_id": "txn-0016",
            "portfolio_id": "yungu",
            "transaction_type": "opening_balance",
            "trade_date": "2026-02-20",
            "settlement_date": "2026-02-20",
            "account_id": "cash-hkd-main",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 120000.0,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "HKD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Initial HKD funding for Asia sleeve.",
            "created_at": "2026-02-20T08:00:00Z",
        },
        {
            "transaction_id": "txn-0017",
            "portfolio_id": "yungu",
            "transaction_type": "buy",
            "trade_date": "2026-03-04",
            "settlement_date": "2026-03-06",
            "account_id": "broker-hk-core",
            "settlement_cash_account_id": "cash-hkd-main",
            "instrument_id": "fund-hk-2800",
            "instrument_ref": {
                "instrument_id": "fund-hk-2800",
                "instrument_name": "Tracker Fund of Hong Kong",
                "instrument_type": "fund",
                "currency": "HKD",
                "identifiers": [
                    {
                        "identifier_type": "ticker",
                        "identifier_value": "2800.HK",
                        "is_primary": True,
                    }
                ],
            },
            "quantity": 5000.0,
            "price": 22.35,
            "gross_amount": 111750.0,
            "fees": 90.0,
            "taxes": 0.0,
            "currency": "HKD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": None,
            "note": "Establish Hong Kong equity sleeve with HKD settlement.",
            "created_at": "2026-03-04T10:05:00Z",
        },
        {
            "transaction_id": "txn-0018",
            "portfolio_id": "yungu",
            "transaction_type": "fx_conversion",
            "trade_date": "2026-04-02",
            "settlement_date": "2026-04-02",
            "account_id": "cash-usd-main",
            "settlement_cash_account_id": None,
            "instrument_id": None,
            "instrument_ref": None,
            "quantity": None,
            "price": None,
            "gross_amount": 25000.0,
            "counter_amount": 182250.0,
            "fx_rate": 7.29,
            "fees": 0.0,
            "taxes": 0.0,
            "currency": "USD",
            "transfer_scope": None,
            "transfer_object_type": None,
            "transfer_group_id": None,
            "counterparty_account_id": "cash-cny-main",
            "note": "Convert USD liquidity into onshore CNY cash.",
            "created_at": "2026-04-02T11:15:00Z",
        },
    ],
}
