from __future__ import annotations

from copy import deepcopy


FIELD_CATEGORIES = [
    {"category_code": "general", "label": "General", "display_order": 1},
    {"category_code": "basics", "label": "Basics", "display_order": 2},
    {
        "category_code": "instrument_taxonomy",
        "label": "Instrument Taxonomy",
        "display_order": 3,
    },
    {
        "category_code": "research_framework",
        "label": "Investment Research",
        "display_order": 4,
    },
    {
        "category_code": "monitoring_assessment",
        "label": "Monitoring Assessment",
        "display_order": 5,
    },
    {"category_code": "fees_terms", "label": "Fees & Terms", "display_order": 6},
    {
        "category_code": "performance_risk",
        "label": "Performance & Risk",
        "display_order": 7,
    },
    {"category_code": "exposure", "label": "Exposure", "display_order": 8},
    {"category_code": "monitoring", "label": "Monitoring", "display_order": 9},
]

INSTRUMENT_ATTRIBUTE_DEFINITIONS = [
    {
        "attribute_key": "fund_vehicle",
        "label": "产品形态",
        "description": "场外开放式、LOF、私募契约型等基金载体形态，属于基本情况而非策略分类。",
        "data_type": "single_select",
        "options": [
            "LOF/场内开放式",
            "场外开放式",
            "封闭式",
            "集合资管计划",
            "契约型私募基金",
            "公司型私募基金",
            "其他",
        ],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "overview",
        "group_code": "overview_identity",
        "display_order": 20,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述基金法律/交易载体，不等于分类树。",
            "standard": "按当前主载体单选；不要把策略判断写进载体字段。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "primary_geographic_exposure",
        "label": "主要地域敞口",
        "description": "底层资产的主要地域，而不是产品注册地、交易所或上市地点；用于跨市场筛选和同类比较。",
        "data_type": "single_select",
        "options": [
            "中国 A 股",
            "中国内地",
            "香港",
            "大中华区",
            "美国",
            "全球",
            "发达市场（美国除外）",
            "新兴市场",
            "欧洲",
            "日本",
            "亚太（日本除外）",
            "其他 / 多地域",
            "全球 / 非地域型",
        ],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "overview",
        "group_code": "overview_exposure",
        "display_order": 25,
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "index"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "把投资敞口与上市市场、注册地和 QDII 等包装形式分开。",
            "standard": "按长期主要风险敞口单选；全球宏观、商品和真正跨地域组合使用全球 / 非地域型或其他 / 多地域。",
            "evidence": ["mandate", "benchmark", "holdings", "country_allocation"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "coverage_status",
        "label": "Investment Status",
        "description": "Investment/watchlist lifecycle status such as watch, proposed, invested, paused, or exited. This is not Research View.",
        "data_type": "single_select",
        "options": ["Watch", "Proposed", "Invested", "Paused", "Exited"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": True,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 110,
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述投资生命周期状态，而不是定性研究结论。",
            "standard": "只保留一个当前有效状态；Research View 和人工 rating 在 research payload 中维护。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "thesis_status",
        "label": "Investment Thesis Status",
        "description": "Current state of the investable thesis, separate from watchlist lifecycle and position status.",
        "data_type": "single_select",
        "options": ["Developing", "Active", "Under Review", "Broken", "Closed"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 115,
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "记录投资论点本身处于建立、有效、复核、失效还是结束状态。",
            "standard": "Under Review 必须有明确待核查证据；Broken 表示核心前提已经被证伪；Closed 表示研究周期已经结束。",
            "evidence": ["investment_view", "research_notes", "decision_record"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "focus_bucket",
        "label": "Research Priority",
        "description": "Internal attention bucket for near-term research and review priority.",
        "data_type": "single_select",
        "options": ["Tier 1", "Tier 2", "Tier 3"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 120,
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "用于排研究资源优先级，不代表标的好坏或是否持仓。",
            "standard": "Tier 1 代表近期最需要研究/复核；Tier 3 代表低频观察。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "research_evidence_level",
        "label": "证据充分度",
        "description": "当前定性结论背后的证据完整程度。",
        "data_type": "single_select",
        "options": ["完整证据", "部分证据", "轶事证据", "待验证"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 125,
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "衡量标签、rating 和 Research View 是否有足够材料支撑。",
            "standard": "完整证据需要覆盖与资产类型相匹配的一手材料、量化或估值验证、关键反证与失效条件；轶事证据不能支撑高 conviction。",
            "evidence": ["primary_sources", "research_notes", "quantitative_or_valuation_work", "invalidation_evidence"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "investment_edge_quality",
        "label": "投资优势质量",
        "description": "收益来源是否清晰、可解释、可持续。",
        "data_type": "single_select",
        "options": ["清晰且可持续", "清晰但需验证", "主要是市场贝塔", "边际优势不清"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_edge",
        "display_order": 128,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "回答“这只产品是否有真正的、可持续的 edge”。",
            "standard": "必须能通过流程、团队、数据、市场结构或历史归因解释；不要把短期排名当作 edge。",
            "evidence": ["performance_attribution", "portfolio_history", "manager_interview", "process_materials"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "implementation_style",
        "label": "实现方式",
        "description": "投资决策和执行主要由主观判断、量化模型还是规则复制驱动。",
        "data_type": "single_select",
        "options": ["主观", "量化", "主观+量化", "被动规则"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 130,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述收益生成方式，不等于分类树层级。",
            "standard": "按当前主实现方式单选；混合策略可选主观+量化。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "process_repeatability",
        "label": "流程可复制性",
        "description": "研究、决策、交易和复盘流程是否能稳定重复。",
        "data_type": "single_select",
        "options": ["可重复", "部分可重复", "关键人驱动", "不透明"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 135,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "顶层管理人尽调维度，区分流程型能力和个人英雄式能力。",
            "standard": "可重复必须有清晰职责、研究/交易记录、组合结果解释和复盘机制；关键人驱动需要同步标记 key-person risk。",
            "evidence": ["investment_process", "decision_records", "portfolio_explainability", "team_interview"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "decision_discipline",
        "label": "决策纪律",
        "description": "投资决策是否依赖可验证证据、规则和复盘。",
        "data_type": "single_select",
        "options": ["证据驱动", "经验驱动", "机会型", "不清晰"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 138,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "判断投资行为是否有一致的决策和复盘纪律。",
            "standard": "证据驱动需要能看到投资备忘录、风控约束、交易理由或系统化规则；机会型表示仓位/交易较依赖短期判断。",
            "evidence": ["investment_memo", "risk_limits", "trade_rationale", "post_mortem"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "trading_universe",
        "label": "交易市场/品种",
        "description": "主要交易的底层市场与工具，可多选。",
        "data_type": "multi_select",
        "options": [
            "A股",
            "港股",
            "美股",
            "债券",
            "可转债",
            "股指期货",
            "国债期货",
            "商品期货",
            "期权",
            "海外市场",
        ],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 140,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述基金真实操作的底层市场，不是销售口径。",
            "standard": "保留 1-3 个核心市场/工具即可。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "alpha_source",
        "label": "主要收益来源",
        "description": "基金最核心的收益引擎，可多选。",
        "data_type": "multi_select",
        "options": [
            "选股Alpha",
            "指数复制",
            "贝塔增强",
            "趋势跟踪",
            "期限结构",
            "价差收敛",
            "波动率交易",
            "事件驱动",
            "宏观择时",
            "Carry/票息",
            "主题/风格暴露",
            "高频/微观结构",
        ],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_edge",
        "display_order": 150,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "回答“这只产品靠什么赚钱”。",
            "standard": "只保留真正长期贡献超额的 1-3 个来源。",
            "evidence": ["performance_attribution", "portfolio_history", "manager_interview"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "style_profile",
        "label": "风格画像",
        "description": "面向 FOF 定性研究的标准化风格标签，可多选。",
        "data_type": "multi_select",
        "options": [
            "深度价值",
            "均衡成长",
            "GARP",
            "行业轮动",
            "短线交易",
            "高换手",
            "集中持仓",
            "分散持仓",
            "多因子",
            "高频",
            "中频",
            "低频",
            "指数增强",
            "信用下沉",
            "久期交易",
            "趋势跟踪",
        ],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_style",
        "display_order": 160,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "把 FOF 研究里的风格判断标准化，便于横向比较。",
            "standard": "标签必须能被历史组合、访谈或披露材料反复验证。",
            "evidence": ["portfolio_history", "factor_exposure", "turnover", "manager_interview"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "manager_assessment",
        "label": "管理人评价",
        "description": "管理人与团队层面的定性判断，可多选。",
        "data_type": "multi_select",
        "options": [
            "资深核心PM",
            "机构化团队",
            "关键人风险",
            "团队纵深不足",
            "近期人员变动",
            "传承风险",
        ],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_manager",
        "display_order": 170,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "只记录已经形成共识的团队和组织判断，不写临时印象。",
            "standard": "每个标签都应能对应明确证据，如履历、团队职责、人员变动、访谈纪要或组织激励。",
            "evidence": ["team_roster", "ownership_incentives", "manager_interview", "org_change_log"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "team_stability_assessment",
        "label": "团队稳定性",
        "description": "对核心投研团队是否稳定的研究判断。",
        "data_type": "single_select",
        "options": ["稳定", "正常流动", "近期流失", "关键人依赖", "不清楚"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_manager",
        "display_order": 180,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "区分团队是否具备稳定持续输出能力。",
            "standard": "结合核心人员流动、职责清晰度和投研流程延续性判断。",
            "evidence": ["team_roster", "personnel_changes", "role_map", "manager_interview"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "portfolio_construction",
        "label": "组合构建方式",
        "description": "组合如何落地到仓位、约束与换手，可多选。",
        "data_type": "multi_select",
        "options": ["集中持仓", "分散持仓", "行业集中", "风格均衡", "严格基准约束", "低跟踪误差", "容量敏感", "高换手"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_style",
        "display_order": 190,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述组合工程特征，帮助解释收益与回撤形态。",
            "standard": "仅选择长期、可观测、会影响持有人体验的构建特征。",
            "evidence": ["holdings", "turnover", "risk_contribution", "benchmark_constraints"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "style_drift_risk",
        "label": "风格漂移风险",
        "description": "策略暴露和执行风格偏离原研究假设的风险。",
        "data_type": "single_select",
        "options": ["低", "中", "高", "不清楚"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_style",
        "display_order": 195,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "监控原始研究假设是否仍然成立。",
            "standard": "低表示历史暴露和沟通口径长期一致；高表示策略、仓位或风格频繁偏离原假设。",
            "evidence": ["holdings", "factor_exposure", "turnover", "manager_communication"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "risk_management_quality",
        "label": "风险管理质量",
        "description": "风险预算、约束、压力期应对和复盘是否有效。",
        "data_type": "single_select",
        "options": ["强", "合格", "被动", "弱", "不清楚"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_risk",
        "display_order": 198,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "判断风险是否被主动预算、约束和复盘。",
            "standard": "强需要能看到风险预算、止损/减仓机制、压力测试和一致执行；弱表示风险暴露与策略承诺不匹配。",
            "evidence": ["risk_limits", "drawdown_review", "stress_test", "risk_reports"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "capacity_bucket",
        "label": "容量判断",
        "description": "产品容量与规模约束的研究结论。",
        "data_type": "single_select",
        "options": ["可扩容", "有容量约束", "接近容量", "规模过大", "不清楚"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_terms",
        "display_order": 200,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "用于识别规模扩张是否会侵蚀策略有效性。",
            "standard": "结合市场容量、换手、底层工具流动性和历史规模变化判断。",
            "evidence": ["aum_history", "turnover", "market_liquidity", "slippage", "capacity_guidance"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "liquidity_terms_fit",
        "label": "流动性条款匹配",
        "description": "申赎、锁定期、底层资产流动性和压力期机制是否匹配。",
        "data_type": "single_select",
        "options": ["匹配", "可接受错配", "明显错配", "特殊流动性风险", "未评估"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_terms",
        "display_order": 205,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "判断基金条款和底层资产流动性是否匹配。",
            "standard": "明显错配表示赎回条款与底层流动性不匹配；特殊流动性风险包括闸门、侧袋、集中赎回或难估值资产。",
            "evidence": ["fund_contract", "liquidity_terms", "holdings_liquidity", "redemption_history"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "fee_value_assessment",
        "label": "费用价值匹配",
        "description": "费用是否与 alpha、容量稀缺性、服务和条款匹配。",
        "data_type": "single_select",
        "options": ["费用合理", "偏贵但可接受", "费用不匹配", "未评估"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_terms",
        "display_order": 208,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "判断持有人支付的费用是否有足够风险调整后价值支撑。",
            "standard": "费用不匹配表示费用高于可获得 beta/alpha、透明度或服务质量；未评估不能支撑高 conviction。",
            "evidence": ["fee_schedule", "peer_fee_comparison", "performance_after_fees", "terms_review"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "alignment_quality",
        "label": "利益一致性",
        "description": "管理人与持有人利益是否一致。",
        "data_type": "single_select",
        "options": ["强一致", "基本一致", "存在冲突", "不清楚"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_governance",
        "display_order": 209,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "判断自有资金、长期激励、容量纪律和披露是否与持有人一致。",
            "standard": "存在冲突包括费用、渠道、规模扩张、关联交易或流动性安排与持有人利益不一致。",
            "evidence": ["ownership_investment", "fee_terms", "capacity_policy", "related_party_disclosure"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "historical_delivery",
        "label": "历史兑现度",
        "description": "管理人/产品是否长期兑现其声明能力。",
        "data_type": "single_select",
        "options": ["稳定兑现", "环境依赖", "尚未验证", "兑现失效"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_delivery",
        "display_order": 210,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "这是 buy-side 研究里的“有没有说到做到”。",
            "standard": "必须结合完整周期和压力阶段，不用短期排名替代。",
            "evidence": ["full_cycle_performance", "drawdown_review", "style_exposure", "peer_comparison"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "portfolio_role",
        "label": "组合角色",
        "description": "该标的更适合在组合中承担什么角色，可多选但通常不超过两个。",
        "data_type": "multi_select",
        "options": ["核心配置", "卫星增强", "分散化工具", "防守/对冲", "战术配置", "仅观察"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_role",
        "display_order": 215,
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "把单一标的研究结论翻译成组合用途。",
            "standard": "组合角色必须与相关性、风险贡献、容量、交易或申赎约束及当前投资结论一致；仅观察不能与已建议配置的高 conviction 结论并存。",
            "evidence": ["correlation", "risk_contribution", "portfolio_gap", "research_notes"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "equity_business_quality",
        "label": "Business Quality",
        "description": "Durability of the listed company's economics, competitive position, and reinvestment opportunity.",
        "data_type": "single_select",
        "options": ["Exceptional", "Strong", "Average", "Weak", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_equity",
        "display_order": 220,
        "instrument_scope_json": ["equity"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "综合商业模式、竞争优势、资本回报和可再投资空间，而不是短期股价表现。",
            "standard": "结论应由盈利结构、竞争行为、客户/供应商关系与行业结构支撑。",
            "evidence": ["financials", "industry_research", "management_evidence", "research_notes"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "equity_valuation_view",
        "label": "Valuation View",
        "description": "Current valuation conclusion relative to normalized fundamentals and the investment thesis.",
        "data_type": "single_select",
        "options": ["Deeply Undervalued", "Undervalued", "Fair", "Expensive", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_equity",
        "display_order": 225,
        "instrument_scope_json": ["equity"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "估值判断必须对应明确的盈利、现金流、资产或情景框架。",
            "standard": "不把历史分位本身当作内在价值；记录关键假设和失效条件。",
            "evidence": ["valuation_model", "financials", "scenario_analysis"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "equity_financial_quality",
        "label": "Financial Quality",
        "description": "Quality of earnings, cash conversion, leverage, and balance-sheet resilience.",
        "data_type": "single_select",
        "options": ["High", "Acceptable", "Cyclical", "Fragile", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_equity",
        "display_order": 230,
        "instrument_scope_json": ["equity"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "区分会计利润、现金兑现和资产负债表承压能力。",
            "standard": "至少结合现金转换、应计项目、资本化政策、杠杆和到期结构。",
            "evidence": ["financial_statements", "cash_flow", "balance_sheet", "accounting_notes"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "equity_governance_quality",
        "label": "Governance & Capital Allocation",
        "description": "Management incentives, minority-holder alignment, governance, and capital-allocation quality.",
        "data_type": "single_select",
        "options": ["Strong", "Acceptable", "Mixed", "Weak", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_equity",
        "display_order": 235,
        "instrument_scope_json": ["equity"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "记录管理层行为、激励、关联交易与资本配置，而不是只看人物履历。",
            "standard": "结合历史承诺兑现、并购、分红回购、融资稀释和少数股东待遇。",
            "evidence": ["governance_filings", "capital_allocation_history", "management_record"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "etf_index_fit",
        "label": "Index / Strategy Fit",
        "description": "How well the tracked index or ruleset expresses the intended portfolio exposure.",
        "data_type": "single_select",
        "options": ["Excellent", "Good", "Compromised", "Poor", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_etf",
        "display_order": 240,
        "instrument_scope_json": ["etf"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "判断指数规则、成分边界和权重方法是否真正表达目标敞口。",
            "standard": "不能用 ETF 名称代替对指数规则、集中度、换手和不可投资成分的检查。",
            "evidence": ["index_methodology", "holdings", "concentration", "turnover"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "etf_tracking_quality",
        "label": "Tracking Quality",
        "description": "Observed and expected ability to deliver the tracked exposure after fees and implementation effects.",
        "data_type": "single_select",
        "options": ["Strong", "Acceptable", "Variable", "Weak", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_etf",
        "display_order": 245,
        "instrument_scope_json": ["etf"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "综合跟踪差异、跟踪误差、费用、现金拖累和复制方式。",
            "standard": "缺少对应基准和一致收益口径时标记 Unclear，不用价格相关性替代。",
            "evidence": ["benchmark_returns", "fund_returns", "fees", "replication_method"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "etf_liquidity_quality",
        "label": "Liquidity & Trading Quality",
        "description": "Secondary-market liquidity, spread, creation/redemption depth, and premium/discount behavior.",
        "data_type": "single_select",
        "options": ["Strong", "Adequate", "Thin", "Stressed", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_etf",
        "display_order": 250,
        "instrument_scope_json": ["etf"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "把屏幕成交、价差、底层流动性和申赎机制一起判断。",
            "standard": "成交量不是唯一证据；压力期折溢价和做市深度应单独核查。",
            "evidence": ["volume", "bid_ask_spread", "premium_discount", "underlying_liquidity"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "etf_structure_quality",
        "label": "Structure & Cost Quality",
        "description": "Fund structure, securities lending, tax, counterparty, closure, and total-cost assessment.",
        "data_type": "single_select",
        "options": ["Strong", "Acceptable", "Mixed", "Weak", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_etf",
        "display_order": 255,
        "instrument_scope_json": ["etf"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "评价持有者实际承担的结构、税务、对手方和关闭风险。",
            "standard": "费用率只是总成本的一部分；需结合跟踪差异、借券收益与交易成本。",
            "evidence": ["prospectus", "fees", "securities_lending", "fund_size", "issuer_policy"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "index_methodology_quality",
        "label": "Methodology Quality",
        "description": "Clarity, economic rationale, robustness, and reproducibility of the index methodology.",
        "data_type": "single_select",
        "options": ["Strong", "Acceptable", "Fragile", "Weak", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_index",
        "display_order": 260,
        "instrument_scope_json": ["index"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "判断方法论是否透明、可复现且有明确经济含义。",
            "standard": "警惕复杂但缺乏经济依据、依赖自由裁量或过度回测拟合的规则。",
            "evidence": ["methodology_document", "rule_history", "backfill_policy", "governance"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "index_representation_quality",
        "label": "Market Representation",
        "description": "How well constituents and weights represent the market, segment, factor, or theme claimed by the index.",
        "data_type": "single_select",
        "options": ["High", "Adequate", "Biased", "Poor", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_index",
        "display_order": 265,
        "instrument_scope_json": ["index"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "检查成分边界、权重、集中度和行业/风格偏差。",
            "standard": "指数名称不能证明代表性；必须查看实际成分和长期暴露。",
            "evidence": ["constituents", "weights", "sector_exposure", "factor_exposure"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "index_investability_quality",
        "label": "Investability",
        "description": "Practical replicability after liquidity, capacity, turnover, reconstitution, and market-access constraints.",
        "data_type": "single_select",
        "options": ["High", "Adequate", "Constrained", "Poor", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_index",
        "display_order": 270,
        "instrument_scope_json": ["index"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "评价从纸面指数转化为可交易组合后的容量、成本和可复制性。",
            "standard": "结合成分流动性、换手、调仓拥挤、市场准入和公司行动处理。",
            "evidence": ["constituent_liquidity", "turnover", "rebalance_history", "market_access"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "index_governance_quality",
        "label": "Methodology Governance",
        "description": "Quality of index-provider governance, consultation, exception handling, and change control.",
        "data_type": "single_select",
        "options": ["Strong", "Acceptable", "Discretionary", "Weak", "Unclear"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_index",
        "display_order": 275,
        "instrument_scope_json": ["index"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "记录方法论变更、例外处置和利益冲突治理。",
            "standard": "明确区分可预测规则与委员会自由裁量，并保留重大变更证据。",
            "evidence": ["governance_policy", "consultations", "methodology_changes", "committee_disclosures"],
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "equity_correlation_bucket",
        "label": "权益相关性",
        "description": "与权益市场的典型相关性水平。",
        "data_type": "single_select",
        "options": ["低相关", "中相关", "高相关", "负相关/危机对冲"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_risk",
        "display_order": 330,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "帮助判断基金在组合里的分散化价值。",
            "standard": "以持仓和历史表现为主，不用短窗口噪声替代长期判断。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "preferred_regime",
        "label": "适配环境",
        "description": "更容易发挥优势的市场环境，可多选。",
        "data_type": "multi_select",
        "options": ["低波震荡", "高波趋势", "流动性宽松", "流动性收紧", "单边上涨", "单边下跌", "商品趋势", "股指震荡"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_regime",
        "display_order": 340,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "帮助投委会理解“什么时候该用它”。",
            "standard": "只标长期更易发挥优势的环境，不标短期行情观点。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "weak_regime",
        "label": "脆弱环境",
        "description": "更容易失效或放大风险的环境，可多选。",
        "data_type": "multi_select",
        "options": ["高波反转", "流动性冲击", "无趋势震荡", "权益急跌后V形", "商品快速切换", "基差异常/挤仓"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_regime",
        "display_order": 350,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "记录基金最容易失效的环境，用于风控和仓位讨论。",
            "standard": "必须能被历史回撤或机制解释支撑。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "transparency_quality",
        "label": "研究透明度",
        "description": "产品对外信息披露与可研究性质量。",
        "data_type": "single_select",
        "options": ["高", "中", "低"],
        "is_groupable": False,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_operational",
        "display_order": 370,
        "instrument_scope_json": ["public_fund", "private_fund"],
        "applicability_json": {"coverage_status": ["Proposed", "Invested", "Paused"]},
        "rubric_json": {
            "summary": "衡量后续跟踪是否有足够材料支撑。",
            "standard": "看披露频率、口径一致性、访谈可得性和底层可验证程度。",
        },
        "required_for_monitoring": True,
    },
]

FIELD_REGISTRY = [
    {
        "field_key": "instrument_name",
        "label": "Name",
        "description": "Canonical instrument display name from the watchlist row read model.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.instrument_name",
        "default_width": 320,
        "default_visible": True,
    },
    {
        "field_key": "instrument_type",
        "label": "Instrument Type",
        "description": "Top-level instrument type resolved from shared identity.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.instrument_type",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "currency",
        "label": "Currency",
        "description": "Canonical instrument currency from the shared Instrument Registry.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_registry"]},
        "source_domain": "instrument_registry",
        "source_metric_code": "instrument.currency",
        "default_width": 100,
        "default_visible": False,
    },
    {
        "field_key": "ticker_or_isin",
        "label": "Ticker / ISIN",
        "description": "Primary public identifier for the row.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "identifier",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["primary_identifier"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.ticker_or_isin",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "latest_quote",
        "label": "Latest Value",
        "description": "Most recent valuation-role value: Unit NAV for funds, market price for equities and ETFs, or index level for indexes.",
        "category_code": "general",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "instrument_chart_read_model.latest_values.valuation.value",
        "default_width": 130,
        "default_visible": False,
    },
    {
        "field_key": "latest_quote_date",
        "label": "Value Date",
        "description": "As-of date for the most recent valuation-role value.",
        "category_code": "general",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "instrument_chart_read_model.latest_values.valuation.date",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "latest_cumulative_nav",
        "label": "Cumulative NAV",
        "description": "Most recent dividend-reinvested cumulative NAV for a public or private fund; blank for other asset types.",
        "category_code": "general",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "instrument_chart_read_model.latest_values.total_return.value",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "latest_cumulative_nav_date",
        "label": "Cumulative NAV Date",
        "description": "As-of date for the most recent dividend-reinvested cumulative NAV; blank for other asset types.",
        "category_code": "general",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "instrument_chart_read_model.latest_values.total_return.date",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "management_firm_name",
        "label": "Manager / Issuer",
        "description": "Current fund manager, advisor, or ETF issuer.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.management_firm_name",
        "default_width": 220,
        "default_visible": False,
    },
    {
        "field_key": "aum",
        "label": "AUM",
        "description": "Current assets under management from the watchlist row read model.",
        "category_code": "basics",
        "data_type": "number",
        "formatter_code": "currency_compact",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.aum",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "attr.research_current_view",
        "label": "Current Investment View",
        "description": "Current analyst conclusion from the investment research profile.",
        "category_code": "research_framework",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_research_profile"]},
        "source_domain": "research",
        "source_metric_code": "instrument_research_profile.current_view",
        "default_width": 280,
        "default_visible": False,
    },
    {
        "field_key": "attr.manual_rating",
        "label": "Research Rating",
        "description": "Current 1–5 analyst conviction rating; this is not an automatic quantitative score.",
        "category_code": "research_framework",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "discrete",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_research_profile"]},
        "source_domain": "research",
        "source_metric_code": "instrument_research_profile.manual_rating",
        "default_width": 130,
        "default_visible": False,
    },
    {
        "field_key": "attr.primary_analyst",
        "label": "Primary Analyst",
        "description": "Current owner of the investment research profile.",
        "category_code": "research_framework",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_research_profile"]},
        "source_domain": "research",
        "source_metric_code": "instrument_research_profile.primary_analyst",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "attr.research_next_review_date",
        "label": "Next Research Review",
        "description": "Scheduled date for the next full investment-thesis review.",
        "category_code": "monitoring",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_research_profile"]},
        "source_domain": "research",
        "source_metric_code": "instrument_research_profile.next_review_date",
        "default_width": 170,
        "default_visible": False,
    },
    {
        "field_key": "attr.research_note_count",
        "label": "Research Records",
        "description": "Number of active evidence, meeting, event, decision, risk, and review records.",
        "category_code": "monitoring",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_research_note"]},
        "source_domain": "research",
        "source_metric_code": "instrument_research_note.active_count",
        "default_width": 145,
        "default_visible": False,
    },
    {
        "field_key": "attr.research_next_follow_up_date",
        "label": "Next Follow-up",
        "description": "Earliest unresolved follow-up date across active research records.",
        "category_code": "monitoring",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_research_note"]},
        "source_domain": "research",
        "source_metric_code": "instrument_research_note.next_follow_up_date",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "attr.research_updated_at",
        "label": "Research Updated",
        "description": "Last update time of the current investment research profile.",
        "category_code": "monitoring",
        "data_type": "datetime",
        "formatter_code": "datetime",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_research_profile"]},
        "source_domain": "research",
        "source_metric_code": "instrument_research_profile.updated_at",
        "default_width": 170,
        "default_visible": False,
    },
    *[
        {
            "field_key": field_key,
            "label": label,
            "description": description,
            "category_code": "performance_risk",
            "data_type": "sparkline",
            "formatter_code": "sparkline",
            "sort_mode": "none",
            "filter_mode": "none",
            "group_mode": "none",
            "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
            "product_scope_json": [],
            "availability_rule_json": {
                "requires": ["instrument_chart_read_model"]
            },
            "source_domain": "read_model",
            "source_metric_code": (
                f"instrument_chart_read_model.normalized_return.{window.lower()}"
            ),
            "default_width": 140,
            "default_visible": False,
        }
        for field_key, window, label, description in (
            (
                "return_chart_1d",
                "1D",
                "Return 1D",
                "Cumulative return from the last valid close on or before the "
                "one-day boundary to the latest close.",
            ),
            (
                "return_chart_1w",
                "1W",
                "Return 1W",
                "Cumulative return from the last valid close on or before the "
                "one-week boundary to the latest close.",
            ),
            (
                "return_chart_1m",
                "1M",
                "Return 1M",
                "Cumulative return from the last valid close on or before the "
                "one-month boundary to the latest close.",
            ),
            (
                "return_chart_1y",
                "1Y",
                "Return 1Y",
                "Cumulative return from the last valid close on or before the "
                "one-year boundary to the latest close.",
            ),
        )
    ],
    {
        "field_key": "return_ytd",
        "label": "YTD",
        "description": "Year-to-date return from the selected calculation series, ending at this instrument's own latest observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_ytd",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_mtd",
        "label": "MTD",
        "description": "Month-to-date return from the selected calculation series, ending at this instrument's own latest observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_mtd",
        "default_width": 120,
        "default_visible": True,
    },
    {
        "field_key": "return_1w",
        "label": "1W Return",
        "description": "Calendar 1-week return from the selected calculation series, ending at this instrument's own latest observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1w",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1m",
        "label": "1M",
        "description": "Calendar 1-month return from the selected calculation series, ending at this instrument's own latest observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1m",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_3m",
        "label": "3M",
        "description": "Calendar 3-month return from the selected calculation series, ending at this instrument's own latest observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_3m",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_6m",
        "label": "6M",
        "description": "Calendar 6-month return from the selected calculation series, ending at this instrument's own latest observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_6m",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1y",
        "label": "1Y",
        "description": "Trailing 1-year return from the selected calculation series, ending at this instrument's own latest observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1y",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "annualized_return",
        "label": "Ann.",
        "description": "Since-inception annualized return through this instrument's own latest observation; withheld before the first calendar anniversary.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.annualized_return",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "return_3y",
        "label": "3Y",
        "description": "Trailing 3-year annualized return ending at this instrument's own latest calculation-series observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_3y_annualized",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_5y",
        "label": "5Y",
        "description": "Trailing 5-year annualized return ending at this instrument's own latest calculation-series observation.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_5y_annualized",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "max_drawdown",
        "label": "Max DD",
        "description": "Since-inception maximum drawdown through this instrument's own latest observation, calculated from available canonical observations; inspect data quality alongside the metric.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.max_drawdown",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "attr.current_drawdown",
        "label": "Current DD",
        "description": "Current drawdown through this instrument's own latest observation relative to its prior high watermark, calculated from available canonical observations.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_risk_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.current_drawdown",
        "default_width": 120,
        "default_visible": False,
    },
    {
        "field_key": "volatility",
        "label": "Volatility",
        "description": "Since-inception annualized volatility through this instrument's own latest observation, calculated from available canonical return intervals; inspect data quality alongside the metric.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.volatility",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "sharpe_ratio",
        "label": "Sharpe Ratio",
        "description": "Since-inception zero-risk-free Sharpe ratio through this instrument's own latest observation, calculated from available canonical return intervals; inspect data quality alongside the metric.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.sharpe_ratio",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_group",
        "label": "Peer Group",
        "description": "Taxonomy-derived peer group used for peer percentile calculations.",
        "category_code": "performance_risk",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_group",
        "default_width": 220,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_sample_count",
        "label": "Peer Sample",
        "description": "Number of comparable instruments, excluding the current instrument, with the same taxonomy leaf and metric as-of date.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_sample_count",
        "default_width": 120,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_1w_percentile",
        "label": "1W Return Pctl",
        "description": "1-week return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_1w_percentile",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_1m_percentile",
        "label": "1M Pctl",
        "description": "1-month return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_1m_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_ytd_percentile",
        "label": "YTD Pctl",
        "description": "Year-to-date return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_ytd_percentile",
        "default_width": 170,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_1y_percentile",
        "label": "1Y Pctl",
        "description": "1-year return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_1y_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_3y_percentile",
        "label": "3Y Pctl",
        "description": "3-year annualized return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_3y_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_5y_percentile",
        "label": "5Y Pctl",
        "description": "5-year annualized return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_5y_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_annualized_return_percentile",
        "label": "Ann. Pctl",
        "description": "Since-inception annualized return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_annualized_return_percentile",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_volatility_percentile",
        "label": "Volatility Percentile",
        "description": "Volatility percentile within the taxonomy peer group. Lower volatility ranks better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_volatility_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_max_drawdown_percentile",
        "label": "Max DD Pctl",
        "description": "Maximum drawdown percentile within the taxonomy peer group. Shallower drawdown ranks better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_max_drawdown_percentile",
        "default_width": 185,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_sharpe_percentile",
        "label": "Sharpe Percentile",
        "description": "Sharpe ratio percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_sharpe_percentile",
        "default_width": 155,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_calmar_percentile",
        "label": "Calmar Percentile",
        "description": "Calmar ratio percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_calmar_percentile",
        "default_width": 155,
        "default_visible": False,
    },
    {
        "field_key": "duration",
        "label": "Duration",
        "description": "Weighted effective duration derived from exposure analytics.",
        "category_code": "exposure",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_duration",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "avg_credit_rating",
        "label": "Avg Credit Rating",
        "description": "Exposure-weighted average credit quality.",
        "category_code": "exposure",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.avg_credit_rating",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "yield_to_worst",
        "label": "Yield To Worst",
        "description": "Exposure-weighted yield to worst derived from holdings analytics.",
        "category_code": "exposure",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_yield_to_worst",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "metric_as_of_date",
        "label": "Metric As Of",
        "description": "Instrument-specific endpoint used by the materialized return and risk fields; Watchlist rows need not share one date.",
        "category_code": "monitoring",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.last_nav_date",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "exposure_updated_at",
        "label": "Holdings Source Cutoff",
        "description": "Evidence cutoff timestamp of the holdings statement used by the current exposure snapshot.",
        "category_code": "monitoring",
        "data_type": "datetime",
        "formatter_code": "datetime",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.exposure_updated_at",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "data_freshness_status",
        "label": "Freshness",
        "description": "System freshness status derived from the current read model.",
        "category_code": "monitoring",
        "data_type": "string",
        "formatter_code": "status",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.data_freshness_status",
        "default_width": 140,
        "default_visible": True,
    },
]


INSTRUMENT_TAXONOMY_FIELD_REGISTRY = [
    *[
        {
            "field_key": f"attr.instrument_taxonomy_level_{level}",
            "label": f"分类层级 {level}",
            "description": f"Level {level} of the assigned cross-asset instrument taxonomy path.",
            "category_code": "instrument_taxonomy",
            "data_type": "string",
            "formatter_code": "text",
            "sort_mode": "alpha",
            "filter_mode": "multi_select",
            "group_mode": "none",
            "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
            "product_scope_json": [],
            "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
            "source_domain": "taxonomy",
            "source_metric_code": f"instrument_taxonomy.derived.level_{level}",
            "default_width": 150,
            "default_visible": False,
        }
        for level in range(1, 8)
    ],
    {
        "field_key": "attr.instrument_taxonomy_leaf",
        "label": "分类叶子",
        "description": "Leaf label of the assigned cross-asset instrument taxonomy path.",
        "category_code": "instrument_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "instrument_taxonomy.derived.leaf",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.instrument_taxonomy_path",
        "label": "分类路径",
        "description": "Full assigned cross-asset instrument taxonomy path.",
        "category_code": "instrument_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "none",
        "instrument_scope_json": ["public_fund", "private_fund", "etf", "equity", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "instrument_taxonomy.derived.path",
        "default_width": 280,
        "default_visible": False,
    },
]


def _attribute_field_key(attribute_key: str) -> str:
    return f"attr.{attribute_key}"


ATTRIBUTE_FIELD_CATEGORY_BY_DOMAIN = {
    "overview": "basics",
    "research": "research_framework",
    "monitoring": "monitoring_assessment",
}


def build_attribute_field_definition(
    definition: dict[str, object],
) -> dict[str, object]:
    data_type = str(definition["data_type"])
    filter_mode = "multi_select"
    group_mode = "discrete"
    formatter_code = "text"
    sort_mode = "alpha"
    if data_type == "boolean":
        formatter_code = "boolean"
    elif data_type == "number":
        formatter_code = "decimal"
        filter_mode = "range"
        group_mode = "bucket"
        sort_mode = "numeric"
    elif data_type == "date":
        formatter_code = "date"
        filter_mode = "date_range"
        group_mode = "bucket"
        sort_mode = "date"
    elif data_type == "multi_select":
        formatter_code = "tags"

    supports_discrete_grouping = data_type in {"single_select", "boolean"}
    return {
        "field_key": _attribute_field_key(str(definition["attribute_key"])),
        "label": str(definition["label"]),
        "description": (
            str(definition["description"])
            if definition.get("description") is not None
            else None
        ),
        "category_code": ATTRIBUTE_FIELD_CATEGORY_BY_DOMAIN.get(
            str(definition.get("domain_code") or "research"),
            "research_framework",
        ),
        "data_type": data_type,
        "formatter_code": formatter_code,
        "sort_mode": sort_mode,
        "filter_mode": filter_mode,
        "group_mode": (
            group_mode
            if definition.get("is_groupable", False) and supports_discrete_grouping
            else "none"
        ),
        "instrument_scope_json": [
            str(item)
            for item in definition.get("instrument_scope_json", ["public_fund", "private_fund", "etf"])
            if str(item).strip()
        ],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_attribute_value"]},
        "source_domain": "custom_attribute",
        "source_metric_code": f"instrument_attribute_value.{definition['attribute_key']}",
        "default_width": 160,
        "default_visible": bool(definition.get("default_visible", False)),
    }


def current_field_registry() -> list[dict[str, object]]:
    fields = deepcopy(FIELD_REGISTRY)
    fields.extend(deepcopy(INSTRUMENT_TAXONOMY_FIELD_REGISTRY))
    fields.extend(
        build_attribute_field_definition(item)
        for item in INSTRUMENT_ATTRIBUTE_DEFINITIONS
        if item.get("is_view_column", True)
    )
    return fields
