from __future__ import annotations

from copy import deepcopy


FIELD_CATEGORIES = [
    {"category_code": "general", "label": "General", "display_order": 1},
    {"category_code": "basics", "label": "Basics", "display_order": 2},
    {
        "category_code": "product_taxonomy",
        "label": "Product Taxonomy",
        "display_order": 3,
    },
    {
        "category_code": "research_framework",
        "label": "Research Tags",
        "display_order": 4,
    },
    {
        "category_code": "monitoring_assessment",
        "label": "Monitoring Assessment",
        "display_order": 5,
    },
    {"category_code": "fees_terms", "label": "Fees & Terms", "display_order": 6},
    {
        "category_code": "performance_risk",
        "label": "Performance & Risk",
        "display_order": 7,
    },
    {"category_code": "exposure", "label": "Exposure", "display_order": 8},
    {
        "category_code": "ratings_analysis",
        "label": "Ratings & Analysis",
        "display_order": 9,
    },
    {"category_code": "monitoring", "label": "Monitoring", "display_order": 10},
]

INSTRUMENT_ATTRIBUTE_DEFINITIONS = [
    {
        "attribute_key": "fund_vehicle",
        "label": "产品形态",
        "description": "ETF、场外开放式、私募契约型等载体形态，属于基本情况而非策略分类。",
        "data_type": "single_select",
        "options": [
            "ETF",
            "LOF/场内开放式",
            "场外开放式",
            "封闭式",
            "集合资管计划",
            "契约型私募基金",
            "公司型私募基金",
            "其他",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "overview",
        "group_code": "overview_identity",
        "display_order": 20,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述基金法律/交易载体，不等于分类树。",
            "standard": "按当前主载体单选；不要把策略判断写进载体字段。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "coverage_status",
        "label": "Coverage Status",
        "description": "Research status such as invested, focus, watch, or archived.",
        "data_type": "single_select",
        "options": ["Invested", "Focus", "Watch", "Archived"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": True,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 110,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述研究覆盖状态，而不是产品分类。",
            "standard": "只保留一个当前有效状态，研究会议后更新。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "focus_bucket",
        "label": "Focus Bucket",
        "description": "Internal attention bucket for near-term review priority.",
        "data_type": "single_select",
        "options": ["Tier 1", "Tier 2", "Tier 3"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 120,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "用于排优先级，不代表基金好坏。",
            "standard": "Tier 1 代表近期最需要研究/复核。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "implementation_style",
        "label": "实现方式",
        "description": "投资决策和执行主要由主观判断、量化模型还是规则复制驱动。",
        "data_type": "single_select",
        "options": ["主观", "量化", "主观+量化", "被动规则"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 130,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述收益生成方式，不等于分类树层级。",
            "standard": "按当前主实现方式单选；混合策略可选主观+量化。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "trading_universe",
        "label": "交易市场/品种",
        "description": "主要交易的底层市场与工具，可多选。",
        "data_type": "multi_select",
        "options": [
            "A股",
            "港股",
            "美股",
            "债券",
            "可转债",
            "股指期货",
            "国债期货",
            "商品期货",
            "期权",
            "海外市场",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 140,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述基金真实操作的底层市场，不是销售口径。",
            "standard": "保留 1-3 个核心市场/工具即可。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "alpha_source",
        "label": "主要收益来源",
        "description": "基金最核心的收益引擎，可多选。",
        "data_type": "multi_select",
        "options": [
            "选股Alpha",
            "指数复制",
            "贝塔增强",
            "趋势跟踪",
            "期限结构",
            "价差收敛",
            "波动率交易",
            "事件驱动",
            "宏观择时",
            "Carry/票息",
            "主题/风格暴露",
            "高频/微观结构",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 150,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "回答“这只产品靠什么赚钱”。",
            "standard": "只保留真正长期贡献超额的 1-3 个来源。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "style_profile",
        "label": "风格画像",
        "description": "面向 FOF 定性研究的标准化风格标签，可多选。",
        "data_type": "multi_select",
        "options": [
            "深度价值",
            "均衡成长",
            "GARP",
            "行业轮动",
            "短线交易",
            "高换手",
            "集中持仓",
            "分散持仓",
            "多因子",
            "高频",
            "中频",
            "低频",
            "指数增强",
            "信用下沉",
            "久期交易",
            "趋势跟踪",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_style",
        "display_order": 160,
        "asset_scope_json": ["fund"],
        "applicability_json": {
            "fund_taxonomy_level_1": [
                "股票策略",
                "债券策略",
                "期货及衍生品策略",
                "多资产策略",
                "组合基金",
                "其他",
                "股票型",
                "混合型",
                "债券型",
                "QDII",
                "商品型",
                "REITS",
                "FOF",
            ]
        },
        "rubric_json": {
            "summary": "把 FOF 研究里的风格判断标准化，便于横向比较。",
            "standard": "标签必须能被历史组合、访谈或披露材料反复验证。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "manager_assessment",
        "label": "管理人评价",
        "description": "管理人与团队层面的定性判断，可多选。",
        "data_type": "multi_select",
        "options": ["历史业绩优秀", "团队稳定", "研究体系成熟", "风控纪律强", "渠道能力强", "待持续验证"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_manager",
        "display_order": 170,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "只记录已经形成共识的管理人判断，不写临时印象。",
            "standard": "每个标签都应能对应明确证据，如历史兑现、团队变动、访谈纪要。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "team_stability_assessment",
        "label": "团队稳定性",
        "description": "对核心投研团队是否稳定的研究判断。",
        "data_type": "single_select",
        "options": ["高", "中", "低"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_manager",
        "display_order": 180,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "区分团队是否具备稳定持续输出能力。",
            "standard": "结合核心人员流动、职责清晰度和投研流程延续性判断。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "portfolio_construction",
        "label": "组合构建方式",
        "description": "组合如何落地到仓位、约束与换手，可多选。",
        "data_type": "multi_select",
        "options": ["集中持仓", "分散持仓", "行业集中", "风格均衡", "严格基准约束", "低跟踪误差", "容量敏感", "高换手"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 190,
        "asset_scope_json": ["fund"],
        "applicability_json": {
            "fund_taxonomy_level_1": [
                "股票策略",
                "债券策略",
                "期货及衍生品策略",
                "多资产策略",
                "组合基金",
                "其他",
                "股票型",
                "混合型",
                "债券型",
                "QDII",
                "商品型",
                "REITS",
                "FOF",
            ]
        },
        "rubric_json": {
            "summary": "描述组合工程特征，帮助解释收益与回撤形态。",
            "standard": "仅选择长期、可观测、会影响持有人体验的构建特征。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "capacity_bucket",
        "label": "容量判断",
        "description": "产品容量与规模约束的研究结论。",
        "data_type": "single_select",
        "options": ["容量充足", "容量一般", "容量受限", "强容量约束"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_manager",
        "display_order": 200,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "用于识别规模扩张是否会侵蚀策略有效性。",
            "standard": "结合市场容量、换手、底层工具流动性和历史规模变化判断。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "historical_delivery",
        "label": "历史兑现度",
        "description": "管理人/产品是否长期兑现其声明能力。",
        "data_type": "single_select",
        "options": ["优秀", "稳健", "一般", "待验证"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_manager",
        "display_order": 210,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "这是 buy-side 研究里的“有没有说到做到”。",
            "standard": "必须结合完整周期和压力阶段，不用短期排名替代。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "volatility_bucket",
        "label": "波动分层",
        "description": "产品的典型波动水平。",
        "data_type": "single_select",
        "options": ["低波", "中波", "高波"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_risk",
        "display_order": 310,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "监控视角下的风险体感标签，不替代正式风险指标。",
            "standard": "结合历史波动、持仓结构和策略说明综合判断。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "drawdown_control",
        "label": "回撤控制",
        "description": "产品在压力阶段的回撤管理能力。",
        "data_type": "single_select",
        "options": ["强", "中", "弱"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_risk",
        "display_order": 320,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "用于持续跟踪产品在压力期的防守能力。",
            "standard": "观察历史大回撤、止损纪律、风险预算执行与恢复速度。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "equity_correlation_bucket",
        "label": "权益相关性",
        "description": "与权益市场的典型相关性水平。",
        "data_type": "single_select",
        "options": ["低相关", "中相关", "高相关", "负相关/危机对冲"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_risk",
        "display_order": 330,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "帮助判断基金在组合里的分散化价值。",
            "standard": "以持仓和历史表现为主，不用短窗口噪声替代长期判断。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "preferred_regime",
        "label": "适配环境",
        "description": "更容易发挥优势的市场环境，可多选。",
        "data_type": "multi_select",
        "options": ["低波震荡", "高波趋势", "流动性宽松", "流动性收紧", "单边上涨", "单边下跌", "商品趋势", "股指震荡"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_regime",
        "display_order": 340,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "帮助投委会理解“什么时候该用它”。",
            "standard": "只标长期更易发挥优势的环境，不标短期行情观点。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "weak_regime",
        "label": "脆弱环境",
        "description": "更容易失效或放大风险的环境，可多选。",
        "data_type": "multi_select",
        "options": ["高波反转", "流动性冲击", "无趋势震荡", "权益急跌后V形", "商品快速切换", "基差异常/挤仓"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_regime",
        "display_order": 350,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "记录基金最容易失效的环境，用于风控和仓位讨论。",
            "standard": "必须能被历史回撤或机制解释支撑。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "style_stability",
        "label": "风格稳定性",
        "description": "策略暴露和执行风格是否稳定。",
        "data_type": "single_select",
        "options": ["高", "中", "低"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_operational",
        "display_order": 360,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "监控产品是否偏离原始研究假设。",
            "standard": "结合持仓、换手、行业/因子暴露和沟通口径判断。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "transparency_quality",
        "label": "研究透明度",
        "description": "产品对外信息披露与可研究性质量。",
        "data_type": "single_select",
        "options": ["高", "中", "低"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_operational",
        "display_order": 370,
        "asset_scope_json": ["fund"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "衡量后续跟踪是否有足够材料支撑。",
            "standard": "看披露频率、口径一致性、访谈可得性和底层可验证程度。",
        },
        "required_for_monitoring": True,
    },
]

FIELD_REGISTRY = [
    {
        "field_key": "asset_name",
        "label": "Name",
        "description": "Canonical instrument display name from the watchlist row read model.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "discrete",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.asset_name",
        "default_width": 320,
        "default_visible": True,
    },
    {
        "field_key": "asset_type",
        "label": "Asset Type",
        "description": "Top-level instrument type resolved from shared identity.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.asset_type",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "ticker_or_isin",
        "label": "Ticker / ISIN",
        "description": "Primary public identifier for the row.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "identifier",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "none",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["primary_identifier"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.ticker_or_isin",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "latest_quote",
        "label": "Latest Quote",
        "description": "Most recent point from the active quote series used by the detail quote view.",
        "category_code": "general",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["asset_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "asset_chart_read_model.series.latest_quote",
        "default_width": 130,
        "default_visible": False,
    },
    {
        "field_key": "latest_quote_date",
        "label": "Quote Date",
        "description": "As-of date for the most recent active quote series point.",
        "category_code": "general",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["asset_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "asset_chart_read_model.series.latest_quote_date",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_regime",
        "label": "公募/私募",
        "description": "Fund taxonomy root derived from the assigned fund taxonomy path.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.fund_regime",
        "default_width": 120,
        "default_visible": True,
    },
    {
        "field_key": "attr.fund_taxonomy_level_1",
        "label": "一级分类",
        "description": "First internal taxonomy branch after 公募/私募, derived from fund taxonomy.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_1",
        "default_width": 120,
        "default_visible": True,
    },
    {
        "field_key": "attr.fund_taxonomy_level_2",
        "label": "二级分类",
        "description": "Second internal taxonomy branch for deeper fund grouping.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_2",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "attr.fund_taxonomy_level_3",
        "label": "三级分类",
        "description": "Third internal taxonomy branch for deeper fund grouping.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_3",
        "default_width": 170,
        "default_visible": True,
    },
    {
        "field_key": "attr.fund_taxonomy_level_4",
        "label": "四级分类",
        "description": "Fourth internal taxonomy branch for leaf-level fund grouping.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_4",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_taxonomy_level_5",
        "label": "五级分类",
        "description": "Fifth internal taxonomy branch for variable-depth taxonomy branches.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_5",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_taxonomy_level_6",
        "label": "六级分类",
        "description": "Sixth internal taxonomy branch for variable-depth taxonomy branches.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_6",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_taxonomy_leaf",
        "label": "分类叶子",
        "description": "Leaf taxonomy label derived from the fund taxonomy path.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.leaf",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_taxonomy_path",
        "label": "分类路径",
        "description": "Full fund taxonomy path derived from the taxonomy tree.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.path",
        "default_width": 280,
        "default_visible": False,
    },
    {
        "field_key": "management_firm_name",
        "label": "Management Firm",
        "description": "Current manager / advisor firm.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.management_firm_name",
        "default_width": 220,
        "default_visible": False,
    },
    {
        "field_key": "category_name",
        "label": "Peer Category",
        "description": "External peer group/category used for ranking and comparison, separate from internal fund taxonomy.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.category_name",
        "default_width": 240,
        "default_visible": True,
    },
    {
        "field_key": "asset_class",
        "label": "Asset Class",
        "description": "Top-level asset class for group by and filtering.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["asset_detail"]},
        "source_domain": "asset_detail",
        "source_metric_code": "asset_detail.metadata_json.asset_class",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "aum",
        "label": "AUM",
        "description": "Current assets under management from the watchlist row read model.",
        "category_code": "basics",
        "data_type": "number",
        "formatter_code": "currency_compact",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.aum",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "price_chart_1m",
        "label": "Price Chart",
        "description": "1-month NAV spark chart from the current chart read model.",
        "category_code": "performance_risk",
        "data_type": "sparkline",
        "formatter_code": "sparkline",
        "sort_mode": "none",
        "filter_mode": "none",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["asset_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "asset_chart_read_model.series",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "overall_rating",
        "label": "Overall Rating",
        "description": "Internal score-based rating derived from the current methodology.",
        "category_code": "ratings_analysis",
        "data_type": "integer",
        "formatter_code": "stars",
        "sort_mode": "numeric",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["asset_score_snapshot"]},
        "source_domain": "score",
        "source_metric_code": "asset_score_snapshot.overall_rating",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "analyst_stance",
        "label": "Analyst Stance",
        "description": "Current house view from the score snapshot.",
        "category_code": "ratings_analysis",
        "data_type": "string",
        "formatter_code": "badge",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["asset_score_snapshot"]},
        "source_domain": "score",
        "source_metric_code": "asset_score_snapshot.analyst_stance",
        "default_width": 160,
        "default_visible": True,
    },
    {
        "field_key": "return_ytd",
        "label": "Total Return (YTD)",
        "description": "Derived from canonical NAV facts.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_ytd",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1w",
        "label": "Total Return (1W)",
        "description": "1-week total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1w",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1m",
        "label": "Total Return (1M)",
        "description": "1-month total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1m",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1y",
        "label": "Total Return (1Y)",
        "description": "1-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1y",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "annualized_return",
        "label": "Annualized Return",
        "description": "Since-inception annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.annualized_return",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "return_3y",
        "label": "Total Return (3Y)",
        "description": "3-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_3y_annualized",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_5y",
        "label": "Total Return (5Y)",
        "description": "5-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_5y_annualized",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "max_drawdown",
        "label": "Max Drawdown",
        "description": "Maximum drawdown from the active performance snapshot.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.max_drawdown",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "volatility",
        "label": "Volatility",
        "description": "Risk snapshot volatility for the selected window.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.volatility",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "sharpe_ratio",
        "label": "Sharpe Ratio",
        "description": "Current risk-adjusted return metric.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.sharpe_ratio",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "duration",
        "label": "Duration",
        "description": "Weighted effective duration derived from exposure analytics.",
        "category_code": "exposure",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_duration",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "avg_credit_rating",
        "label": "Avg Credit Rating",
        "description": "Exposure-weighted average credit quality.",
        "category_code": "exposure",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.avg_credit_rating",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "yield_to_worst",
        "label": "Yield To Worst",
        "description": "Exposure-weighted yield to worst derived from holdings analytics.",
        "category_code": "exposure",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_yield_to_worst",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "last_nav_date",
        "label": "Last NAV Date",
        "description": "Most recent canonical NAV fact adopted for the asset.",
        "category_code": "monitoring",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.last_nav_date",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "exposure_updated_at",
        "label": "Holdings Updated At",
        "description": "Latest holdings statement adoption time.",
        "category_code": "monitoring",
        "data_type": "datetime",
        "formatter_code": "datetime",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.exposure_updated_at",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "data_freshness_status",
        "label": "Freshness",
        "description": "System freshness status derived from the current read model.",
        "category_code": "monitoring",
        "data_type": "string",
        "formatter_code": "status",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.data_freshness_status",
        "default_width": 140,
        "default_visible": True,
    },
]


def _attribute_field_key(attribute_key: str) -> str:
    return f"attr.{attribute_key}"


ATTRIBUTE_FIELD_CATEGORY_BY_DOMAIN = {
    "overview": "basics",
    "research": "research_framework",
    "monitoring": "monitoring_assessment",
}


def build_attribute_field_definition(
    definition: dict[str, object],
) -> dict[str, object]:
    data_type = str(definition["data_type"])
    filter_mode = "multi_select"
    group_mode = "discrete"
    formatter_code = "text"
    sort_mode = "alpha"
    if data_type == "boolean":
        formatter_code = "boolean"
    elif data_type == "number":
        formatter_code = "decimal"
        filter_mode = "range"
        group_mode = "bucket"
        sort_mode = "numeric"
    elif data_type == "date":
        formatter_code = "date"
        filter_mode = "date_range"
        group_mode = "bucket"
        sort_mode = "date"
    elif data_type == "multi_select":
        formatter_code = "tags"

    return {
        "field_key": _attribute_field_key(str(definition["attribute_key"])),
        "label": str(definition["label"]),
        "description": (
            str(definition["description"])
            if definition.get("description") is not None
            else None
        ),
        "category_code": ATTRIBUTE_FIELD_CATEGORY_BY_DOMAIN.get(
            str(definition.get("domain_code") or "research"),
            "research_framework",
        ),
        "data_type": data_type,
        "formatter_code": formatter_code,
        "sort_mode": sort_mode,
        "filter_mode": filter_mode,
        "group_mode": group_mode if definition.get("is_groupable", True) else "none",
        "asset_scope_json": [
            str(item)
            for item in definition.get("asset_scope_json", ["fund"])
            if str(item).strip()
        ],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_attribute_value"]},
        "source_domain": "custom_attribute",
        "source_metric_code": f"instrument_attribute_value.{definition['attribute_key']}",
        "default_width": 160,
        "default_visible": bool(definition.get("default_visible", False)),
    }


def current_field_registry() -> list[dict[str, object]]:
    fields = deepcopy(FIELD_REGISTRY)
    fields.extend(
        build_attribute_field_definition(item)
        for item in INSTRUMENT_ATTRIBUTE_DEFINITIONS
        if item.get("is_view_column", True)
    )
    return fields
