from __future__ import annotations

from copy import deepcopy


FIELD_CATEGORIES = [
    {"category_code": "general", "label": "General", "display_order": 1},
    {"category_code": "basics", "label": "Basics", "display_order": 2},
    {
        "category_code": "product_taxonomy",
        "label": "Product Taxonomy",
        "display_order": 3,
    },
    {
        "category_code": "research_framework",
        "label": "Research Tags",
        "display_order": 4,
    },
    {
        "category_code": "monitoring_assessment",
        "label": "Monitoring Assessment",
        "display_order": 5,
    },
    {"category_code": "fees_terms", "label": "Fees & Terms", "display_order": 6},
    {
        "category_code": "performance_risk",
        "label": "Performance & Risk",
        "display_order": 7,
    },
    {"category_code": "exposure", "label": "Exposure", "display_order": 8},
    {
        "category_code": "ratings_analysis",
        "label": "Ratings & Analysis",
        "display_order": 9,
    },
    {"category_code": "monitoring", "label": "Monitoring", "display_order": 10},
]

INSTRUMENT_ATTRIBUTE_DEFINITIONS = [
    {
        "attribute_key": "fund_vehicle",
        "label": "产品形态",
        "description": "ETF、场外开放式、私募契约型等载体形态，属于基本情况而非策略分类。",
        "data_type": "single_select",
        "options": [
            "ETF",
            "LOF/场内开放式",
            "场外开放式",
            "封闭式",
            "集合资管计划",
            "契约型私募基金",
            "公司型私募基金",
            "其他",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "overview",
        "group_code": "overview_identity",
        "display_order": 20,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述基金法律/交易载体，不等于分类树。",
            "standard": "按当前主载体单选；不要把策略判断写进载体字段。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "coverage_status",
        "label": "Status",
        "description": "Investment/watchlist lifecycle status such as watch, proposed, invested, paused, or exited. This is not Research View.",
        "data_type": "single_select",
        "options": ["Watch", "Proposed", "Invested", "Paused", "Exited"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": True,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 110,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述投资生命周期状态，而不是定性研究结论。",
            "standard": "只保留一个当前有效状态；Research View 和人工 rating 在 research payload 中维护。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "focus_bucket",
        "label": "Research Priority",
        "description": "Internal attention bucket for near-term research and review priority.",
        "data_type": "single_select",
        "options": ["Tier 1", "Tier 2", "Tier 3"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 120,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "用于排研究资源优先级，不代表基金好坏或是否持仓。",
            "standard": "Tier 1 代表近期最需要研究/复核；Tier 3 代表低频观察。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "research_evidence_level",
        "label": "证据充分度",
        "description": "当前定性结论背后的证据完整程度。",
        "data_type": "single_select",
        "options": ["完整证据", "部分证据", "轶事证据", "待验证"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_coverage",
        "display_order": 125,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "衡量标签、rating 和 Research View 是否有足够材料支撑。",
            "standard": "完整证据需要至少覆盖文档、访谈、业绩归因/持仓验证和条款检查；轶事证据不能支撑高 conviction。",
            "evidence": ["research_notes", "documents", "meeting_notes", "performance_attribution"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "investment_edge_quality",
        "label": "投资优势质量",
        "description": "收益来源是否清晰、可解释、可持续。",
        "data_type": "single_select",
        "options": ["清晰且可持续", "清晰但需验证", "主要是市场贝塔", "边际优势不清"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_edge",
        "display_order": 128,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "回答“这只产品是否有真正的、可持续的 edge”。",
            "standard": "必须能通过流程、团队、数据、市场结构或历史归因解释；不要把短期排名当作 edge。",
            "evidence": ["performance_attribution", "portfolio_history", "manager_interview", "process_materials"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "implementation_style",
        "label": "实现方式",
        "description": "投资决策和执行主要由主观判断、量化模型还是规则复制驱动。",
        "data_type": "single_select",
        "options": ["主观", "量化", "主观+量化", "被动规则"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 130,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述收益生成方式，不等于分类树层级。",
            "standard": "按当前主实现方式单选；混合策略可选主观+量化。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "process_repeatability",
        "label": "流程可复制性",
        "description": "研究、决策、交易和复盘流程是否能稳定重复。",
        "data_type": "single_select",
        "options": ["可重复", "部分可重复", "关键人驱动", "不透明"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 135,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "顶层管理人尽调维度，区分流程型能力和个人英雄式能力。",
            "standard": "可重复必须有清晰职责、研究/交易记录、组合结果解释和复盘机制；关键人驱动需要同步标记 key-person risk。",
            "evidence": ["investment_process", "decision_records", "portfolio_explainability", "team_interview"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "decision_discipline",
        "label": "决策纪律",
        "description": "投资决策是否依赖可验证证据、规则和复盘。",
        "data_type": "single_select",
        "options": ["证据驱动", "经验驱动", "机会型", "不清晰"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 138,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "判断投资行为是否有一致的决策和复盘纪律。",
            "standard": "证据驱动需要能看到投资备忘录、风控约束、交易理由或系统化规则；机会型表示仓位/交易较依赖短期判断。",
            "evidence": ["investment_memo", "risk_limits", "trade_rationale", "post_mortem"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "trading_universe",
        "label": "交易市场/品种",
        "description": "主要交易的底层市场与工具，可多选。",
        "data_type": "multi_select",
        "options": [
            "A股",
            "港股",
            "美股",
            "债券",
            "可转债",
            "股指期货",
            "国债期货",
            "商品期货",
            "期权",
            "海外市场",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_process",
        "display_order": 140,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "描述基金真实操作的底层市场，不是销售口径。",
            "standard": "保留 1-3 个核心市场/工具即可。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "alpha_source",
        "label": "主要收益来源",
        "description": "基金最核心的收益引擎，可多选。",
        "data_type": "multi_select",
        "options": [
            "选股Alpha",
            "指数复制",
            "贝塔增强",
            "趋势跟踪",
            "期限结构",
            "价差收敛",
            "波动率交易",
            "事件驱动",
            "宏观择时",
            "Carry/票息",
            "主题/风格暴露",
            "高频/微观结构",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_edge",
        "display_order": 150,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "回答“这只产品靠什么赚钱”。",
            "standard": "只保留真正长期贡献超额的 1-3 个来源。",
            "evidence": ["performance_attribution", "portfolio_history", "manager_interview"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "style_profile",
        "label": "风格画像",
        "description": "面向 FOF 定性研究的标准化风格标签，可多选。",
        "data_type": "multi_select",
        "options": [
            "深度价值",
            "均衡成长",
            "GARP",
            "行业轮动",
            "短线交易",
            "高换手",
            "集中持仓",
            "分散持仓",
            "多因子",
            "高频",
            "中频",
            "低频",
            "指数增强",
            "信用下沉",
            "久期交易",
            "趋势跟踪",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_style",
        "display_order": 160,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {
            "fund_taxonomy_level_1": [
                "股票策略",
                "债券策略",
                "期货及衍生品策略",
                "多资产策略",
                "组合基金",
                "其他",
                "股票型",
                "混合型",
                "债券型",
                "QDII",
                "商品型",
                "REITS",
                "FOF",
            ]
        },
        "rubric_json": {
            "summary": "把 FOF 研究里的风格判断标准化，便于横向比较。",
            "standard": "标签必须能被历史组合、访谈或披露材料反复验证。",
            "evidence": ["portfolio_history", "factor_exposure", "turnover", "manager_interview"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "manager_assessment",
        "label": "管理人评价",
        "description": "管理人与团队层面的定性判断，可多选。",
        "data_type": "multi_select",
        "options": [
            "资深核心PM",
            "机构化团队",
            "关键人风险",
            "团队纵深不足",
            "近期人员变动",
            "传承风险",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_manager",
        "display_order": 170,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "只记录已经形成共识的团队和组织判断，不写临时印象。",
            "standard": "每个标签都应能对应明确证据，如履历、团队职责、人员变动、访谈纪要或组织激励。",
            "evidence": ["team_roster", "ownership_incentives", "manager_interview", "org_change_log"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "team_stability_assessment",
        "label": "团队稳定性",
        "description": "对核心投研团队是否稳定的研究判断。",
        "data_type": "single_select",
        "options": ["稳定", "正常流动", "近期流失", "关键人依赖", "不清楚"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_manager",
        "display_order": 180,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "区分团队是否具备稳定持续输出能力。",
            "standard": "结合核心人员流动、职责清晰度和投研流程延续性判断。",
            "evidence": ["team_roster", "personnel_changes", "role_map", "manager_interview"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "portfolio_construction",
        "label": "组合构建方式",
        "description": "组合如何落地到仓位、约束与换手，可多选。",
        "data_type": "multi_select",
        "options": ["集中持仓", "分散持仓", "行业集中", "风格均衡", "严格基准约束", "低跟踪误差", "容量敏感", "高换手"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_style",
        "display_order": 190,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {
            "fund_taxonomy_level_1": [
                "股票策略",
                "债券策略",
                "期货及衍生品策略",
                "多资产策略",
                "组合基金",
                "其他",
                "股票型",
                "混合型",
                "债券型",
                "QDII",
                "商品型",
                "REITS",
                "FOF",
            ]
        },
        "rubric_json": {
            "summary": "描述组合工程特征，帮助解释收益与回撤形态。",
            "standard": "仅选择长期、可观测、会影响持有人体验的构建特征。",
            "evidence": ["holdings", "turnover", "risk_contribution", "benchmark_constraints"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "style_drift_risk",
        "label": "风格漂移风险",
        "description": "策略暴露和执行风格偏离原研究假设的风险。",
        "data_type": "single_select",
        "options": ["低", "中", "高", "不清楚"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_style",
        "display_order": 195,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "监控原始研究假设是否仍然成立。",
            "standard": "低表示历史暴露和沟通口径长期一致；高表示策略、仓位或风格频繁偏离原假设。",
            "evidence": ["holdings", "factor_exposure", "turnover", "manager_communication"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "risk_management_quality",
        "label": "风险管理质量",
        "description": "风险预算、约束、压力期应对和复盘是否有效。",
        "data_type": "single_select",
        "options": ["强", "合格", "被动", "弱", "不清楚"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_risk",
        "display_order": 198,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "判断风险是否被主动预算、约束和复盘。",
            "standard": "强需要能看到风险预算、止损/减仓机制、压力测试和一致执行；弱表示风险暴露与策略承诺不匹配。",
            "evidence": ["risk_limits", "drawdown_review", "stress_test", "risk_reports"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "capacity_bucket",
        "label": "容量判断",
        "description": "产品容量与规模约束的研究结论。",
        "data_type": "single_select",
        "options": ["可扩容", "有容量约束", "接近容量", "规模过大", "不清楚"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_terms",
        "display_order": 200,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "用于识别规模扩张是否会侵蚀策略有效性。",
            "standard": "结合市场容量、换手、底层工具流动性和历史规模变化判断。",
            "evidence": ["aum_history", "turnover", "market_liquidity", "slippage", "capacity_guidance"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "liquidity_terms_fit",
        "label": "流动性条款匹配",
        "description": "申赎、锁定期、底层资产流动性和压力期机制是否匹配。",
        "data_type": "single_select",
        "options": ["匹配", "可接受错配", "明显错配", "特殊流动性风险", "未评估"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_terms",
        "display_order": 205,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "判断基金条款和底层资产流动性是否匹配。",
            "standard": "明显错配表示赎回条款与底层流动性不匹配；特殊流动性风险包括闸门、侧袋、集中赎回或难估值资产。",
            "evidence": ["fund_contract", "liquidity_terms", "holdings_liquidity", "redemption_history"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "fee_value_assessment",
        "label": "费用价值匹配",
        "description": "费用是否与 alpha、容量稀缺性、服务和条款匹配。",
        "data_type": "single_select",
        "options": ["费用合理", "偏贵但可接受", "费用不匹配", "未评估"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_terms",
        "display_order": 208,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "判断持有人支付的费用是否有足够风险调整后价值支撑。",
            "standard": "费用不匹配表示费用高于可获得 beta/alpha、透明度或服务质量；未评估不能支撑高 conviction。",
            "evidence": ["fee_schedule", "peer_fee_comparison", "performance_after_fees", "terms_review"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "alignment_quality",
        "label": "利益一致性",
        "description": "管理人与持有人利益是否一致。",
        "data_type": "single_select",
        "options": ["强一致", "基本一致", "存在冲突", "不清楚"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_governance",
        "display_order": 209,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "判断自有资金、长期激励、容量纪律和披露是否与持有人一致。",
            "standard": "存在冲突包括费用、渠道、规模扩张、关联交易或流动性安排与持有人利益不一致。",
            "evidence": ["ownership_investment", "fee_terms", "capacity_policy", "related_party_disclosure"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "historical_delivery",
        "label": "历史兑现度",
        "description": "管理人/产品是否长期兑现其声明能力。",
        "data_type": "single_select",
        "options": ["稳定兑现", "环境依赖", "尚未验证", "兑现失效"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_delivery",
        "display_order": 210,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "这是 buy-side 研究里的“有没有说到做到”。",
            "standard": "必须结合完整周期和压力阶段，不用短期排名替代。",
            "evidence": ["full_cycle_performance", "drawdown_review", "style_exposure", "peer_comparison"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "portfolio_role",
        "label": "组合角色",
        "description": "该基金更适合在组合中承担什么角色，可多选但通常不超过两个。",
        "data_type": "multi_select",
        "options": ["核心配置", "卫星增强", "分散化工具", "防守/对冲", "战术配置", "仅观察"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "research",
        "group_code": "research_role",
        "display_order": 215,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "把单只基金研究结论翻译成组合用途。",
            "standard": "组合角色必须与相关性、风险贡献、容量、条款和 rating 一致；仅观察不能与 5 星同时存在。",
            "evidence": ["correlation", "risk_contribution", "portfolio_gap", "research_notes"],
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "volatility_bucket",
        "label": "波动分层",
        "description": "产品的典型波动水平。",
        "data_type": "single_select",
        "options": ["低波", "中波", "高波"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_risk",
        "display_order": 310,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "监控视角下的风险体感标签，不替代正式风险指标。",
            "standard": "结合历史波动、持仓结构和策略说明综合判断。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "drawdown_control",
        "label": "回撤控制",
        "description": "产品在压力阶段的回撤管理能力。",
        "data_type": "single_select",
        "options": ["强", "中", "弱"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_risk",
        "display_order": 320,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "用于持续跟踪产品在压力期的防守能力。",
            "standard": "观察历史大回撤、止损纪律、风险预算执行与恢复速度。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "equity_correlation_bucket",
        "label": "权益相关性",
        "description": "与权益市场的典型相关性水平。",
        "data_type": "single_select",
        "options": ["低相关", "中相关", "高相关", "负相关/危机对冲"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_risk",
        "display_order": 330,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "帮助判断基金在组合里的分散化价值。",
            "standard": "以持仓和历史表现为主，不用短窗口噪声替代长期判断。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "preferred_regime",
        "label": "适配环境",
        "description": "更容易发挥优势的市场环境，可多选。",
        "data_type": "multi_select",
        "options": ["低波震荡", "高波趋势", "流动性宽松", "流动性收紧", "单边上涨", "单边下跌", "商品趋势", "股指震荡"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_regime",
        "display_order": 340,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "帮助投委会理解“什么时候该用它”。",
            "standard": "只标长期更易发挥优势的环境，不标短期行情观点。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "weak_regime",
        "label": "脆弱环境",
        "description": "更容易失效或放大风险的环境，可多选。",
        "data_type": "multi_select",
        "options": ["高波反转", "流动性冲击", "无趋势震荡", "权益急跌后V形", "商品快速切换", "基差异常/挤仓"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_regime",
        "display_order": 350,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "记录基金最容易失效的环境，用于风控和仓位讨论。",
            "standard": "必须能被历史回撤或机制解释支撑。",
        },
        "required_for_monitoring": False,
    },
    {
        "attribute_key": "style_stability",
        "label": "风格稳定性",
        "description": "策略暴露和执行风格是否稳定。",
        "data_type": "single_select",
        "options": ["高", "中", "低"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_operational",
        "display_order": 360,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "监控产品是否偏离原始研究假设。",
            "standard": "结合持仓、换手、行业/因子暴露和沟通口径判断。",
        },
        "required_for_monitoring": True,
    },
    {
        "attribute_key": "transparency_quality",
        "label": "研究透明度",
        "description": "产品对外信息披露与可研究性质量。",
        "data_type": "single_select",
        "options": ["高", "中", "低"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
        "domain_code": "monitoring",
        "group_code": "monitoring_operational",
        "display_order": 370,
        "instrument_scope_json": ["fund", "etf"],
        "applicability_json": {},
        "rubric_json": {
            "summary": "衡量后续跟踪是否有足够材料支撑。",
            "standard": "看披露频率、口径一致性、访谈可得性和底层可验证程度。",
        },
        "required_for_monitoring": True,
    },
]

FIELD_REGISTRY = [
    {
        "field_key": "instrument_name",
        "label": "Name",
        "description": "Canonical instrument display name from the watchlist row read model.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "discrete",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.instrument_name",
        "default_width": 320,
        "default_visible": True,
    },
    {
        "field_key": "instrument_type",
        "label": "Instrument Type",
        "description": "Top-level instrument type resolved from shared identity.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.instrument_type",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "ticker_or_isin",
        "label": "Ticker / ISIN",
        "description": "Primary public identifier for the row.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "identifier",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "none",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["primary_identifier"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.ticker_or_isin",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "latest_quote",
        "label": "Latest Quote",
        "description": "Most recent point from the active quote series used by the detail quote view.",
        "category_code": "general",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "instrument_chart_read_model.series.latest_quote",
        "default_width": 130,
        "default_visible": False,
    },
    {
        "field_key": "latest_quote_date",
        "label": "Quote Date",
        "description": "As-of date for the most recent active quote series point.",
        "category_code": "general",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "instrument_chart_read_model.series.latest_quote_date",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_regime",
        "label": "公募/私募",
        "description": "Fund taxonomy root derived from the assigned fund taxonomy path.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.fund_regime",
        "default_width": 120,
        "default_visible": True,
    },
    {
        "field_key": "attr.fund_taxonomy_level_1",
        "label": "一级分类",
        "description": "First internal taxonomy branch after 公募/私募, derived from fund taxonomy.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_1",
        "default_width": 120,
        "default_visible": True,
    },
    {
        "field_key": "attr.fund_taxonomy_level_2",
        "label": "二级分类",
        "description": "Second internal taxonomy branch for deeper fund grouping.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_2",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "attr.fund_taxonomy_level_3",
        "label": "三级分类",
        "description": "Third internal taxonomy branch for deeper fund grouping.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_3",
        "default_width": 170,
        "default_visible": True,
    },
    {
        "field_key": "attr.fund_taxonomy_level_4",
        "label": "四级分类",
        "description": "Fourth internal taxonomy branch for leaf-level fund grouping.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_4",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_taxonomy_level_5",
        "label": "五级分类",
        "description": "Fifth internal taxonomy branch for variable-depth taxonomy branches.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_5",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_taxonomy_level_6",
        "label": "六级分类",
        "description": "Sixth internal taxonomy branch for variable-depth taxonomy branches.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.level_6",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_taxonomy_leaf",
        "label": "分类叶子",
        "description": "Leaf taxonomy label derived from the fund taxonomy path.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.leaf",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.fund_taxonomy_path",
        "label": "分类路径",
        "description": "Full fund taxonomy path derived from the taxonomy tree.",
        "category_code": "product_taxonomy",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_taxonomy_assignment"]},
        "source_domain": "taxonomy",
        "source_metric_code": "fund_taxonomy.derived.path",
        "default_width": 280,
        "default_visible": False,
    },
    {
        "field_key": "management_firm_name",
        "label": "Management Firm",
        "description": "Current manager / advisor firm.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.management_firm_name",
        "default_width": 220,
        "default_visible": False,
    },
    {
        "field_key": "instrument_class",
        "label": "Instrument Class",
        "description": "Top-level instrument class for group by and filtering.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_detail"]},
        "source_domain": "instrument_detail",
        "source_metric_code": "instrument_detail.metadata_json.instrument_class",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "aum",
        "label": "AUM",
        "description": "Current assets under management from the watchlist row read model.",
        "category_code": "basics",
        "data_type": "number",
        "formatter_code": "currency_compact",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.aum",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "price_chart_1m",
        "label": "Chart 1M",
        "description": "1-month chart from the current selected quote series.",
        "category_code": "performance_risk",
        "data_type": "sparkline",
        "formatter_code": "sparkline",
        "sort_mode": "none",
        "filter_mode": "none",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "instrument_chart_read_model.series",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "overall_rating",
        "label": "Overall Rating",
        "description": "Internal score-based rating derived from the current methodology.",
        "category_code": "ratings_analysis",
        "data_type": "integer",
        "formatter_code": "stars",
        "sort_mode": "numeric",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_score_snapshot"]},
        "source_domain": "score",
        "source_metric_code": "instrument_score_snapshot.overall_rating",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "analyst_stance",
        "label": "Analyst Stance",
        "description": "Current house view from the score snapshot.",
        "category_code": "ratings_analysis",
        "data_type": "string",
        "formatter_code": "badge",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_score_snapshot"]},
        "source_domain": "score",
        "source_metric_code": "instrument_score_snapshot.analyst_stance",
        "default_width": 160,
        "default_visible": True,
    },
    {
        "field_key": "return_ytd",
        "label": "YTD",
        "description": "Derived from canonical NAV facts.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_ytd",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_mtd",
        "label": "MTD",
        "description": "Month-to-date total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_mtd",
        "default_width": 120,
        "default_visible": True,
    },
    {
        "field_key": "return_1w",
        "label": "1W Return",
        "description": "1-week total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1w",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1m",
        "label": "1M",
        "description": "1-month total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1m",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1y",
        "label": "1Y",
        "description": "1-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1y",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "annualized_return",
        "label": "Ann.",
        "description": "Since-inception annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.annualized_return",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "return_3y",
        "label": "3Y",
        "description": "3-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_3y_annualized",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_5y",
        "label": "5Y",
        "description": "5-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_5y_annualized",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "max_drawdown",
        "label": "Max DD",
        "description": "Maximum drawdown from the active performance snapshot.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.max_drawdown",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "attr.current_drawdown",
        "label": "Current DD",
        "description": "Current drawdown from the latest NAV relative to the prior high watermark.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_risk_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.current_drawdown",
        "default_width": 120,
        "default_visible": False,
    },
    {
        "field_key": "volatility",
        "label": "Volatility",
        "description": "Risk snapshot volatility for the selected window.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.volatility",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "sharpe_ratio",
        "label": "Sharpe Ratio",
        "description": "Current risk-adjusted return metric.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf", "index"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.sharpe_ratio",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_group",
        "label": "Peer Group",
        "description": "Taxonomy-derived peer group used for peer percentile calculations.",
        "category_code": "performance_risk",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_group",
        "default_width": 220,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_sample_count",
        "label": "Peer Sample",
        "description": "Number of funds in the taxonomy peer sample.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_sample_count",
        "default_width": 120,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_overall_percentile",
        "label": "同类排名",
        "description": "Composite taxonomy peer percentile across return, risk, and risk-adjusted metrics. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_overall_percentile",
        "default_width": 170,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_percentile",
        "label": "Return Pctl",
        "description": "Average taxonomy peer percentile across available return metrics. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_risk_percentile",
        "label": "Risk Pctl",
        "description": "Average taxonomy peer percentile across available risk metrics. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_risk_percentile",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_risk_adjusted_percentile",
        "label": "Risk-Adj Pctl",
        "description": "Average taxonomy peer percentile across risk-adjusted metrics. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_risk_adjusted_percentile",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_1w_percentile",
        "label": "1W Return Pctl",
        "description": "1-week return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_1w_percentile",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_1m_percentile",
        "label": "1M Pctl",
        "description": "1-month return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_1m_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_ytd_percentile",
        "label": "YTD Pctl",
        "description": "Year-to-date return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_ytd_percentile",
        "default_width": 170,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_1y_percentile",
        "label": "1Y Pctl",
        "description": "1-year return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_1y_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_3y_percentile",
        "label": "3Y Pctl",
        "description": "3-year annualized return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_3y_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_return_5y_percentile",
        "label": "5Y Pctl",
        "description": "5-year annualized return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_return_5y_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_annualized_return_percentile",
        "label": "Ann. Pctl",
        "description": "Since-inception annualized return percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_annualized_return_percentile",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_volatility_percentile",
        "label": "Volatility Percentile",
        "description": "Volatility percentile within the taxonomy peer group. Lower volatility ranks better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_volatility_percentile",
        "default_width": 165,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_max_drawdown_percentile",
        "label": "Max DD Pctl",
        "description": "Maximum drawdown percentile within the taxonomy peer group. Shallower drawdown ranks better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_max_drawdown_percentile",
        "default_width": 185,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_sharpe_percentile",
        "label": "Sharpe Percentile",
        "description": "Sharpe ratio percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_sharpe_percentile",
        "default_width": 155,
        "default_visible": False,
    },
    {
        "field_key": "attr.peer_calmar_percentile",
        "label": "Calmar Percentile",
        "description": "Calmar ratio percentile within the taxonomy peer group. Higher is better.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["instrument_performance_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.attributes.peer_calmar_percentile",
        "default_width": 155,
        "default_visible": False,
    },
    {
        "field_key": "duration",
        "label": "Duration",
        "description": "Weighted effective duration derived from exposure analytics.",
        "category_code": "exposure",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_duration",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "avg_credit_rating",
        "label": "Avg Credit Rating",
        "description": "Exposure-weighted average credit quality.",
        "category_code": "exposure",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.avg_credit_rating",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "yield_to_worst",
        "label": "Yield To Worst",
        "description": "Exposure-weighted yield to worst derived from holdings analytics.",
        "category_code": "exposure",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_yield_to_worst",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "last_nav_date",
        "label": "Last Quote Date",
        "description": "Most recent selected quote-series date adopted for the instrument.",
        "category_code": "monitoring",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.last_nav_date",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "exposure_updated_at",
        "label": "Holdings Updated At",
        "description": "Latest holdings statement adoption time.",
        "category_code": "monitoring",
        "data_type": "datetime",
        "formatter_code": "datetime",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "instrument_scope_json": ["fund", "etf"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.exposure_updated_at",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "data_freshness_status",
        "label": "Freshness",
        "description": "System freshness status derived from the current read model.",
        "category_code": "monitoring",
        "data_type": "string",
        "formatter_code": "status",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "instrument_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.data_freshness_status",
        "default_width": 140,
        "default_visible": True,
    },
]


def _attribute_field_key(attribute_key: str) -> str:
    return f"attr.{attribute_key}"


ATTRIBUTE_FIELD_CATEGORY_BY_DOMAIN = {
    "overview": "basics",
    "research": "research_framework",
    "monitoring": "monitoring_assessment",
}


def build_attribute_field_definition(
    definition: dict[str, object],
) -> dict[str, object]:
    data_type = str(definition["data_type"])
    filter_mode = "multi_select"
    group_mode = "discrete"
    formatter_code = "text"
    sort_mode = "alpha"
    if data_type == "boolean":
        formatter_code = "boolean"
    elif data_type == "number":
        formatter_code = "decimal"
        filter_mode = "range"
        group_mode = "bucket"
        sort_mode = "numeric"
    elif data_type == "date":
        formatter_code = "date"
        filter_mode = "date_range"
        group_mode = "bucket"
        sort_mode = "date"
    elif data_type == "multi_select":
        formatter_code = "tags"

    return {
        "field_key": _attribute_field_key(str(definition["attribute_key"])),
        "label": str(definition["label"]),
        "description": (
            str(definition["description"])
            if definition.get("description") is not None
            else None
        ),
        "category_code": ATTRIBUTE_FIELD_CATEGORY_BY_DOMAIN.get(
            str(definition.get("domain_code") or "research"),
            "research_framework",
        ),
        "data_type": data_type,
        "formatter_code": formatter_code,
        "sort_mode": sort_mode,
        "filter_mode": filter_mode,
        "group_mode": group_mode if definition.get("is_groupable", True) else "none",
        "instrument_scope_json": [
            str(item)
            for item in definition.get("instrument_scope_json", ["fund", "etf"])
            if str(item).strip()
        ],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_attribute_value"]},
        "source_domain": "custom_attribute",
        "source_metric_code": f"instrument_attribute_value.{definition['attribute_key']}",
        "default_width": 160,
        "default_visible": bool(definition.get("default_visible", False)),
    }


def current_field_registry() -> list[dict[str, object]]:
    fields = deepcopy(FIELD_REGISTRY)
    fields.extend(
        build_attribute_field_definition(item)
        for item in INSTRUMENT_ATTRIBUTE_DEFINITIONS
        if item.get("is_view_column", True)
    )
    return fields
