from __future__ import annotations


def _seed(
    *,
    regime: str,
    vehicle: str,
    family: str,
    subtype: list[str],
    implementation: str,
    universe: list[str],
    alpha: list[str],
    volatility: str,
    drawdown: str,
    correlation: str,
    preferred: list[str],
    weak: list[str],
    stability: str,
    transparency: str,
) -> dict[str, object]:
    return {
        "fund_regime": regime,
        "fund_vehicle": vehicle,
        "strategy_family": family,
        "strategy_subtype": subtype,
        "implementation_style": implementation,
        "trading_universe": universe,
        "alpha_source": alpha,
        "volatility_bucket": volatility,
        "drawdown_control": drawdown,
        "equity_correlation_bucket": correlation,
        "preferred_regime": preferred,
        "weak_regime": weak,
        "style_stability": stability,
        "transparency_quality": transparency,
    }


EXAMPLE_FUND_ATTRIBUTE_VALUES: dict[str, dict[str, object]] = {
    "AA": _seed(
        regime="公募",
        vehicle="场外开放式",
        family="其他",
        subtype=["股票多头"],
        implementation="主观",
        universe=["A股"],
        alpha=["选股Alpha"],
        volatility="中波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="低",
        transparency="低",
    ),
    "AAA": _seed(
        regime="公募",
        vehicle="场外开放式",
        family="其他",
        subtype=["股票多头"],
        implementation="主观",
        universe=["A股"],
        alpha=["选股Alpha"],
        volatility="中波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="低",
        transparency="低",
    ),
    "TEST": _seed(
        regime="公募",
        vehicle="场外开放式",
        family="其他",
        subtype=["股票多头"],
        implementation="主观",
        universe=["A股"],
        alpha=["选股Alpha"],
        volatility="中波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="低",
        transparency="低",
    ),
    "fund-us-agg": _seed(
        regime="公募",
        vehicle="ETF",
        family="被动指数",
        subtype=["债券指数"],
        implementation="被动规则",
        universe=["债券"],
        alpha=["指数复制"],
        volatility="低波",
        drawdown="强",
        correlation="低相关",
        preferred=["低波震荡", "流动性宽松"],
        weak=["流动性冲击"],
        stability="高",
        transparency="高",
    ),
    "cloz": _seed(
        regime="公募",
        vehicle="ETF",
        family="债券策略",
        subtype=["信用债"],
        implementation="被动规则",
        universe=["债券"],
        alpha=["Carry/票息"],
        volatility="中波",
        drawdown="中",
        correlation="低相关",
        preferred=["低波震荡", "流动性宽松"],
        weak=["流动性冲击"],
        stability="高",
        transparency="高",
    ),
    "fax": _seed(
        regime="公募",
        vehicle="封闭式",
        family="债券策略",
        subtype=["信用债", "QDII"],
        implementation="主观",
        universe=["债券"],
        alpha=["Carry/票息"],
        volatility="低波",
        drawdown="强",
        correlation="低相关",
        preferred=["低波震荡", "流动性宽松"],
        weak=["流动性冲击"],
        stability="高",
        transparency="高",
    ),
    "new-asia-income": _seed(
        regime="公募",
        vehicle="场外开放式",
        family="债券策略",
        subtype=["信用债", "QDII"],
        implementation="主观",
        universe=["债券"],
        alpha=["Carry/票息"],
        volatility="低波",
        drawdown="强",
        correlation="低相关",
        preferred=["低波震荡", "流动性宽松"],
        weak=["流动性冲击"],
        stability="中",
        transparency="高",
    ),
    "bosera-cb-etf": _seed(
        regime="公募",
        vehicle="ETF",
        family="被动指数",
        subtype=["债券指数", "可转债策略"],
        implementation="被动规则",
        universe=["可转债"],
        alpha=["指数复制"],
        volatility="中波",
        drawdown="中",
        correlation="中相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="高",
        transparency="高",
    ),
    "gf-hkinnodrug": _seed(
        regime="公募",
        vehicle="ETF",
        family="被动指数",
        subtype=["行业主题指数", "QDII"],
        implementation="被动规则",
        universe=["港股"],
        alpha=["指数复制", "主题/风格暴露"],
        volatility="高波",
        drawdown="弱",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="高",
        transparency="高",
    ),
    "efund-cnint50": _seed(
        regime="公募",
        vehicle="ETF",
        family="被动指数",
        subtype=["行业主题指数", "QDII"],
        implementation="被动规则",
        universe=["港股", "美股"],
        alpha=["指数复制", "主题/风格暴露"],
        volatility="高波",
        drawdown="弱",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="高",
        transparency="高",
    ),
    "hstech": _seed(
        regime="公募",
        vehicle="ETF",
        family="被动指数",
        subtype=["行业主题指数"],
        implementation="被动规则",
        universe=["港股"],
        alpha=["指数复制", "主题/风格暴露"],
        volatility="高波",
        drawdown="弱",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="高",
        transparency="高",
    ),
    "nasdaq100": _seed(
        regime="公募",
        vehicle="ETF",
        family="被动指数",
        subtype=["宽基指数", "QDII"],
        implementation="被动规则",
        universe=["美股"],
        alpha=["指数复制"],
        volatility="高波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="高",
        transparency="高",
    ),
    "dacheng-gx-c": _seed(
        regime="公募",
        vehicle="场外开放式",
        family="主动权益",
        subtype=["股票多头"],
        implementation="主观",
        universe=["A股"],
        alpha=["选股Alpha"],
        volatility="中波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="中",
        transparency="高",
    ),
    "cmb-quant-c": _seed(
        regime="公募",
        vehicle="场外开放式",
        family="主动权益",
        subtype=["股票多头", "量化选股"],
        implementation="量化",
        universe=["A股"],
        alpha=["选股Alpha", "贝塔增强"],
        volatility="高波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="高",
        transparency="高",
    ),
    "gj-multifactor-c": _seed(
        regime="公募",
        vehicle="场外开放式",
        family="主动权益",
        subtype=["量化选股", "指数增强"],
        implementation="量化",
        universe=["A股"],
        alpha=["选股Alpha", "贝塔增强"],
        volatility="高波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="高",
        transparency="高",
    ),
    "sxv264": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="多策略",
        subtype=["复合多策略"],
        implementation="主观+量化",
        universe=["A股", "债券"],
        alpha=["选股Alpha", "Carry/票息"],
        volatility="低波",
        drawdown="强",
        correlation="中相关",
        preferred=["低波震荡", "流动性宽松"],
        weak=["高波反转", "流动性冲击"],
        stability="中",
        transparency="中",
    ),
    "savf63": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="债券策略",
        subtype=["信用债"],
        implementation="主观+量化",
        universe=["债券"],
        alpha=["Carry/票息"],
        volatility="低波",
        drawdown="强",
        correlation="低相关",
        preferred=["低波震荡", "流动性宽松"],
        weak=["流动性冲击"],
        stability="中",
        transparency="中",
    ),
    "sazb60": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="多策略",
        subtype=["复合多策略"],
        implementation="主观",
        universe=["A股", "债券"],
        alpha=["选股Alpha", "贝塔增强"],
        volatility="高波",
        drawdown="中",
        correlation="中相关",
        preferred=["流动性宽松", "单边上涨"],
        weak=["高波反转", "流动性冲击"],
        stability="中",
        transparency="中",
    ),
    "sample-yungu-1": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="多策略",
        subtype=["复合多策略"],
        implementation="主观+量化",
        universe=["A股", "债券"],
        alpha=["选股Alpha", "Carry/票息"],
        volatility="低波",
        drawdown="强",
        correlation="中相关",
        preferred=["低波震荡", "流动性宽松"],
        weak=["高波反转", "流动性冲击"],
        stability="中",
        transparency="中",
    ),
    "sample-sanang-jinlu-1": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="股票对冲",
        subtype=["市场中性", "统计套利"],
        implementation="量化",
        universe=["A股", "股指期货"],
        alpha=["选股Alpha", "高频/微观结构"],
        volatility="中波",
        drawdown="强",
        correlation="低相关",
        preferred=["低波震荡", "股指震荡"],
        weak=["高波反转", "流动性冲击"],
        stability="高",
        transparency="中",
    ),
    "svk343": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="股票对冲",
        subtype=["市场中性", "统计套利"],
        implementation="量化",
        universe=["A股", "股指期货"],
        alpha=["选股Alpha", "高频/微观结构"],
        volatility="中波",
        drawdown="强",
        correlation="低相关",
        preferred=["低波震荡", "股指震荡"],
        weak=["高波反转", "流动性冲击"],
        stability="高",
        transparency="中",
    ),
    "anm38b": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="股票对冲",
        subtype=["市场中性", "统计套利"],
        implementation="量化",
        universe=["A股", "股指期货"],
        alpha=["选股Alpha", "高频/微观结构"],
        volatility="低波",
        drawdown="强",
        correlation="低相关",
        preferred=["低波震荡", "股指震荡"],
        weak=["高波反转", "流动性冲击"],
        stability="高",
        transparency="中",
    ),
    "b3935b": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="股票对冲",
        subtype=["市场中性"],
        implementation="主观+量化",
        universe=["A股", "股指期货"],
        alpha=["选股Alpha"],
        volatility="中波",
        drawdown="中",
        correlation="低相关",
        preferred=["低波震荡", "股指震荡"],
        weak=["高波反转", "流动性冲击"],
        stability="中",
        transparency="中",
    ),
    "sample-gtja-cta-2": _seed(
        regime="私募",
        vehicle="集合资管计划",
        family="CTA",
        subtype=["商品CTA", "金融CTA", "趋势跟踪"],
        implementation="量化",
        universe=["商品期货", "股指期货", "国债期货"],
        alpha=["趋势跟踪"],
        volatility="中波",
        drawdown="中",
        correlation="低相关",
        preferred=["高波趋势", "商品趋势"],
        weak=["无趋势震荡", "商品快速切换"],
        stability="高",
        transparency="中",
    ),
    "sbcj69": _seed(
        regime="私募",
        vehicle="集合资管计划",
        family="CTA",
        subtype=["商品CTA", "金融CTA", "趋势跟踪"],
        implementation="量化",
        universe=["商品期货", "股指期货", "国债期货"],
        alpha=["趋势跟踪"],
        volatility="中波",
        drawdown="中",
        correlation="低相关",
        preferred=["高波趋势", "商品趋势"],
        weak=["无趋势震荡", "商品快速切换"],
        stability="高",
        transparency="中",
    ),
    "zb945a": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="主动权益",
        subtype=["股票多头"],
        implementation="主观",
        universe=["A股"],
        alpha=["选股Alpha"],
        volatility="中波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="中",
        transparency="中",
    ),
    "anz73a": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="主动权益",
        subtype=["股票多头"],
        implementation="主观",
        universe=["A股"],
        alpha=["选股Alpha"],
        volatility="低波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="中",
        transparency="中",
    ),
    "are77a": _seed(
        regime="私募",
        vehicle="场外开放式",
        family="主动权益",
        subtype=["股票多头"],
        implementation="主观",
        universe=["A股"],
        alpha=["选股Alpha"],
        volatility="中波",
        drawdown="中",
        correlation="高相关",
        preferred=["单边上涨", "流动性宽松"],
        weak=["流动性冲击", "权益急跌后V形"],
        stability="中",
        transparency="中",
    ),
}


def get_example_fund_attributes(asset_id: str) -> dict[str, object] | None:
    return EXAMPLE_FUND_ATTRIBUTE_VALUES.get(asset_id)
