from __future__ import annotations

from copy import deepcopy


FIELD_CATEGORIES = [
    {"category_code": "general", "label": "General", "display_order": 1},
    {"category_code": "basics", "label": "Basics", "display_order": 2},
    {"category_code": "fees_terms", "label": "Fees & Terms", "display_order": 3},
    {
        "category_code": "performance_risk",
        "label": "Performance & Risk",
        "display_order": 4,
    },
    {"category_code": "exposure", "label": "Exposure", "display_order": 5},
    {
        "category_code": "ratings_analysis",
        "label": "Ratings & Analysis",
        "display_order": 6,
    },
    {"category_code": "monitoring", "label": "Monitoring", "display_order": 7},
    {
        "category_code": "custom_attributes",
        "label": "Custom Attributes",
        "display_order": 8,
    },
]

INSTRUMENT_ATTRIBUTE_DEFINITIONS = [
    {
        "attribute_key": "coverage_status",
        "label": "Coverage Status",
        "description": "Research status such as invested, focus, or watch.",
        "data_type": "single_select",
        "options": ["Invested", "Focus", "Watch", "Archived"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": True,
    },
    {
        "attribute_key": "focus_bucket",
        "label": "Focus Bucket",
        "description": "Internal attention bucket for near-term review priority.",
        "data_type": "single_select",
        "options": ["Tier 1", "Tier 2", "Tier 3"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "is_invested",
        "label": "Currently Invested",
        "description": "Whether the instrument is currently in the invested book.",
        "data_type": "boolean",
        "options": [],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "fund_regime",
        "label": "基金属性",
        "description": "公募还是私募，用于先分产品身份。",
        "data_type": "single_select",
        "options": ["公募", "私募"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "fund_vehicle",
        "label": "产品形态",
        "description": "ETF、场外开放式或资管计划等载体形态。",
        "data_type": "single_select",
        "options": ["ETF", "场外开放式", "LOF/场内开放式", "封闭式", "集合资管计划", "其他"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "strategy_family",
        "label": "策略大类",
        "description": "基金的主策略身份，用于第一层快速筛选。",
        "data_type": "single_select",
        "options": ["主动权益", "被动指数", "股票对冲", "CTA", "套利", "多策略", "债券策略", "宏观", "FOF/MOM", "期权/波动率", "其他"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "strategy_subtype",
        "label": "策略细分",
        "description": "更具体的实现类型，可多选。",
        "data_type": "multi_select",
        "options": [
            "市场中性",
            "指数增强",
            "股票多头",
            "量化选股",
            "宽基指数",
            "行业主题指数",
            "债券指数",
            "QDII",
            "商品CTA",
            "金融CTA",
            "趋势跟踪",
            "短周期CTA",
            "跨期套利",
            "跨品种套利",
            "统计套利",
            "期权套利",
            "可转债套利",
            "可转债策略",
            "宏观择时",
            "信用债",
            "复合多策略",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "implementation_style",
        "label": "实现方式",
        "description": "主观、量化或混合实现。",
        "data_type": "single_select",
        "options": ["主观", "量化", "主观+量化", "被动规则"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "trading_universe",
        "label": "交易市场/品种",
        "description": "主要交易的底层市场与工具，可多选。",
        "data_type": "multi_select",
        "options": ["A股", "港股", "美股", "股指期货", "国债期货", "商品期货", "期权", "可转债", "债券"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "alpha_source",
        "label": "主要收益来源",
        "description": "基金最核心的收益引擎，可多选。",
        "data_type": "multi_select",
        "options": [
            "选股Alpha",
            "趋势跟踪",
            "期限结构",
            "价差收敛",
            "波动率交易",
            "事件驱动",
            "贝塔增强",
            "指数复制",
            "主题/风格暴露",
            "高频/微观结构",
            "宏观择时",
            "Carry/票息",
        ],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "volatility_bucket",
        "label": "波动分层",
        "description": "产品的典型波动水平。",
        "data_type": "single_select",
        "options": ["低波", "中波", "高波"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "drawdown_control",
        "label": "回撤控制",
        "description": "产品在压力阶段的回撤管理能力。",
        "data_type": "single_select",
        "options": ["强", "中", "弱"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "equity_correlation_bucket",
        "label": "权益相关性",
        "description": "与权益市场的典型相关性水平。",
        "data_type": "single_select",
        "options": ["低相关", "中相关", "高相关", "负相关/危机对冲"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "preferred_regime",
        "label": "适配环境",
        "description": "更容易发挥优势的市场环境，可多选。",
        "data_type": "multi_select",
        "options": ["低波震荡", "高波趋势", "流动性宽松", "流动性收紧", "单边上涨", "单边下跌", "商品趋势", "股指震荡"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "weak_regime",
        "label": "脆弱环境",
        "description": "更容易失效或放大风险的环境，可多选。",
        "data_type": "multi_select",
        "options": ["高波反转", "流动性冲击", "无趋势震荡", "权益急跌后V形", "商品快速切换", "基差异常/挤仓"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "style_stability",
        "label": "风格稳定性",
        "description": "策略暴露和执行风格是否稳定。",
        "data_type": "single_select",
        "options": ["高", "中", "低"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
    {
        "attribute_key": "transparency_quality",
        "label": "研究透明度",
        "description": "产品对外信息披露与可研究性质量。",
        "data_type": "single_select",
        "options": ["高", "中", "低"],
        "is_groupable": True,
        "is_filterable": True,
        "is_view_column": True,
        "default_visible": False,
    },
]

FIELD_REGISTRY = [
    {
        "field_key": "asset_name",
        "label": "Name",
        "description": "Canonical instrument display name from the watchlist row read model.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "discrete",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.asset_name",
        "default_width": 320,
        "default_visible": True,
    },
    {
        "field_key": "asset_type",
        "label": "Asset Type",
        "description": "Top-level instrument type resolved from shared identity.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.asset_type",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "ticker_or_isin",
        "label": "Ticker / ISIN",
        "description": "Primary public identifier for the row.",
        "category_code": "general",
        "data_type": "string",
        "formatter_code": "identifier",
        "sort_mode": "alpha",
        "filter_mode": "text",
        "group_mode": "none",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["primary_identifier"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.ticker_or_isin",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "latest_quote",
        "label": "Latest Quote",
        "description": "Most recent point from the active quote series used by the detail quote view.",
        "category_code": "general",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["asset_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "asset_chart_read_model.series.latest_quote",
        "default_width": 130,
        "default_visible": False,
    },
    {
        "field_key": "latest_quote_date",
        "label": "Quote Date",
        "description": "As-of date for the most recent active quote series point.",
        "category_code": "general",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["asset_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "asset_chart_read_model.series.latest_quote_date",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "management_firm_name",
        "label": "Management Firm",
        "description": "Current manager / advisor firm.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.management_firm_name",
        "default_width": 220,
        "default_visible": False,
    },
    {
        "field_key": "category_name",
        "label": "Category",
        "description": "Peer group/category used for ranking and comparison.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.category_name",
        "default_width": 240,
        "default_visible": True,
    },
    {
        "field_key": "asset_class",
        "label": "Asset Class",
        "description": "Top-level asset class for group by and filtering.",
        "category_code": "basics",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["asset_detail"]},
        "source_domain": "asset_detail",
        "source_metric_code": "asset_detail.metadata_json.asset_class",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "aum",
        "label": "AUM",
        "description": "Current assets under management from the watchlist row read model.",
        "category_code": "basics",
        "data_type": "number",
        "formatter_code": "currency_compact",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.aum",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "price_chart_1m",
        "label": "Price Chart",
        "description": "1-month NAV spark chart from the current chart read model.",
        "category_code": "performance_risk",
        "data_type": "sparkline",
        "formatter_code": "sparkline",
        "sort_mode": "none",
        "filter_mode": "none",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["asset_chart_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "asset_chart_read_model.series",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "overall_rating",
        "label": "Overall Rating",
        "description": "Internal score-based rating derived from the current methodology.",
        "category_code": "ratings_analysis",
        "data_type": "integer",
        "formatter_code": "stars",
        "sort_mode": "numeric",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["asset_score_snapshot"]},
        "source_domain": "score",
        "source_metric_code": "asset_score_snapshot.overall_rating",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "analyst_stance",
        "label": "Analyst Stance",
        "description": "Current house view from the score snapshot.",
        "category_code": "ratings_analysis",
        "data_type": "string",
        "formatter_code": "badge",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["asset_score_snapshot"]},
        "source_domain": "score",
        "source_metric_code": "asset_score_snapshot.analyst_stance",
        "default_width": 160,
        "default_visible": True,
    },
    {
        "field_key": "return_ytd",
        "label": "Total Return (YTD)",
        "description": "Derived from canonical NAV facts.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_ytd",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1w",
        "label": "Total Return (1W)",
        "description": "1-week total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1w",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1m",
        "label": "Total Return (1M)",
        "description": "1-month total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1m",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_1y",
        "label": "Total Return (1Y)",
        "description": "1-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_1y",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "annualized_return",
        "label": "Annualized Return",
        "description": "Since-inception annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.annualized_return",
        "default_width": 160,
        "default_visible": False,
    },
    {
        "field_key": "return_3y",
        "label": "Total Return (3Y)",
        "description": "3-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_3y_annualized",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "return_5y",
        "label": "Total Return (5Y)",
        "description": "5-year annualized total return.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.return_5y_annualized",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "max_drawdown",
        "label": "Max Drawdown",
        "description": "Maximum drawdown from the active performance snapshot.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["performance_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "performance_snapshot.max_drawdown",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "volatility",
        "label": "Volatility",
        "description": "Risk snapshot volatility for the selected window.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.volatility",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "sharpe_ratio",
        "label": "Sharpe Ratio",
        "description": "Current risk-adjusted return metric.",
        "category_code": "performance_risk",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["risk_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "risk_snapshot.sharpe_ratio",
        "default_width": 140,
        "default_visible": False,
    },
    {
        "field_key": "duration",
        "label": "Duration",
        "description": "Weighted effective duration derived from exposure analytics.",
        "category_code": "exposure",
        "data_type": "number",
        "formatter_code": "decimal",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_duration",
        "default_width": 140,
        "default_visible": True,
    },
    {
        "field_key": "avg_credit_rating",
        "label": "Avg Credit Rating",
        "description": "Exposure-weighted average credit quality.",
        "category_code": "exposure",
        "data_type": "string",
        "formatter_code": "text",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.avg_credit_rating",
        "default_width": 150,
        "default_visible": True,
    },
    {
        "field_key": "yield_to_worst",
        "label": "Yield To Worst",
        "description": "Exposure-weighted yield to worst derived from holdings analytics.",
        "category_code": "exposure",
        "data_type": "number",
        "formatter_code": "percent",
        "sort_mode": "numeric",
        "filter_mode": "range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["exposure_analytics_snapshot"]},
        "source_domain": "snapshot",
        "source_metric_code": "exposure_analytics_snapshot.weighted_yield_to_worst",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "last_nav_date",
        "label": "Last NAV Date",
        "description": "Most recent canonical NAV fact adopted for the asset.",
        "category_code": "monitoring",
        "data_type": "date",
        "formatter_code": "date",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.last_nav_date",
        "default_width": 150,
        "default_visible": False,
    },
    {
        "field_key": "exposure_updated_at",
        "label": "Holdings Updated At",
        "description": "Latest holdings statement adoption time.",
        "category_code": "monitoring",
        "data_type": "datetime",
        "formatter_code": "datetime",
        "sort_mode": "date",
        "filter_mode": "date_range",
        "group_mode": "bucket",
        "asset_scope_json": ["fund"],
        "product_scope_json": ["mutual_fund", "cef", "etf"],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.exposure_updated_at",
        "default_width": 180,
        "default_visible": False,
    },
    {
        "field_key": "data_freshness_status",
        "label": "Freshness",
        "description": "System freshness status derived from the current read model.",
        "category_code": "monitoring",
        "data_type": "string",
        "formatter_code": "status",
        "sort_mode": "alpha",
        "filter_mode": "multi_select",
        "group_mode": "discrete",
        "asset_scope_json": [],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["watchlist_row_read_model"]},
        "source_domain": "read_model",
        "source_metric_code": "watchlist_row_read_model.data_freshness_status",
        "default_width": 140,
        "default_visible": True,
    },
]


def _attribute_field_key(attribute_key: str) -> str:
    return f"attr.{attribute_key}"


def build_attribute_field_definition(
    definition: dict[str, object],
) -> dict[str, object]:
    data_type = str(definition["data_type"])
    filter_mode = "multi_select"
    group_mode = "discrete"
    formatter_code = "text"
    sort_mode = "alpha"
    if data_type == "boolean":
        formatter_code = "boolean"
    elif data_type == "number":
        formatter_code = "decimal"
        filter_mode = "range"
        group_mode = "bucket"
        sort_mode = "numeric"
    elif data_type == "date":
        formatter_code = "date"
        filter_mode = "date_range"
        group_mode = "bucket"
        sort_mode = "date"
    elif data_type == "multi_select":
        formatter_code = "tags"

    return {
        "field_key": _attribute_field_key(str(definition["attribute_key"])),
        "label": str(definition["label"]),
        "description": (
            str(definition["description"])
            if definition.get("description") is not None
            else None
        ),
        "category_code": "custom_attributes",
        "data_type": data_type,
        "formatter_code": formatter_code,
        "sort_mode": sort_mode,
        "filter_mode": filter_mode,
        "group_mode": group_mode if definition.get("is_groupable", True) else "none",
        "asset_scope_json": ["fund"],
        "product_scope_json": [],
        "availability_rule_json": {"requires": ["instrument_attribute_value"]},
        "source_domain": "custom_attribute",
        "source_metric_code": f"instrument_attribute_value.{definition['attribute_key']}",
        "default_width": 160,
        "default_visible": bool(definition.get("default_visible", False)),
    }


def current_field_registry() -> list[dict[str, object]]:
    fields = deepcopy(FIELD_REGISTRY)
    fields.extend(
        build_attribute_field_definition(item)
        for item in INSTRUMENT_ATTRIBUTE_DEFINITIONS
        if item.get("is_view_column", True)
    )
    return fields
