"""Public façade for the exact, manifest-driven Portfolio Daily ledger.

Implementation is split into immutable input contracts, immutable state/evidence
records, and the single-pass replay engine.  Importing from this façade keeps
call sites independent of that internal layout without preserving any legacy
float-ledger behavior.
"""

from portfolio_app.calculations.portfolio_daily.ledger_contracts import (
    BuyEvent,
    CashTransferEvent,
    CostBasisMethod,
    DividendReinvestmentEvent,
    ExpenseEvent,
    ExpenseKind,
    ExternalCashFlowEvent,
    ExternalFlowKind,
    ExternalFlowTiming,
    FactLineage,
    FxConversionEvent,
    FxRateConvention,
    IncomeEvent,
    IncomeKind,
    LEDGER_FACT_SCALES,
    LedgerContractError,
    LedgerFactKind,
    LedgerReasonCode,
    MaturityRedemptionEvent,
    OpeningCashEvent,
    OpeningPositionEvent,
    PositionTransferEvent,
    ReturnOfCapitalEvent,
    SellEvent,
    SplitEvent,
    quantize_ledger_fact,
)
from portfolio_app.calculations.portfolio_daily.ledger_engine import (
    replay_daily_ledger,
    replay_ledger_series,
)
from portfolio_app.calculations.portfolio_daily.ledger_state import (
    BaseCoverageStatus,
    CashBalance,
    DailyLedgerResult,
    DailyLedgerSnapshot,
    DailyLedgerState,
    DividendReinvestmentEvidence,
    FxConversionEvidence,
    LEDGER_TOTAL_EFFECT_FIELDS,
    LEDGER_TOTAL_FIELDS,
    LedgerEffect,
    LedgerEffectKind,
    LedgerSeriesResult,
    LedgerStatus,
    LedgerTotals,
    LotDisposition,
    OpeningAnchorEvidence,
    PendingComponentKind,
    PendingSettlement,
    PriceEvidenceStatus,
    PositionLot,
    PositionState,
)


__all__ = [
    "BaseCoverageStatus",
    "BuyEvent",
    "CashBalance",
    "CashTransferEvent",
    "CostBasisMethod",
    "DailyLedgerResult",
    "DailyLedgerSnapshot",
    "DailyLedgerState",
    "DividendReinvestmentEvent",
    "DividendReinvestmentEvidence",
    "ExpenseEvent",
    "ExpenseKind",
    "ExternalCashFlowEvent",
    "ExternalFlowKind",
    "ExternalFlowTiming",
    "FactLineage",
    "FxConversionEvent",
    "FxConversionEvidence",
    "FxRateConvention",
    "IncomeEvent",
    "IncomeKind",
    "LEDGER_FACT_SCALES",
    "LEDGER_TOTAL_EFFECT_FIELDS",
    "LEDGER_TOTAL_FIELDS",
    "LedgerContractError",
    "LedgerEffect",
    "LedgerEffectKind",
    "LedgerFactKind",
    "LedgerReasonCode",
    "LedgerSeriesResult",
    "LedgerStatus",
    "LedgerTotals",
    "LotDisposition",
    "MaturityRedemptionEvent",
    "OpeningAnchorEvidence",
    "OpeningCashEvent",
    "OpeningPositionEvent",
    "PendingComponentKind",
    "PendingSettlement",
    "PriceEvidenceStatus",
    "PositionLot",
    "PositionState",
    "PositionTransferEvent",
    "ReturnOfCapitalEvent",
    "SellEvent",
    "SplitEvent",
    "quantize_ledger_fact",
    "replay_daily_ledger",
    "replay_ledger_series",
]
