"""Frozen cross-market taxonomy and peer-dimension contract for migration 0047."""

from __future__ import annotations

TAXONOMY_NODE_ROWS = [{'node_id': 'fund-public-equity',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '权益基金',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 1,
  'is_leaf': False,
  'path_labels_json': ['权益基金'],
  'path_node_ids_json': ['fund-public-equity']},
 {'node_id': 'fund-public-equity-active',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '主动权益',
  'parent_node_id': 'fund-public-equity',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['权益基金', '主动权益'],
  'path_node_ids_json': ['fund-public-equity', 'fund-public-equity-active']},
 {'node_id': 'fund-public-equity-index',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '指数权益',
  'parent_node_id': 'fund-public-equity',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['权益基金', '指数权益'],
  'path_node_ids_json': ['fund-public-equity', 'fund-public-equity-index']},
 {'node_id': 'fund-public-equity-sector',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '行业权益',
  'parent_node_id': 'fund-public-equity',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['权益基金', '行业权益'],
  'path_node_ids_json': ['fund-public-equity', 'fund-public-equity-sector']},
 {'node_id': 'fund-public-equity-theme',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '主题权益',
  'parent_node_id': 'fund-public-equity',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['权益基金', '主题权益'],
  'path_node_ids_json': ['fund-public-equity', 'fund-public-equity-theme']},
 {'node_id': 'fund-public-equity-long-short',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '权益多空',
  'parent_node_id': 'fund-public-equity',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['权益基金', '权益多空'],
  'path_node_ids_json': ['fund-public-equity', 'fund-public-equity-long-short']},
 {'node_id': 'fund-public-fixed-income',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '固定收益基金',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 2,
  'is_leaf': False,
  'path_labels_json': ['固定收益基金'],
  'path_node_ids_json': ['fund-public-fixed-income']},
 {'node_id': 'fund-public-fixed-income-government',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '政府债',
  'parent_node_id': 'fund-public-fixed-income',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['固定收益基金', '政府债'],
  'path_node_ids_json': ['fund-public-fixed-income', 'fund-public-fixed-income-government']},
 {'node_id': 'fund-public-fixed-income-investment-grade',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '投资级信用',
  'parent_node_id': 'fund-public-fixed-income',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['固定收益基金', '投资级信用'],
  'path_node_ids_json': ['fund-public-fixed-income', 'fund-public-fixed-income-investment-grade']},
 {'node_id': 'fund-public-fixed-income-high-yield',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '高收益债',
  'parent_node_id': 'fund-public-fixed-income',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['固定收益基金', '高收益债'],
  'path_node_ids_json': ['fund-public-fixed-income', 'fund-public-fixed-income-high-yield']},
 {'node_id': 'fund-public-fixed-income-aggregate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '综合债券',
  'parent_node_id': 'fund-public-fixed-income',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['固定收益基金', '综合债券'],
  'path_node_ids_json': ['fund-public-fixed-income', 'fund-public-fixed-income-aggregate']},
 {'node_id': 'fund-public-fixed-income-short-duration',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '短久期',
  'parent_node_id': 'fund-public-fixed-income',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['固定收益基金', '短久期'],
  'path_node_ids_json': ['fund-public-fixed-income', 'fund-public-fixed-income-short-duration']},
 {'node_id': 'fund-public-fixed-income-convertible',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '可转债',
  'parent_node_id': 'fund-public-fixed-income',
  'level_index': 2,
  'display_order': 6,
  'is_leaf': True,
  'path_labels_json': ['固定收益基金', '可转债'],
  'path_node_ids_json': ['fund-public-fixed-income', 'fund-public-fixed-income-convertible']},
 {'node_id': 'fund-public-fixed-income-index',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '债券指数',
  'parent_node_id': 'fund-public-fixed-income',
  'level_index': 2,
  'display_order': 7,
  'is_leaf': True,
  'path_labels_json': ['固定收益基金', '债券指数'],
  'path_node_ids_json': ['fund-public-fixed-income', 'fund-public-fixed-income-index']},
 {'node_id': 'fund-public-allocation',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '配置基金',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 3,
  'is_leaf': False,
  'path_labels_json': ['配置基金'],
  'path_node_ids_json': ['fund-public-allocation']},
 {'node_id': 'fund-public-allocation-equity-biased',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '偏股配置',
  'parent_node_id': 'fund-public-allocation',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['配置基金', '偏股配置'],
  'path_node_ids_json': ['fund-public-allocation', 'fund-public-allocation-equity-biased']},
 {'node_id': 'fund-public-allocation-balanced',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '均衡配置',
  'parent_node_id': 'fund-public-allocation',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['配置基金', '均衡配置'],
  'path_node_ids_json': ['fund-public-allocation', 'fund-public-allocation-balanced']},
 {'node_id': 'fund-public-allocation-bond-biased',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '偏债配置',
  'parent_node_id': 'fund-public-allocation',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['配置基金', '偏债配置'],
  'path_node_ids_json': ['fund-public-allocation', 'fund-public-allocation-bond-biased']},
 {'node_id': 'fund-public-allocation-flexible',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '灵活配置',
  'parent_node_id': 'fund-public-allocation',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['配置基金', '灵活配置'],
  'path_node_ids_json': ['fund-public-allocation', 'fund-public-allocation-flexible']},
 {'node_id': 'fund-public-allocation-target',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '目标日期 / 目标风险',
  'parent_node_id': 'fund-public-allocation',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['配置基金', '目标日期 / 目标风险'],
  'path_node_ids_json': ['fund-public-allocation', 'fund-public-allocation-target']},
 {'node_id': 'fund-public-alternative',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '另类策略基金',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 4,
  'is_leaf': False,
  'path_labels_json': ['另类策略基金'],
  'path_node_ids_json': ['fund-public-alternative']},
 {'node_id': 'fund-public-alternative-market-neutral',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '市场中性',
  'parent_node_id': 'fund-public-alternative',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['另类策略基金', '市场中性'],
  'path_node_ids_json': ['fund-public-alternative', 'fund-public-alternative-market-neutral']},
 {'node_id': 'fund-public-alternative-managed-futures',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '管理期货',
  'parent_node_id': 'fund-public-alternative',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['另类策略基金', '管理期货'],
  'path_node_ids_json': ['fund-public-alternative', 'fund-public-alternative-managed-futures']},
 {'node_id': 'fund-public-alternative-macro',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '宏观策略',
  'parent_node_id': 'fund-public-alternative',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['另类策略基金', '宏观策略'],
  'path_node_ids_json': ['fund-public-alternative', 'fund-public-alternative-macro']},
 {'node_id': 'fund-public-alternative-event-driven',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '事件驱动',
  'parent_node_id': 'fund-public-alternative',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['另类策略基金', '事件驱动'],
  'path_node_ids_json': ['fund-public-alternative', 'fund-public-alternative-event-driven']},
 {'node_id': 'fund-public-alternative-relative-value',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '相对价值',
  'parent_node_id': 'fund-public-alternative',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['另类策略基金', '相对价值'],
  'path_node_ids_json': ['fund-public-alternative', 'fund-public-alternative-relative-value']},
 {'node_id': 'fund-public-alternative-multi-strategy',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '另类多策略',
  'parent_node_id': 'fund-public-alternative',
  'level_index': 2,
  'display_order': 6,
  'is_leaf': True,
  'path_labels_json': ['另类策略基金', '另类多策略'],
  'path_node_ids_json': ['fund-public-alternative', 'fund-public-alternative-multi-strategy']},
 {'node_id': 'fund-public-commodity',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '商品型',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 5,
  'is_leaf': False,
  'path_labels_json': ['商品型'],
  'path_node_ids_json': ['fund-public-commodity']},
 {'node_id': 'fund-public-commodity-precious-metals',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '贵金属基金',
  'parent_node_id': 'fund-public-commodity',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['商品型', '贵金属基金'],
  'path_node_ids_json': ['fund-public-commodity', 'fund-public-commodity-precious-metals']},
 {'node_id': 'fund-public-commodity-broad',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '综合 / 其他商品',
  'parent_node_id': 'fund-public-commodity',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['商品型', '综合 / 其他商品'],
  'path_node_ids_json': ['fund-public-commodity', 'fund-public-commodity-broad']},
 {'node_id': 'fund-public-real-assets',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '实物资产基金',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 6,
  'is_leaf': False,
  'path_labels_json': ['实物资产基金'],
  'path_node_ids_json': ['fund-public-real-assets']},
 {'node_id': 'fund-public-real-assets-real-estate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '房地产 / REITs',
  'parent_node_id': 'fund-public-real-assets',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['实物资产基金', '房地产 / REITs'],
  'path_node_ids_json': ['fund-public-real-assets', 'fund-public-real-assets-real-estate']},
 {'node_id': 'fund-public-real-assets-infrastructure',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '基础设施',
  'parent_node_id': 'fund-public-real-assets',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['实物资产基金', '基础设施'],
  'path_node_ids_json': ['fund-public-real-assets', 'fund-public-real-assets-infrastructure']},
 {'node_id': 'fund-public-money-market',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '货币市场',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 7,
  'is_leaf': True,
  'path_labels_json': ['货币市场'],
  'path_node_ids_json': ['fund-public-money-market']},
 {'node_id': 'fund-public-fof',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '基金中基金',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 8,
  'is_leaf': False,
  'path_labels_json': ['基金中基金'],
  'path_node_ids_json': ['fund-public-fof']},
 {'node_id': 'fund-public-fof-equity',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '权益 FOF',
  'parent_node_id': 'fund-public-fof',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['基金中基金', '权益 FOF'],
  'path_node_ids_json': ['fund-public-fof', 'fund-public-fof-equity']},
 {'node_id': 'fund-public-fof-fixed-income',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '固定收益 FOF',
  'parent_node_id': 'fund-public-fof',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['基金中基金', '固定收益 FOF'],
  'path_node_ids_json': ['fund-public-fof', 'fund-public-fof-fixed-income']},
 {'node_id': 'fund-public-fof-allocation',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '配置 FOF',
  'parent_node_id': 'fund-public-fof',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['基金中基金', '配置 FOF'],
  'path_node_ids_json': ['fund-public-fof', 'fund-public-fof-allocation']},
 {'node_id': 'fund-public-fof-alternative',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '另类 FOF',
  'parent_node_id': 'fund-public-fof',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['基金中基金', '另类 FOF'],
  'path_node_ids_json': ['fund-public-fof', 'fund-public-fof-alternative']},
 {'node_id': 'fund-public-other',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'public_fund',
  'label': '其他',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 9,
  'is_leaf': True,
  'path_labels_json': ['其他'],
  'path_node_ids_json': ['fund-public-other']},
 {'node_id': 'fund-private-equity',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '股票策略',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 10,
  'is_leaf': False,
  'path_labels_json': ['股票策略'],
  'path_node_ids_json': ['fund-private-equity']},
 {'node_id': 'fund-private-equity-discretionary-long',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '主观多头',
  'parent_node_id': 'fund-private-equity',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['股票策略', '主观多头'],
  'path_node_ids_json': ['fund-private-equity', 'fund-private-equity-discretionary-long']},
 {'node_id': 'fund-private-equity-quant-long',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '量化多头',
  'parent_node_id': 'fund-private-equity',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': False,
  'path_labels_json': ['股票策略', '量化多头'],
  'path_node_ids_json': ['fund-private-equity', 'fund-private-equity-quant-long']},
 {'node_id': 'fund-private-equity-quant-index-enhanced',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '指数增强',
  'parent_node_id': 'fund-private-equity-quant-long',
  'level_index': 3,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['股票策略', '量化多头', '指数增强'],
  'path_node_ids_json': ['fund-private-equity',
                         'fund-private-equity-quant-long',
                         'fund-private-equity-quant-index-enhanced']},
 {'node_id': 'fund-private-equity-quant-stock-selection',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '量化选股',
  'parent_node_id': 'fund-private-equity-quant-long',
  'level_index': 3,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['股票策略', '量化多头', '量化选股'],
  'path_node_ids_json': ['fund-private-equity',
                         'fund-private-equity-quant-long',
                         'fund-private-equity-quant-stock-selection']},
 {'node_id': 'fund-private-equity-long-short',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '股票多空',
  'parent_node_id': 'fund-private-equity',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['股票策略', '股票多空'],
  'path_node_ids_json': ['fund-private-equity', 'fund-private-equity-long-short']},
 {'node_id': 'fund-private-equity-market-neutral',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '股票市场中性',
  'parent_node_id': 'fund-private-equity',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['股票策略', '股票市场中性'],
  'path_node_ids_json': ['fund-private-equity', 'fund-private-equity-market-neutral']},
 {'node_id': 'fund-private-credit',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '信用策略',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 11,
  'is_leaf': False,
  'path_labels_json': ['信用策略'],
  'path_node_ids_json': ['fund-private-credit']},
 {'node_id': 'fund-private-credit-long-only',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '信用多头',
  'parent_node_id': 'fund-private-credit',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['信用策略', '信用多头'],
  'path_node_ids_json': ['fund-private-credit', 'fund-private-credit-long-only']},
 {'node_id': 'fund-private-credit-long-short',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '信用多空',
  'parent_node_id': 'fund-private-credit',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['信用策略', '信用多空'],
  'path_node_ids_json': ['fund-private-credit', 'fund-private-credit-long-short']},
 {'node_id': 'fund-private-credit-distressed',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '困境债 / 特殊机会',
  'parent_node_id': 'fund-private-credit',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['信用策略', '困境债 / 特殊机会'],
  'path_node_ids_json': ['fund-private-credit', 'fund-private-credit-distressed']},
 {'node_id': 'fund-private-credit-structured',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '结构化信用',
  'parent_node_id': 'fund-private-credit',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['信用策略', '结构化信用'],
  'path_node_ids_json': ['fund-private-credit', 'fund-private-credit-structured']},
 {'node_id': 'fund-private-macro',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '宏观策略',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 12,
  'is_leaf': False,
  'path_labels_json': ['宏观策略'],
  'path_node_ids_json': ['fund-private-macro']},
 {'node_id': 'fund-private-macro-discretionary',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '主观宏观',
  'parent_node_id': 'fund-private-macro',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['宏观策略', '主观宏观'],
  'path_node_ids_json': ['fund-private-macro', 'fund-private-macro-discretionary']},
 {'node_id': 'fund-private-macro-systematic',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '系统化宏观',
  'parent_node_id': 'fund-private-macro',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['宏观策略', '系统化宏观'],
  'path_node_ids_json': ['fund-private-macro', 'fund-private-macro-systematic']},
 {'node_id': 'fund-private-managed-futures',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '管理期货',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 13,
  'is_leaf': False,
  'path_labels_json': ['管理期货'],
  'path_node_ids_json': ['fund-private-managed-futures']},
 {'node_id': 'fund-private-managed-futures-trend',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '趋势跟踪',
  'parent_node_id': 'fund-private-managed-futures',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['管理期货', '趋势跟踪'],
  'path_node_ids_json': ['fund-private-managed-futures', 'fund-private-managed-futures-trend']},
 {'node_id': 'fund-private-managed-futures-relative-value',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '期货相对价值',
  'parent_node_id': 'fund-private-managed-futures',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['管理期货', '期货相对价值'],
  'path_node_ids_json': ['fund-private-managed-futures',
                         'fund-private-managed-futures-relative-value']},
 {'node_id': 'fund-private-managed-futures-multi',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': 'CTA 多策略',
  'parent_node_id': 'fund-private-managed-futures',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['管理期货', 'CTA 多策略'],
  'path_node_ids_json': ['fund-private-managed-futures', 'fund-private-managed-futures-multi']},
 {'node_id': 'fund-private-event-driven',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '事件驱动',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 14,
  'is_leaf': False,
  'path_labels_json': ['事件驱动'],
  'path_node_ids_json': ['fund-private-event-driven']},
 {'node_id': 'fund-private-event-driven-merger-arbitrage',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '并购套利',
  'parent_node_id': 'fund-private-event-driven',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['事件驱动', '并购套利'],
  'path_node_ids_json': ['fund-private-event-driven',
                         'fund-private-event-driven-merger-arbitrage']},
 {'node_id': 'fund-private-event-driven-special-situations',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '特殊事件',
  'parent_node_id': 'fund-private-event-driven',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['事件驱动', '特殊事件'],
  'path_node_ids_json': ['fund-private-event-driven',
                         'fund-private-event-driven-special-situations']},
 {'node_id': 'fund-private-relative-value',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '相对价值',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 15,
  'is_leaf': False,
  'path_labels_json': ['相对价值'],
  'path_node_ids_json': ['fund-private-relative-value']},
 {'node_id': 'fund-private-relative-value-fixed-income',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '固定收益相对价值',
  'parent_node_id': 'fund-private-relative-value',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['相对价值', '固定收益相对价值'],
  'path_node_ids_json': ['fund-private-relative-value',
                         'fund-private-relative-value-fixed-income']},
 {'node_id': 'fund-private-relative-value-convertible',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '可转债套利',
  'parent_node_id': 'fund-private-relative-value',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['相对价值', '可转债套利'],
  'path_node_ids_json': ['fund-private-relative-value', 'fund-private-relative-value-convertible']},
 {'node_id': 'fund-private-relative-value-volatility',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '波动率 / 期权',
  'parent_node_id': 'fund-private-relative-value',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['相对价值', '波动率 / 期权'],
  'path_node_ids_json': ['fund-private-relative-value', 'fund-private-relative-value-volatility']},
 {'node_id': 'fund-private-relative-value-multi-asset',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '跨资产相对价值',
  'parent_node_id': 'fund-private-relative-value',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['相对价值', '跨资产相对价值'],
  'path_node_ids_json': ['fund-private-relative-value', 'fund-private-relative-value-multi-asset']},
 {'node_id': 'fund-private-multi-strategy',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '多策略',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 16,
  'is_leaf': True,
  'path_labels_json': ['多策略'],
  'path_node_ids_json': ['fund-private-multi-strategy']},
 {'node_id': 'fund-private-fund-of-funds',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '组合基金',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 17,
  'is_leaf': False,
  'path_labels_json': ['组合基金'],
  'path_node_ids_json': ['fund-private-fund-of-funds']},
 {'node_id': 'fund-private-fund-of-funds-fof',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': 'FOF',
  'parent_node_id': 'fund-private-fund-of-funds',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['组合基金', 'FOF'],
  'path_node_ids_json': ['fund-private-fund-of-funds', 'fund-private-fund-of-funds-fof']},
 {'node_id': 'fund-private-fund-of-funds-mom',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': 'MOM',
  'parent_node_id': 'fund-private-fund-of-funds',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['组合基金', 'MOM'],
  'path_node_ids_json': ['fund-private-fund-of-funds', 'fund-private-fund-of-funds-mom']},
 {'node_id': 'fund-private-other',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'private_fund',
  'label': '其他',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 18,
  'is_leaf': True,
  'path_labels_json': ['其他'],
  'path_node_ids_json': ['fund-private-other']},
 {'node_id': 'etf-equity',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '权益',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 19,
  'is_leaf': False,
  'path_labels_json': ['权益'],
  'path_node_ids_json': ['etf-equity']},
 {'node_id': 'etf-equity-broad-market',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '宽基',
  'parent_node_id': 'etf-equity',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['权益', '宽基'],
  'path_node_ids_json': ['etf-equity', 'etf-equity-broad-market']},
 {'node_id': 'etf-equity-size-style',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '规模 / 风格',
  'parent_node_id': 'etf-equity',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['权益', '规模 / 风格'],
  'path_node_ids_json': ['etf-equity', 'etf-equity-size-style']},
 {'node_id': 'etf-equity-sector',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '行业',
  'parent_node_id': 'etf-equity',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['权益', '行业'],
  'path_node_ids_json': ['etf-equity', 'etf-equity-sector']},
 {'node_id': 'etf-equity-theme',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '主题',
  'parent_node_id': 'etf-equity',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['权益', '主题'],
  'path_node_ids_json': ['etf-equity', 'etf-equity-theme']},
 {'node_id': 'etf-equity-factor',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '因子 / 股息',
  'parent_node_id': 'etf-equity',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['权益', '因子 / 股息'],
  'path_node_ids_json': ['etf-equity', 'etf-equity-factor']},
 {'node_id': 'etf-fixed-income',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '固定收益',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 20,
  'is_leaf': False,
  'path_labels_json': ['固定收益'],
  'path_node_ids_json': ['etf-fixed-income']},
 {'node_id': 'etf-fixed-income-government',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '利率债',
  'parent_node_id': 'etf-fixed-income',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['固定收益', '利率债'],
  'path_node_ids_json': ['etf-fixed-income', 'etf-fixed-income-government']},
 {'node_id': 'etf-fixed-income-investment-grade',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '投资级信用',
  'parent_node_id': 'etf-fixed-income',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['固定收益', '投资级信用'],
  'path_node_ids_json': ['etf-fixed-income', 'etf-fixed-income-investment-grade']},
 {'node_id': 'etf-fixed-income-high-yield',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '高收益债',
  'parent_node_id': 'etf-fixed-income',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['固定收益', '高收益债'],
  'path_node_ids_json': ['etf-fixed-income', 'etf-fixed-income-high-yield']},
 {'node_id': 'etf-fixed-income-aggregate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '综合债券',
  'parent_node_id': 'etf-fixed-income',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['固定收益', '综合债券'],
  'path_node_ids_json': ['etf-fixed-income', 'etf-fixed-income-aggregate']},
 {'node_id': 'etf-fixed-income-short-duration',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '短久期',
  'parent_node_id': 'etf-fixed-income',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['固定收益', '短久期'],
  'path_node_ids_json': ['etf-fixed-income', 'etf-fixed-income-short-duration']},
 {'node_id': 'etf-fixed-income-inflation-linked',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '通胀挂钩',
  'parent_node_id': 'etf-fixed-income',
  'level_index': 2,
  'display_order': 6,
  'is_leaf': True,
  'path_labels_json': ['固定收益', '通胀挂钩'],
  'path_node_ids_json': ['etf-fixed-income', 'etf-fixed-income-inflation-linked']},
 {'node_id': 'etf-fixed-income-municipal',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '市政债',
  'parent_node_id': 'etf-fixed-income',
  'level_index': 2,
  'display_order': 7,
  'is_leaf': True,
  'path_labels_json': ['固定收益', '市政债'],
  'path_node_ids_json': ['etf-fixed-income', 'etf-fixed-income-municipal']},
 {'node_id': 'etf-fixed-income-convertible',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '可转债',
  'parent_node_id': 'etf-fixed-income',
  'level_index': 2,
  'display_order': 8,
  'is_leaf': True,
  'path_labels_json': ['固定收益', '可转债'],
  'path_node_ids_json': ['etf-fixed-income', 'etf-fixed-income-convertible']},
 {'node_id': 'etf-commodity',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '商品',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 21,
  'is_leaf': False,
  'path_labels_json': ['商品'],
  'path_node_ids_json': ['etf-commodity']},
 {'node_id': 'etf-commodity-precious-metals',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '贵金属',
  'parent_node_id': 'etf-commodity',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['商品', '贵金属'],
  'path_node_ids_json': ['etf-commodity', 'etf-commodity-precious-metals']},
 {'node_id': 'etf-commodity-broad',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '综合商品',
  'parent_node_id': 'etf-commodity',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['商品', '综合商品'],
  'path_node_ids_json': ['etf-commodity', 'etf-commodity-broad']},
 {'node_id': 'etf-commodity-single',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '单一商品',
  'parent_node_id': 'etf-commodity',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['商品', '单一商品'],
  'path_node_ids_json': ['etf-commodity', 'etf-commodity-single']},
 {'node_id': 'etf-real-assets',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '实物资产',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 22,
  'is_leaf': False,
  'path_labels_json': ['实物资产'],
  'path_node_ids_json': ['etf-real-assets']},
 {'node_id': 'etf-real-assets-real-estate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '房地产 / REITs',
  'parent_node_id': 'etf-real-assets',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['实物资产', '房地产 / REITs'],
  'path_node_ids_json': ['etf-real-assets', 'etf-real-assets-real-estate']},
 {'node_id': 'etf-real-assets-infrastructure',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '基础设施',
  'parent_node_id': 'etf-real-assets',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['实物资产', '基础设施'],
  'path_node_ids_json': ['etf-real-assets', 'etf-real-assets-infrastructure']},
 {'node_id': 'etf-multi-asset',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '多资产',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 23,
  'is_leaf': False,
  'path_labels_json': ['多资产'],
  'path_node_ids_json': ['etf-multi-asset']},
 {'node_id': 'etf-multi-asset-allocation',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '资产配置',
  'parent_node_id': 'etf-multi-asset',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['多资产', '资产配置'],
  'path_node_ids_json': ['etf-multi-asset', 'etf-multi-asset-allocation']},
 {'node_id': 'etf-multi-asset-alternative',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '另类多资产',
  'parent_node_id': 'etf-multi-asset',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['多资产', '另类多资产'],
  'path_node_ids_json': ['etf-multi-asset', 'etf-multi-asset-alternative']},
 {'node_id': 'etf-tactical',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '战术工具',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 24,
  'is_leaf': False,
  'path_labels_json': ['战术工具'],
  'path_node_ids_json': ['etf-tactical']},
 {'node_id': 'etf-tactical-leveraged',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '杠杆',
  'parent_node_id': 'etf-tactical',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['战术工具', '杠杆'],
  'path_node_ids_json': ['etf-tactical', 'etf-tactical-leveraged']},
 {'node_id': 'etf-tactical-inverse',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '反向',
  'parent_node_id': 'etf-tactical',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['战术工具', '反向'],
  'path_node_ids_json': ['etf-tactical', 'etf-tactical-inverse']},
 {'node_id': 'etf-tactical-volatility',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '波动率',
  'parent_node_id': 'etf-tactical',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['战术工具', '波动率'],
  'path_node_ids_json': ['etf-tactical', 'etf-tactical-volatility']},
 {'node_id': 'etf-cash',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '现金管理',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 25,
  'is_leaf': True,
  'path_labels_json': ['现金管理'],
  'path_node_ids_json': ['etf-cash']},
 {'node_id': 'etf-other',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'etf',
  'label': '其他',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 26,
  'is_leaf': True,
  'path_labels_json': ['其他'],
  'path_node_ids_json': ['etf-other']},
 {'node_id': 'equity-market-us',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '美股',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 27,
  'is_leaf': False,
  'path_labels_json': ['美股'],
  'path_node_ids_json': ['equity-market-us']},
 {'node_id': 'equity-us-energy',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '能源',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['美股', '能源'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-energy']},
 {'node_id': 'equity-us-materials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '原材料',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['美股', '原材料'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-materials']},
 {'node_id': 'equity-us-industrials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '工业',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['美股', '工业'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-industrials']},
 {'node_id': 'equity-us-consumer-discretionary',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '可选消费',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['美股', '可选消费'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-consumer-discretionary']},
 {'node_id': 'equity-us-consumer-staples',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '日常消费',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['美股', '日常消费'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-consumer-staples']},
 {'node_id': 'equity-us-health-care',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '医疗保健',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 6,
  'is_leaf': True,
  'path_labels_json': ['美股', '医疗保健'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-health-care']},
 {'node_id': 'equity-us-financials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '金融',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 7,
  'is_leaf': True,
  'path_labels_json': ['美股', '金融'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-financials']},
 {'node_id': 'equity-us-information-technology',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '信息技术',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 8,
  'is_leaf': True,
  'path_labels_json': ['美股', '信息技术'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-information-technology']},
 {'node_id': 'equity-us-communication-services',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '通信服务',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 9,
  'is_leaf': True,
  'path_labels_json': ['美股', '通信服务'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-communication-services']},
 {'node_id': 'equity-us-utilities',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '公用事业',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 10,
  'is_leaf': True,
  'path_labels_json': ['美股', '公用事业'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-utilities']},
 {'node_id': 'equity-us-real-estate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '房地产',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 11,
  'is_leaf': True,
  'path_labels_json': ['美股', '房地产'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-real-estate']},
 {'node_id': 'equity-us-unclassified',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '待分类',
  'parent_node_id': 'equity-market-us',
  'level_index': 2,
  'display_order': 12,
  'is_leaf': True,
  'path_labels_json': ['美股', '待分类'],
  'path_node_ids_json': ['equity-market-us', 'equity-us-unclassified']},
 {'node_id': 'equity-market-hk',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '港股',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 28,
  'is_leaf': False,
  'path_labels_json': ['港股'],
  'path_node_ids_json': ['equity-market-hk']},
 {'node_id': 'equity-hk-energy',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '能源',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['港股', '能源'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-energy']},
 {'node_id': 'equity-hk-materials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '原材料',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['港股', '原材料'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-materials']},
 {'node_id': 'equity-hk-industrials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '工业',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['港股', '工业'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-industrials']},
 {'node_id': 'equity-hk-consumer-discretionary',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '可选消费',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['港股', '可选消费'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-consumer-discretionary']},
 {'node_id': 'equity-hk-consumer-staples',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '日常消费',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['港股', '日常消费'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-consumer-staples']},
 {'node_id': 'equity-hk-health-care',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '医疗保健',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 6,
  'is_leaf': True,
  'path_labels_json': ['港股', '医疗保健'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-health-care']},
 {'node_id': 'equity-hk-financials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '金融',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 7,
  'is_leaf': True,
  'path_labels_json': ['港股', '金融'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-financials']},
 {'node_id': 'equity-hk-information-technology',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '信息技术',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 8,
  'is_leaf': True,
  'path_labels_json': ['港股', '信息技术'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-information-technology']},
 {'node_id': 'equity-hk-communication-services',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '通信服务',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 9,
  'is_leaf': True,
  'path_labels_json': ['港股', '通信服务'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-communication-services']},
 {'node_id': 'equity-hk-utilities',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '公用事业',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 10,
  'is_leaf': True,
  'path_labels_json': ['港股', '公用事业'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-utilities']},
 {'node_id': 'equity-hk-real-estate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '房地产',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 11,
  'is_leaf': True,
  'path_labels_json': ['港股', '房地产'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-real-estate']},
 {'node_id': 'equity-hk-unclassified',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '待分类',
  'parent_node_id': 'equity-market-hk',
  'level_index': 2,
  'display_order': 12,
  'is_leaf': True,
  'path_labels_json': ['港股', '待分类'],
  'path_node_ids_json': ['equity-market-hk', 'equity-hk-unclassified']},
 {'node_id': 'equity-market-cn-a',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': 'A股',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 29,
  'is_leaf': False,
  'path_labels_json': ['A股'],
  'path_node_ids_json': ['equity-market-cn-a']},
 {'node_id': 'equity-cn-a-energy',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '能源',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['A股', '能源'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-energy']},
 {'node_id': 'equity-cn-a-materials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '原材料',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['A股', '原材料'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-materials']},
 {'node_id': 'equity-cn-a-industrials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '工业',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['A股', '工业'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-industrials']},
 {'node_id': 'equity-cn-a-consumer-discretionary',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '可选消费',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['A股', '可选消费'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-consumer-discretionary']},
 {'node_id': 'equity-cn-a-consumer-staples',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '日常消费',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['A股', '日常消费'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-consumer-staples']},
 {'node_id': 'equity-cn-a-health-care',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '医疗保健',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 6,
  'is_leaf': True,
  'path_labels_json': ['A股', '医疗保健'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-health-care']},
 {'node_id': 'equity-cn-a-financials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '金融',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 7,
  'is_leaf': True,
  'path_labels_json': ['A股', '金融'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-financials']},
 {'node_id': 'equity-cn-a-information-technology',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '信息技术',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 8,
  'is_leaf': True,
  'path_labels_json': ['A股', '信息技术'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-information-technology']},
 {'node_id': 'equity-cn-a-communication-services',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '通信服务',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 9,
  'is_leaf': True,
  'path_labels_json': ['A股', '通信服务'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-communication-services']},
 {'node_id': 'equity-cn-a-utilities',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '公用事业',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 10,
  'is_leaf': True,
  'path_labels_json': ['A股', '公用事业'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-utilities']},
 {'node_id': 'equity-cn-a-real-estate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '房地产',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 11,
  'is_leaf': True,
  'path_labels_json': ['A股', '房地产'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-real-estate']},
 {'node_id': 'equity-cn-a-unclassified',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '待分类',
  'parent_node_id': 'equity-market-cn-a',
  'level_index': 2,
  'display_order': 12,
  'is_leaf': True,
  'path_labels_json': ['A股', '待分类'],
  'path_node_ids_json': ['equity-market-cn-a', 'equity-cn-a-unclassified']},
 {'node_id': 'equity-market-eu',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '欧洲股市',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 30,
  'is_leaf': False,
  'path_labels_json': ['欧洲股市'],
  'path_node_ids_json': ['equity-market-eu']},
 {'node_id': 'equity-eu-energy',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '能源',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '能源'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-energy']},
 {'node_id': 'equity-eu-materials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '原材料',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '原材料'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-materials']},
 {'node_id': 'equity-eu-industrials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '工业',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '工业'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-industrials']},
 {'node_id': 'equity-eu-consumer-discretionary',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '可选消费',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '可选消费'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-consumer-discretionary']},
 {'node_id': 'equity-eu-consumer-staples',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '日常消费',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '日常消费'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-consumer-staples']},
 {'node_id': 'equity-eu-health-care',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '医疗保健',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 6,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '医疗保健'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-health-care']},
 {'node_id': 'equity-eu-financials',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '金融',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 7,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '金融'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-financials']},
 {'node_id': 'equity-eu-information-technology',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '信息技术',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 8,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '信息技术'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-information-technology']},
 {'node_id': 'equity-eu-communication-services',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '通信服务',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 9,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '通信服务'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-communication-services']},
 {'node_id': 'equity-eu-utilities',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '公用事业',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 10,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '公用事业'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-utilities']},
 {'node_id': 'equity-eu-real-estate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '房地产',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 11,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '房地产'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-real-estate']},
 {'node_id': 'equity-eu-unclassified',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'equity',
  'label': '待分类',
  'parent_node_id': 'equity-market-eu',
  'level_index': 2,
  'display_order': 12,
  'is_leaf': True,
  'path_labels_json': ['欧洲股市', '待分类'],
  'path_node_ids_json': ['equity-market-eu', 'equity-eu-unclassified']},
 {'node_id': 'index-equity',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '权益指数',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 31,
  'is_leaf': False,
  'path_labels_json': ['权益指数'],
  'path_node_ids_json': ['index-equity']},
 {'node_id': 'index-equity-broad-market',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '宽基',
  'parent_node_id': 'index-equity',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['权益指数', '宽基'],
  'path_node_ids_json': ['index-equity', 'index-equity-broad-market']},
 {'node_id': 'index-equity-size-style',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '规模 / 风格',
  'parent_node_id': 'index-equity',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['权益指数', '规模 / 风格'],
  'path_node_ids_json': ['index-equity', 'index-equity-size-style']},
 {'node_id': 'index-equity-sector',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '行业',
  'parent_node_id': 'index-equity',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['权益指数', '行业'],
  'path_node_ids_json': ['index-equity', 'index-equity-sector']},
 {'node_id': 'index-equity-theme',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '主题',
  'parent_node_id': 'index-equity',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['权益指数', '主题'],
  'path_node_ids_json': ['index-equity', 'index-equity-theme']},
 {'node_id': 'index-equity-factor',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '因子 / 股息',
  'parent_node_id': 'index-equity',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['权益指数', '因子 / 股息'],
  'path_node_ids_json': ['index-equity', 'index-equity-factor']},
 {'node_id': 'index-fixed-income',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '固定收益指数',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 32,
  'is_leaf': False,
  'path_labels_json': ['固定收益指数'],
  'path_node_ids_json': ['index-fixed-income']},
 {'node_id': 'index-fixed-income-government',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '政府债',
  'parent_node_id': 'index-fixed-income',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['固定收益指数', '政府债'],
  'path_node_ids_json': ['index-fixed-income', 'index-fixed-income-government']},
 {'node_id': 'index-fixed-income-investment-grade',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '投资级信用',
  'parent_node_id': 'index-fixed-income',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['固定收益指数', '投资级信用'],
  'path_node_ids_json': ['index-fixed-income', 'index-fixed-income-investment-grade']},
 {'node_id': 'index-fixed-income-high-yield',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '高收益债',
  'parent_node_id': 'index-fixed-income',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['固定收益指数', '高收益债'],
  'path_node_ids_json': ['index-fixed-income', 'index-fixed-income-high-yield']},
 {'node_id': 'index-fixed-income-aggregate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '综合债券',
  'parent_node_id': 'index-fixed-income',
  'level_index': 2,
  'display_order': 4,
  'is_leaf': True,
  'path_labels_json': ['固定收益指数', '综合债券'],
  'path_node_ids_json': ['index-fixed-income', 'index-fixed-income-aggregate']},
 {'node_id': 'index-fixed-income-inflation-linked',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '通胀挂钩',
  'parent_node_id': 'index-fixed-income',
  'level_index': 2,
  'display_order': 5,
  'is_leaf': True,
  'path_labels_json': ['固定收益指数', '通胀挂钩'],
  'path_node_ids_json': ['index-fixed-income', 'index-fixed-income-inflation-linked']},
 {'node_id': 'index-fixed-income-convertible',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '可转债',
  'parent_node_id': 'index-fixed-income',
  'level_index': 2,
  'display_order': 6,
  'is_leaf': True,
  'path_labels_json': ['固定收益指数', '可转债'],
  'path_node_ids_json': ['index-fixed-income', 'index-fixed-income-convertible']},
 {'node_id': 'index-commodity',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '商品指数',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 33,
  'is_leaf': False,
  'path_labels_json': ['商品指数'],
  'path_node_ids_json': ['index-commodity']},
 {'node_id': 'index-commodity-broad',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '综合商品',
  'parent_node_id': 'index-commodity',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['商品指数', '综合商品'],
  'path_node_ids_json': ['index-commodity', 'index-commodity-broad']},
 {'node_id': 'index-commodity-precious-metals',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '贵金属',
  'parent_node_id': 'index-commodity',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['商品指数', '贵金属'],
  'path_node_ids_json': ['index-commodity', 'index-commodity-precious-metals']},
 {'node_id': 'index-commodity-single',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '单一商品',
  'parent_node_id': 'index-commodity',
  'level_index': 2,
  'display_order': 3,
  'is_leaf': True,
  'path_labels_json': ['商品指数', '单一商品'],
  'path_node_ids_json': ['index-commodity', 'index-commodity-single']},
 {'node_id': 'index-real-assets',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '实物资产指数',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 34,
  'is_leaf': False,
  'path_labels_json': ['实物资产指数'],
  'path_node_ids_json': ['index-real-assets']},
 {'node_id': 'index-real-assets-real-estate',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '房地产 / REITs',
  'parent_node_id': 'index-real-assets',
  'level_index': 2,
  'display_order': 1,
  'is_leaf': True,
  'path_labels_json': ['实物资产指数', '房地产 / REITs'],
  'path_node_ids_json': ['index-real-assets', 'index-real-assets-real-estate']},
 {'node_id': 'index-real-assets-infrastructure',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '基础设施',
  'parent_node_id': 'index-real-assets',
  'level_index': 2,
  'display_order': 2,
  'is_leaf': True,
  'path_labels_json': ['实物资产指数', '基础设施'],
  'path_node_ids_json': ['index-real-assets', 'index-real-assets-infrastructure']},
 {'node_id': 'index-multi-asset-allocation',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '多资产配置',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 35,
  'is_leaf': True,
  'path_labels_json': ['多资产配置'],
  'path_node_ids_json': ['index-multi-asset-allocation']},
 {'node_id': 'index-alternative',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '另类策略',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 36,
  'is_leaf': True,
  'path_labels_json': ['另类策略'],
  'path_node_ids_json': ['index-alternative']},
 {'node_id': 'index-other',
  'taxonomy_code': 'instrument_taxonomy',
  'instrument_type': 'index',
  'label': '其他',
  'parent_node_id': None,
  'level_index': 1,
  'display_order': 37,
  'is_leaf': True,
  'path_labels_json': ['其他'],
  'path_node_ids_json': ['index-other']}]

PRIMARY_GEOGRAPHIC_EXPOSURE_DEFINITION = {'attribute_key': 'primary_geographic_exposure',
 'label': '主要地域敞口',
 'description': '底层资产的主要地域，而不是基金注册地、交易所或上市地点；用于跨市场筛选和同类比较。',
 'data_type': 'single_select',
 'options': ['中国 A 股',
             '中国内地',
             '香港',
             '大中华区',
             '美国',
             '全球',
             '发达市场（美国除外）',
             '新兴市场',
             '欧洲',
             '日本',
             '亚太（日本除外）',
             '其他 / 多地域',
             '全球 / 非地域型'],
 'is_groupable': True,
 'is_filterable': True,
 'is_view_column': True,
 'default_visible': False,
 'domain_code': 'overview',
 'group_code': 'overview_exposure',
 'display_order': 25,
 'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'index'],
 'applicability_json': {},
 'rubric_json': {'summary': '把投资敞口与上市市场、注册地和 QDII 等包装形式分开。',
                 'standard': '按长期主要风险敞口单选；全球宏观、商品和真正跨地域组合使用全球 / 非地域型或其他 / 多地域。',
                 'evidence': ['mandate', 'benchmark', 'holdings', 'country_allocation']},
 'required_for_monitoring': True}
