"""Frozen Watchlist investment-research field contract for migration 0045."""

from __future__ import annotations

ATTRIBUTE_DEFINITION_ROWS = [{'attribute_key': 'thesis_status',
  'label': 'Investment Thesis Status',
  'description': 'Current state of the investable thesis, separate from watchlist lifecycle and '
                 'position status.',
  'data_type': 'single_select',
  'options': ['Developing', 'Active', 'Under Review', 'Broken', 'Closed'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_coverage',
  'display_order': 115,
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'applicability_json': {},
  'rubric_json': {'summary': '记录投资论点本身处于建立、有效、复核、失效还是结束状态。',
                  'standard': 'Under Review 必须有明确待核查证据；Broken 表示核心前提已经被证伪；Closed 表示研究周期已经结束。',
                  'evidence': ['investment_view', 'research_notes', 'decision_record']},
  'required_for_monitoring': True},
 {'attribute_key': 'focus_bucket',
  'label': 'Research Priority',
  'description': 'Internal attention bucket for near-term research and review priority.',
  'data_type': 'single_select',
  'options': ['Tier 1', 'Tier 2', 'Tier 3'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_coverage',
  'display_order': 120,
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'applicability_json': {},
  'rubric_json': {'summary': '用于排研究资源优先级，不代表基金好坏或是否持仓。',
                  'standard': 'Tier 1 代表近期最需要研究/复核；Tier 3 代表低频观察。'},
  'required_for_monitoring': False},
 {'attribute_key': 'research_evidence_level',
  'label': '证据充分度',
  'description': '当前定性结论背后的证据完整程度。',
  'data_type': 'single_select',
  'options': ['完整证据', '部分证据', '轶事证据', '待验证'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_coverage',
  'display_order': 125,
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'applicability_json': {},
  'rubric_json': {'summary': '衡量标签、rating 和 Research View 是否有足够材料支撑。',
                  'standard': '完整证据需要至少覆盖文档、访谈、业绩归因/持仓验证和条款检查；轶事证据不能支撑高 conviction。',
                  'evidence': ['research_notes',
                               'documents',
                               'meeting_notes',
                               'performance_attribution']},
  'required_for_monitoring': True},
 {'attribute_key': 'investment_edge_quality',
  'label': '投资优势质量',
  'description': '收益来源是否清晰、可解释、可持续。',
  'data_type': 'single_select',
  'options': ['清晰且可持续', '清晰但需验证', '主要是市场贝塔', '边际优势不清'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_edge',
  'display_order': 128,
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'applicability_json': {},
  'rubric_json': {'summary': '回答“这只产品是否有真正的、可持续的 edge”。',
                  'standard': '必须能通过流程、团队、数据、市场结构或历史归因解释；不要把短期排名当作 edge。',
                  'evidence': ['performance_attribution',
                               'portfolio_history',
                               'manager_interview',
                               'process_materials']},
  'required_for_monitoring': False},
 {'attribute_key': 'historical_delivery',
  'label': '历史兑现度',
  'description': '管理人/产品是否长期兑现其声明能力。',
  'data_type': 'single_select',
  'options': ['稳定兑现', '环境依赖', '尚未验证', '兑现失效'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_delivery',
  'display_order': 210,
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'applicability_json': {},
  'rubric_json': {'summary': '这是 buy-side 研究里的“有没有说到做到”。',
                  'standard': '必须结合完整周期和压力阶段，不用短期排名替代。',
                  'evidence': ['full_cycle_performance',
                               'drawdown_review',
                               'style_exposure',
                               'peer_comparison']},
  'required_for_monitoring': False},
 {'attribute_key': 'portfolio_role',
  'label': '组合角色',
  'description': '该标的更适合在组合中承担什么角色，可多选但通常不超过两个。',
  'data_type': 'multi_select',
  'options': ['核心配置', '卫星增强', '分散化工具', '防守/对冲', '战术配置', '仅观察'],
  'is_groupable': False,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_role',
  'display_order': 215,
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'applicability_json': {},
  'rubric_json': {'summary': '把单一标的研究结论翻译成组合用途。',
                  'standard': '组合角色必须与相关性、风险贡献、容量、条款和 rating 一致；仅观察不能与 5 星同时存在。',
                  'evidence': ['correlation',
                               'risk_contribution',
                               'portfolio_gap',
                               'research_notes']},
  'required_for_monitoring': False},
 {'attribute_key': 'equity_business_quality',
  'label': 'Business Quality',
  'description': "Durability of the listed company's economics, competitive position, and "
                 'reinvestment opportunity.',
  'data_type': 'single_select',
  'options': ['Exceptional', 'Strong', 'Average', 'Weak', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_equity',
  'display_order': 220,
  'instrument_scope_json': ['equity'],
  'applicability_json': {},
  'rubric_json': {'summary': '综合商业模式、竞争优势、资本回报和可再投资空间，而不是短期股价表现。',
                  'standard': '结论应由盈利结构、竞争行为、客户/供应商关系与行业结构支撑。',
                  'evidence': ['financials',
                               'industry_research',
                               'management_evidence',
                               'research_notes']},
  'required_for_monitoring': False},
 {'attribute_key': 'equity_valuation_view',
  'label': 'Valuation View',
  'description': 'Current valuation conclusion relative to normalized fundamentals and the '
                 'investment thesis.',
  'data_type': 'single_select',
  'options': ['Deeply Undervalued', 'Undervalued', 'Fair', 'Expensive', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_equity',
  'display_order': 225,
  'instrument_scope_json': ['equity'],
  'applicability_json': {},
  'rubric_json': {'summary': '估值判断必须对应明确的盈利、现金流、资产或情景框架。',
                  'standard': '不把历史分位本身当作内在价值；记录关键假设和失效条件。',
                  'evidence': ['valuation_model', 'financials', 'scenario_analysis']},
  'required_for_monitoring': False},
 {'attribute_key': 'equity_financial_quality',
  'label': 'Financial Quality',
  'description': 'Quality of earnings, cash conversion, leverage, and balance-sheet resilience.',
  'data_type': 'single_select',
  'options': ['High', 'Acceptable', 'Cyclical', 'Fragile', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_equity',
  'display_order': 230,
  'instrument_scope_json': ['equity'],
  'applicability_json': {},
  'rubric_json': {'summary': '区分会计利润、现金兑现和资产负债表承压能力。',
                  'standard': '至少结合现金转换、应计项目、资本化政策、杠杆和到期结构。',
                  'evidence': ['financial_statements',
                               'cash_flow',
                               'balance_sheet',
                               'accounting_notes']},
  'required_for_monitoring': False},
 {'attribute_key': 'equity_governance_quality',
  'label': 'Governance & Capital Allocation',
  'description': 'Management incentives, minority-holder alignment, governance, and '
                 'capital-allocation quality.',
  'data_type': 'single_select',
  'options': ['Strong', 'Acceptable', 'Mixed', 'Weak', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_equity',
  'display_order': 235,
  'instrument_scope_json': ['equity'],
  'applicability_json': {},
  'rubric_json': {'summary': '记录管理层行为、激励、关联交易与资本配置，而不是只看人物履历。',
                  'standard': '结合历史承诺兑现、并购、分红回购、融资稀释和少数股东待遇。',
                  'evidence': ['governance_filings',
                               'capital_allocation_history',
                               'management_record']},
  'required_for_monitoring': False},
 {'attribute_key': 'etf_index_fit',
  'label': 'Index / Strategy Fit',
  'description': 'How well the tracked index or ruleset expresses the intended portfolio exposure.',
  'data_type': 'single_select',
  'options': ['Excellent', 'Good', 'Compromised', 'Poor', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_etf',
  'display_order': 240,
  'instrument_scope_json': ['etf'],
  'applicability_json': {},
  'rubric_json': {'summary': '判断指数规则、成分边界和权重方法是否真正表达目标敞口。',
                  'standard': '不能用 ETF 名称代替对指数规则、集中度、换手和不可投资成分的检查。',
                  'evidence': ['index_methodology', 'holdings', 'concentration', 'turnover']},
  'required_for_monitoring': False},
 {'attribute_key': 'etf_tracking_quality',
  'label': 'Tracking Quality',
  'description': 'Observed and expected ability to deliver the tracked exposure after fees and '
                 'implementation effects.',
  'data_type': 'single_select',
  'options': ['Strong', 'Acceptable', 'Variable', 'Weak', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_etf',
  'display_order': 245,
  'instrument_scope_json': ['etf'],
  'applicability_json': {},
  'rubric_json': {'summary': '综合跟踪差异、跟踪误差、费用、现金拖累和复制方式。',
                  'standard': '缺少对应基准和一致收益口径时标记 Unclear，不用价格相关性替代。',
                  'evidence': ['benchmark_returns', 'fund_returns', 'fees', 'replication_method']},
  'required_for_monitoring': False},
 {'attribute_key': 'etf_liquidity_quality',
  'label': 'Liquidity & Trading Quality',
  'description': 'Secondary-market liquidity, spread, creation/redemption depth, and '
                 'premium/discount behavior.',
  'data_type': 'single_select',
  'options': ['Strong', 'Adequate', 'Thin', 'Stressed', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_etf',
  'display_order': 250,
  'instrument_scope_json': ['etf'],
  'applicability_json': {},
  'rubric_json': {'summary': '把屏幕成交、价差、底层流动性和申赎机制一起判断。',
                  'standard': '成交量不是唯一证据；压力期折溢价和做市深度应单独核查。',
                  'evidence': ['volume',
                               'bid_ask_spread',
                               'premium_discount',
                               'underlying_liquidity']},
  'required_for_monitoring': False},
 {'attribute_key': 'etf_structure_quality',
  'label': 'Structure & Cost Quality',
  'description': 'Fund structure, securities lending, tax, counterparty, closure, and total-cost '
                 'assessment.',
  'data_type': 'single_select',
  'options': ['Strong', 'Acceptable', 'Mixed', 'Weak', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_etf',
  'display_order': 255,
  'instrument_scope_json': ['etf'],
  'applicability_json': {},
  'rubric_json': {'summary': '评价持有者实际承担的结构、税务、对手方和关闭风险。',
                  'standard': '费用率只是总成本的一部分；需结合跟踪差异、借券收益与交易成本。',
                  'evidence': ['prospectus',
                               'fees',
                               'securities_lending',
                               'fund_size',
                               'issuer_policy']},
  'required_for_monitoring': False},
 {'attribute_key': 'index_methodology_quality',
  'label': 'Methodology Quality',
  'description': 'Clarity, economic rationale, robustness, and reproducibility of the index '
                 'methodology.',
  'data_type': 'single_select',
  'options': ['Strong', 'Acceptable', 'Fragile', 'Weak', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_index',
  'display_order': 260,
  'instrument_scope_json': ['index'],
  'applicability_json': {},
  'rubric_json': {'summary': '判断方法论是否透明、可复现且有明确经济含义。',
                  'standard': '警惕复杂但缺乏经济依据、依赖自由裁量或过度回测拟合的规则。',
                  'evidence': ['methodology_document',
                               'rule_history',
                               'backfill_policy',
                               'governance']},
  'required_for_monitoring': False},
 {'attribute_key': 'index_representation_quality',
  'label': 'Market Representation',
  'description': 'How well constituents and weights represent the market, segment, factor, or '
                 'theme claimed by the index.',
  'data_type': 'single_select',
  'options': ['High', 'Adequate', 'Biased', 'Poor', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_index',
  'display_order': 265,
  'instrument_scope_json': ['index'],
  'applicability_json': {},
  'rubric_json': {'summary': '检查成分边界、权重、集中度和行业/风格偏差。',
                  'standard': '指数名称不能证明代表性；必须查看实际成分和长期暴露。',
                  'evidence': ['constituents', 'weights', 'sector_exposure', 'factor_exposure']},
  'required_for_monitoring': False},
 {'attribute_key': 'index_investability_quality',
  'label': 'Investability',
  'description': 'Practical replicability after liquidity, capacity, turnover, reconstitution, and '
                 'market-access constraints.',
  'data_type': 'single_select',
  'options': ['High', 'Adequate', 'Constrained', 'Poor', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_index',
  'display_order': 270,
  'instrument_scope_json': ['index'],
  'applicability_json': {},
  'rubric_json': {'summary': '评价从纸面指数转化为可交易组合后的容量、成本和可复制性。',
                  'standard': '结合成分流动性、换手、调仓拥挤、市场准入和公司行动处理。',
                  'evidence': ['constituent_liquidity',
                               'turnover',
                               'rebalance_history',
                               'market_access']},
  'required_for_monitoring': False},
 {'attribute_key': 'index_governance_quality',
  'label': 'Methodology Governance',
  'description': 'Quality of index-provider governance, consultation, exception handling, and '
                 'change control.',
  'data_type': 'single_select',
  'options': ['Strong', 'Acceptable', 'Discretionary', 'Weak', 'Unclear'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'research',
  'group_code': 'research_index',
  'display_order': 275,
  'instrument_scope_json': ['index'],
  'applicability_json': {},
  'rubric_json': {'summary': '记录方法论变更、例外处置和利益冲突治理。',
                  'standard': '明确区分可预测规则与委员会自由裁量，并保留重大变更证据。',
                  'evidence': ['governance_policy',
                               'consultations',
                               'methodology_changes',
                               'committee_disclosures']},
  'required_for_monitoring': False},
 {'attribute_key': 'transparency_quality',
  'label': '研究透明度',
  'description': '产品对外信息披露与可研究性质量。',
  'data_type': 'single_select',
  'options': ['高', '中', '低'],
  'is_groupable': True,
  'is_filterable': True,
  'is_view_column': True,
  'default_visible': False,
  'domain_code': 'monitoring',
  'group_code': 'monitoring_operational',
  'display_order': 370,
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'applicability_json': {},
  'rubric_json': {'summary': '衡量后续跟踪是否有足够材料支撑。', 'standard': '看披露频率、口径一致性、访谈可得性和底层可验证程度。'},
  'required_for_monitoring': True}]

RESEARCH_SYSTEM_FIELD_ROWS = [{'field_key': 'attr.research_current_view',
  'label': 'Current Investment View',
  'description': 'Current analyst conclusion from the investment research profile.',
  'category_code': 'research_framework',
  'data_type': 'string',
  'formatter_code': 'text',
  'sort_mode': 'alpha',
  'filter_mode': 'text',
  'group_mode': 'none',
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'product_scope_json': [],
  'availability_rule_json': {'requires': ['instrument_research_profile']},
  'source_domain': 'research',
  'source_metric_code': 'instrument_research_profile.current_view',
  'default_width': 280,
  'default_visible': False},
 {'field_key': 'attr.manual_rating',
  'label': 'Manual Rating',
  'description': 'Current 1–5 analyst conviction rating; this is not an automatic quantitative '
                 'score.',
  'category_code': 'research_framework',
  'data_type': 'number',
  'formatter_code': 'decimal',
  'sort_mode': 'numeric',
  'filter_mode': 'range',
  'group_mode': 'none',
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'product_scope_json': [],
  'availability_rule_json': {'requires': ['instrument_research_profile']},
  'source_domain': 'research',
  'source_metric_code': 'instrument_research_profile.manual_rating',
  'default_width': 130,
  'default_visible': False},
 {'field_key': 'attr.primary_analyst',
  'label': 'Primary Analyst',
  'description': 'Current owner of the investment research profile.',
  'category_code': 'research_framework',
  'data_type': 'string',
  'formatter_code': 'text',
  'sort_mode': 'alpha',
  'filter_mode': 'multi_select',
  'group_mode': 'discrete',
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'product_scope_json': [],
  'availability_rule_json': {'requires': ['instrument_research_profile']},
  'source_domain': 'research',
  'source_metric_code': 'instrument_research_profile.primary_analyst',
  'default_width': 160,
  'default_visible': False},
 {'field_key': 'attr.research_next_review_date',
  'label': 'Next Research Review',
  'description': 'Scheduled date for the next full investment-thesis review.',
  'category_code': 'monitoring',
  'data_type': 'date',
  'formatter_code': 'date',
  'sort_mode': 'date',
  'filter_mode': 'date_range',
  'group_mode': 'none',
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'product_scope_json': [],
  'availability_rule_json': {'requires': ['instrument_research_profile']},
  'source_domain': 'research',
  'source_metric_code': 'instrument_research_profile.next_review_date',
  'default_width': 170,
  'default_visible': False},
 {'field_key': 'attr.research_note_count',
  'label': 'Research Records',
  'description': 'Number of active evidence, meeting, event, decision, risk, and review records.',
  'category_code': 'monitoring',
  'data_type': 'number',
  'formatter_code': 'decimal',
  'sort_mode': 'numeric',
  'filter_mode': 'range',
  'group_mode': 'none',
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'product_scope_json': [],
  'availability_rule_json': {'requires': ['instrument_research_note']},
  'source_domain': 'research',
  'source_metric_code': 'instrument_research_note.active_count',
  'default_width': 145,
  'default_visible': False},
 {'field_key': 'attr.research_next_follow_up_date',
  'label': 'Next Follow-up',
  'description': 'Earliest unresolved follow-up date across active research records.',
  'category_code': 'monitoring',
  'data_type': 'date',
  'formatter_code': 'date',
  'sort_mode': 'date',
  'filter_mode': 'date_range',
  'group_mode': 'none',
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'product_scope_json': [],
  'availability_rule_json': {'requires': ['instrument_research_note']},
  'source_domain': 'research',
  'source_metric_code': 'instrument_research_note.next_follow_up_date',
  'default_width': 160,
  'default_visible': False},
 {'field_key': 'attr.research_updated_at',
  'label': 'Research Updated',
  'description': 'Last update time of the current investment research profile.',
  'category_code': 'monitoring',
  'data_type': 'datetime',
  'formatter_code': 'datetime',
  'sort_mode': 'date',
  'filter_mode': 'date_range',
  'group_mode': 'none',
  'instrument_scope_json': ['public_fund', 'private_fund', 'etf', 'equity', 'index'],
  'product_scope_json': [],
  'availability_rule_json': {'requires': ['instrument_research_profile']},
  'source_domain': 'research',
  'source_metric_code': 'instrument_research_profile.updated_at',
  'default_width': 170,
  'default_visible': False}]
